CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,

    name TEXT NOT NULL,
    surname TEXT NOT NULL,
    is_male BOOLEAN,
    birthdate DATE,

    image_path TEXT,

    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT email_length_check CHECK (char_length(email) < 256),
    CONSTRAINT password_hash_check CHECK (char_length(password_hash) <= 256),
    CONSTRAINT name_length_check CHECK (char_length(name) < 256),
    CONSTRAINT surname_length_check CHECK (char_length(surname) < 256),
    CONSTRAINT image_path_length_check CHECK (char_length(image_path) < 2048)
);

CREATE TABLE emails (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    sender_id BIGINT NOT NULL REFERENCES users(id),

    header TEXT,
    body TEXT,

    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT header_length_check CHECK (char_length(header) < 255)

);


CREATE TABLE user_emails (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id BIGINT NOT NULL REFERENCES users(id),
    email_id BIGINT NOT NULL REFERENCES emails(id),

    is_sender BOOLEAN NOT NULL,

    is_read BOOLEAN NOT NULL DEFAULT false,
    is_deleted BOOLEAN NOT NULL DEFAULT false,
    is_starred BOOLEAN NOT NULL DEFAULT false,

    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT unique_user_email_sender UNIQUE (user_id, email_id, is_sender)

);

CREATE TABLE folders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,

    name TEXT NOT NULL,

    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
    UNIQUE(user_id, name)
);
CREATE TABLE folder_emails (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    folder_id BIGINT NOT NULL REFERENCES folders(id) ON DELETE CASCADE,
    email_id BIGINT NOT NULL REFERENCES emails(id) ON DELETE CASCADE,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    UNIQUE(folder_id, email_id)
);

CREATE INDEX idx_user_emails_receiver_id ON user_emails(user_id);
CREATE INDEX idx_user_emails_received_read ON user_emails(user_id, is_read);
CREATE INDEX idx_user_emails_receiver_created ON user_emails(user_id, created_at);
CREATE INDEX idx_user_emails_receiver_read_created ON user_emails(user_id, is_read, created_at DESC);
