CREATE TABLE users (
    id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    name TEXT NOT NULL,
    surname TEXT NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT email_length_check CHECK (char_length(email) < 256),
    CONSTRAINT password_hash_check CHECK (char_length(password_hash) = 256),
    CONSTRAINT name_length_check CHECK (char_length(name) < 256),
    CONSTRAINT surname_length_check CHECK (char_length(surname) < 256),
    CONSTRAINT email_valid CHECK (
        email ~ '^[a-zA-Z0-9.!#$%&''*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$'
    )
);

CREATE TABLE emails (
    id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id INT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    header TEXT,
    body TEXT,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT header_length_check CHECK (char_length(header) < 255)
);

CREATE TABLE user_emails (
    id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receiver_id INT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    email_id INT NOT NULL REFERENCES emails(id) ON DELETE RESTRICT,
    is_read BOOL NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
