CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    email         TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,

    name      TEXT NOT NULL,
    surname   TEXT NOT NULL,
    is_male   BOOLEAN,
    birthdate DATE,

    image_path TEXT,

    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT email_length_check         CHECK (char_length(email) < 256),
    CONSTRAINT password_hash_check        CHECK (char_length(password_hash) <= 256),
    CONSTRAINT name_length_check          CHECK (char_length(name) < 256),
    CONSTRAINT surname_length_check       CHECK (char_length(surname) < 256),
    CONSTRAINT image_path_length_check    CHECK (char_length(image_path) < 2048)
);

CREATE TABLE emails (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    sender_id    BIGINT REFERENCES users(id) ON DELETE SET NULL,
    sender_email TEXT   NOT NULL,

    header TEXT,
    body   TEXT,

    is_draft BOOLEAN NOT NULL DEFAULT false,

    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT header_length_check       CHECK (char_length(header) < 255),
    CONSTRAINT sender_email_length_check CHECK (char_length(sender_email) < 256),
    CONSTRAINT draft_has_internal_sender CHECK (NOT is_draft OR sender_id IS NOT NULL)
);
