--- Profiles ---
CREATE TABLE base_profiles (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    user_type user_type_enum NOT NULL DEFAULT 'user',
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT email_valid CHECK (
        email ~ '^[a-zA-Z0-9.!#$%&''*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$'
    ),
    CONSTRAINT email_length_check CHECK (char_length(email) <= 255)
);

CREATE TABLE profiles (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    base_profile_id INTEGER NOT NULL
        REFERENCES base_profiles(id) ON DELETE RESTRICT,
    username TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    middle_name TEXT,
    gender gender NOT NULL,
    avatar_path TEXT,
    department TEXT,
    position TEXT,
    group_name TEXT,
    auth_version INT NOT NULL,
    last_login_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP

    CONSTRAINT username_valid CHECK (username ~ '^[a-zA-Z0-9][a-zA-Z0-9._-]{2,62}[a-zA-Z0-9]$'),
    CONSTRAINT username_length_check CHECK (char_length(username) <= 64),

    CONSTRAINT first_name_length_check CHECK (char_length(first_name) <= 255),
    CONSTRAINT last_name_length_check CHECK (char_length(last_name) <= 255),
    CONSTRAINT middle_name_length_check CHECK (char_length(middle_name) <= 255),
    CONSTRAINT avatar_path_length_check CHECK (char_length(avatar_path) <= 2048),
    CONSTRAINT department_name_length_check CHECK (char_length(department) <= 255),
    CONSTRAINT position_name_length_check CHECK (char_length(position) <= 255),
    CONSTRAINT group_name_length_check CHECK (char_length(group_name) <= 255)
);

CREATE TABLE profile_settings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id INTEGER
        REFERENCES profiles(id) ON DELETE CASCADE,
    language TEXT NOT NULL DEFAULT 'RU',
    signature TEXT,
    notifications_email BOOLEAN NOT NULL DEFAULT FALSE,
    notifications_push BOOLEAN NOT NULL DEFAULT FALSE,
    messages_per_page INT NOT NULL DEFAULT 50,
    forwarding_address TEXT,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP

    CONSTRAINT email_valid CHECK (
        forwarding_address ~ '^[a-zA-Z0-9.!#$%&''*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$'
    )

    CONSTRAINT signature_length_check CHECK (char_length(signature) <= 2048),
    CONSTRAINT language_length_check CHECK (char_length(language) <= 5),
    CONSTRAINT forwarding_address_length_check CHECK (char_length(forwarding_address) <= 255),

    CONSTRAINT messages_per_page_limit CHECK (messages_per_page >= 10 AND messages_per_page <= 100)
);

--- User Groups ---
CREATE TABLE user_groups (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_code TEXT NOT NULL UNIQUE,
    group_name TEXT NOT NULL,
    description TEXT,
    group_origin group_type_enum NOT NULL DEFAULT 'custom',
    priority INTEGER NOT NULL DEFAULT 0,
    is_system BOOLEAN NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT group_code_length_check CHECK (char_length(group_code) <= 50),
    CONSTRAINT group_name_length_check CHECK (char_length(group_name) <= 255),
    CONSTRAINT description_length_check CHECK (char_length(description) <= 2048)
);

CREATE TABLE permissions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permission_code TEXT NOT NULL UNIQUE,
    permission_name TEXT NOT NULL,
    resource_type permission_resource_enum NOT NULL,
    action permission_action_enum NOT NULL,
    description TEXT,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT permission_code_length_check CHECK (char_length(permission_code) <= 100),
    CONSTRAINT permission_name_length_check CHECK (char_length(permission_name) <= 255),
    CONSTRAINT description_length_check CHECK (char_length(description) <= 2048)
);

CREATE TABLE group_permissions (
    group_id INTEGER NOT NULL
        REFERENCES user_groups(id) ON DELETE CASCADE,
    permission_id INTEGER NOT NULL
        REFERENCES permissions(id) ON DELETE CASCADE,
    grant_type BOOLEAN NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (group_id, permission_id)
);

CREATE TABLE user_group_membership (
    profile_id INTEGER NOT NULL
        REFERENCES profiles(id) ON DELETE CASCADE,
    group_id INTEGER NOT NULL
        REFERENCES user_groups(id) ON DELETE CASCADE,
    assigned_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    assigned_by INTEGER
        REFERENCES profiles(id) ON DELETE SET NULL,
    expires_at timestamptz,
    is_active BOOLEAN NOT NULL DEFAULT true,

    PRIMARY KEY (profile_id, group_id)
);

--- Messages & threads ---
CREATE TABLE threads (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject TEXT,
    participant_count INTEGER NOT NULL DEFAULT 2,
    last_message_at timestamptz,
    is_deleted BOOLEAN NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT subject_length_check CHECK (char_length(subject) <= 255),
    CONSTRAINT participant_count_limit CHECK (participant_count <= 100)
);

CREATE TABLE messages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    thread_id INTEGER NOT NULL
        REFERENCES threads(id) ON DELETE CASCADE,
    parent_message_id INTEGER
        REFERENCES messages(id) ON DELETE SET NULL,
    sender_profile_id INTEGER NOT NULL
        REFERENCES profiles(id) ON DELETE RESTRICT,
    subject TEXT,
    body TEXT NOT NULL,
    body_preview TEXT
        GENERATED ALWAYS AS (LEFT(body, 255)) STORED,
    is_draft BOOLEAN NOT NULL DEFAULT false,
    importance importance_enum NOT NULL DEFAULT 'normal',
    delivered_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT subject_length_check CHECK (char_length(subject) <= 255),
    CONSTRAINT body_preview_length_check CHECK (char_length(body_preview) <= 255)
);

CREATE TABLE message_recipients (
    message_id INTEGER NOT NULL
        REFERENCES messages(id) ON DELETE CASCADE,
    recipient_profile_id INTEGER NOT NULL
        REFERENCES profiles(id) ON DELETE CASCADE,
    recipient_type recipient_type_enum NOT NULL DEFAULT 'to',
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (message_id, recipient_profile_id)
);

CREATE TABLE message_statuses (
    profile_id INTEGER NOT NULL
        REFERENCES profiles(id) ON DELETE CASCADE,
    message_id INTEGER NOT NULL
        REFERENCES messages(id) ON DELETE CASCADE,
    is_read BOOLEAN NOT NULL DEFAULT false,
    is_starred BOOLEAN NOT NULL DEFAULT false,
    deleted_at timestamptz DEFAULT NULL,
    read_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (profile_id, message_id)
);

--- Folders ---
CREATE TABLE folders (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id INTEGER NOT NULL
        REFERENCES profiles(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    type folder_type_enum NOT NULL DEFAULT 'user_created',
    system_name TEXT,
    parent_folder_id INTEGER
        REFERENCES folders(id) ON DELETE CASCADE,
    sort_order INTEGER NOT NULL DEFAULT 0,
    color CHAR(7) DEFAULT '#808080', -- HEX color
    is_hidden BOOLEAN NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT valid_color CHECK (color ~ '^#[0-9A-Fa-f]{6}$'),
    CONSTRAINT unique_folder_name_per_profile UNIQUE (profile_id, name),
    CONSTRAINT check_system_folder_name CHECK (
        (type = 'system' AND system_name IS NOT NULL) OR
        (type != 'system' AND system_name IS NULL)
    ),
    CONSTRAINT name_length_check CHECK (char_length(name) <= 255),
    CONSTRAINT system_name_length_check CHECK (char_length(name) <= 50)
);

CREATE TABLE folder_messages (
    folder_id INTEGER NOT NULL
        REFERENCES folders(id) ON DELETE CASCADE,
    message_id INTEGER NOT NULL
        REFERENCES messages(id) ON DELETE CASCADE,
    added_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (folder_id, message_id)
);

--- Attachments ---
CREATE TABLE attachments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id INTEGER NOT NULL
        REFERENCES messages(id) ON DELETE CASCADE,
    file_name TEXT NOT NULL,
    file_size INTEGER NOT NULL,
    mime_type TEXT NOT NULL,
    storage_path TEXT NOT NULL,
    hash TEXT NOT NULL UNIQUE, -- SHA-256 hash
    is_inline BOOLEAN NOT NULL DEFAULT false,
    cid TEXT, -- Content-ID
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT correct_size CHECK (file_size > 0 AND file_size < 25000000),
    CONSTRAINT file_name_length_check CHECK (char_length(file_name) <= 255),
    CONSTRAINT mime_type_length_check CHECK (char_length(mime_type) <= 100),
    CONSTRAINT hash_length_check CHECK (char_length(hash) <= 64),
    CONSTRAINT cid_length_check CHECK (char_length(cid) <= 255)
);

--- Contacts ---
CREATE TABLE contacts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id INTEGER NOT NULL
        REFERENCES profiles(id) ON DELETE CASCADE,
    contact_email TEXT NOT NULL,
    first_name TEXT,
    last_name TEXT,
    phone TEXT,
    organization TEXT,
    notes TEXT,
    is_favorite BOOLEAN NOT NULL DEFAULT false,
    contact_type contact_type_enum NOT NULL DEFAULT 'external',
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT unique_contact_per_profile UNIQUE (profile_id, contact_email),
    CONSTRAINT contact_email_valid CHECK (
        contact_email ~ '^[a-zA-Z0-9.!#$%&''*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$'
    ),
    CONSTRAINT contact_email_length_check CHECK (char_length(contact_email) <= 255),
    CONSTRAINT first_name_length_check CHECK (char_length(first_name) <= 255),
    CONSTRAINT last_name_length_check CHECK (char_length(last_name) <= 255),
    CONSTRAINT phone_length_check CHECK (char_length(phone) <= 50),
    CONSTRAINT organization_length_check CHECK (char_length(organization) <= 255),
    CONSTRAINT notes_length_check CHECK (char_length(notes) <= 255)
);

CREATE TABLE contact_categories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id INTEGER NOT NULL
        REFERENCES profiles(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    type contact_category_type_enum NOT NULL DEFAULT 'user_defined',
    system_type TEXT,
    is_auto_generated BOOLEAN NOT NULL DEFAULT false,
    auto_update_rule JSONB,
    description TEXT,
    color CHAR(7) DEFAULT '#808080',
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT valid_category_color CHECK (color ~ '^#[0-9A-Fa-f]{6}$'),
    CONSTRAINT unique_category_name_per_profile UNIQUE (profile_id, name),
    CONSTRAINT check_system_category CHECK (
        (type = 'system' AND system_type IS NOT NULL) OR
        (type != 'system' AND system_type IS NULL)
    ),
    CONSTRAINT name_length_check CHECK (char_length(name) <= 255),
    CONSTRAINT system_type_length_check CHECK (char_length(system_type) <= 50)
);

CREATE TABLE contact_category_members (
    category_id INTEGER NOT NULL
        REFERENCES contact_categories(id) ON DELETE CASCADE,
    contact_id INTEGER NOT NULL
        REFERENCES contacts(id) ON DELETE CASCADE,
    added_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_auto_added BOOLEAN NOT NULL DEFAULT false,

    PRIMARY KEY (category_id, contact_id)
);

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

--- Триггеры для обновления updated_at ---
CREATE TRIGGER update_base_profiles_updated_at
    BEFORE UPDATE ON base_profiles
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_profiles_updated_at
    BEFORE UPDATE ON profiles
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_profile_settings_updated_at
    BEFORE UPDATE ON profile_settings
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_user_groups_updated_at
    BEFORE UPDATE ON user_groups
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_threads_updated_at
    BEFORE UPDATE ON threads
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_messages_updated_at
    BEFORE UPDATE ON messages
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_message_statuses_updated_at
    BEFORE UPDATE ON message_statuses
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_folders_updated_at
    BEFORE UPDATE ON folders
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_attachments_updated_at
    BEFORE UPDATE ON attachments
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_contacts_updated_at
    BEFORE UPDATE ON contacts
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_contact_categories_updated_at
    BEFORE UPDATE ON contact_categories
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

--- Комментарии ---
COMMENT ON TABLE base_profiles IS 'Базовые профили всех пользователей (включая внешних)';
COMMENT ON TABLE profiles IS 'Расширенные профили только для внутренних пользователей';
COMMENT ON TABLE profile_settings IS 'Настройки пользователей';
COMMENT ON TABLE user_groups IS 'Группы пользователей';
COMMENT ON TABLE permissions IS 'Разрешения для доступа к ресурсам';
COMMENT ON TABLE group_permissions IS 'Связь групп и разрешений';
COMMENT ON TABLE user_group_membership IS 'Членство пользователей в группах';
COMMENT ON TABLE threads IS 'Цепочки сообщений (переписки)';
COMMENT ON TABLE messages IS 'Сообщения в переписках';
COMMENT ON TABLE message_recipients IS 'Получатели сообщений';
COMMENT ON TABLE message_statuses IS 'Статусы сообщений для каждого получателя';
COMMENT ON TABLE folders IS 'Папки для организации сообщений';
COMMENT ON TABLE folder_messages IS 'Связь сообщений с папками';
COMMENT ON TABLE attachments IS 'Вложения к сообщениям';
COMMENT ON TABLE contacts IS 'Контакты пользователей';
COMMENT ON TABLE contact_categories IS 'Категории для группировки контактов';
COMMENT ON TABLE contact_category_members IS 'Принадлежность контактов к категориям';
