CREATE TABLE support_admins (
    user_id INT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE support_tickets (
    id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    support_id INT REFERENCES users(id) ON DELETE SET NULL,
    subject TEXT NOT NULL,
    category TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'open',
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    closed_at  timestamptz,

    CONSTRAINT subject_length_check CHECK (char_length(subject) BETWEEN 1 AND 255),
    CONSTRAINT category_check CHECK (category IN ('bug','proposal','complaint','other')),
    CONSTRAINT status_check CHECK (status IN ('open','in_progress','closed')),
    CONSTRAINT closed_at_consistency CHECK (
        (status = 'closed' AND closed_at IS NOT NULL) OR
        (status <> 'closed' AND closed_at IS NULL)
    )
);

CREATE INDEX idx_support_tickets_user ON support_tickets(user_id, created_at DESC);
CREATE INDEX idx_support_tickets_status ON support_tickets(status);
CREATE INDEX idx_support_tickets_support_id ON support_tickets(support_id) WHERE support_id IS NOT NULL;

CREATE TABLE support_messages (
    id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id INT NOT NULL REFERENCES support_tickets(id) ON DELETE CASCADE,
    author_id INT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    body TEXT NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT body_length_check CHECK (char_length(body) BETWEEN 1 AND 10000)
);

CREATE INDEX idx_support_messages_ticket ON support_messages(ticket_id, id);

CREATE TRIGGER trigger_update_updated_at
    BEFORE UPDATE ON support_tickets
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();