CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,

    name TEXT NOT NULL,
    surname TEXT NOT NULL,

    is_male BOOLEAN,
    birthdate DATE,

    image_path TEXT,

    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT email_length_check
        CHECK (char_length(email) < 256),

    CONSTRAINT password_hash_check
        CHECK (char_length(password_hash) <= 256),

    CONSTRAINT name_length_check
        CHECK (char_length(name) < 256),

    CONSTRAINT surname_length_check
        CHECK (char_length(surname) < 256),

    CONSTRAINT image_path_length_check
        CHECK (char_length(image_path) < 2048)
);