version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocyclo
    - goconst
    - gofumpt
    - goimports
    - misspell

run:
  timeout: 5m
