services:
  postgres:
    image: postgres:16.3
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DBNAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DBNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    command: server --console-address ":9090" /data
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  user-service:
    image: ghcr.io/go-park-mail-ru/2026_1_pushtomain/user:latest
    pull_policy: always
    env_file:
      - .env
    volumes:
      - ./configs:/app/configs:ro
      - ./db/migrations:/app/db/migrations:ro
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "netstat -tlnp | grep 50051"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    restart: unless-stopped

  email-service:
    image: ghcr.io/go-park-mail-ru/2026_1_pushtomain/email:latest
    pull_policy: always
    env_file:
      - .env
    volumes:
      - ./configs:/app/configs:ro
      - ./db/migrations:/app/db/migrations:ro
    ports:
      - "8082:8082"
    depends_on:
      postgres:
        condition: service_healthy
      user-service:
        condition: service_healthy
    restart: unless-stopped

  folder-service:
    image: ghcr.io/go-park-mail-ru/2026_1_pushtomain/folder:latest
    pull_policy: always
    env_file:
      - .env
    volumes:
      - ./configs:/app/configs:ro
      - ./db/migrations:/app/db/migrations:ro
    ports:
      - "8083:8083"
    depends_on:
      postgres:
        condition: service_healthy
      email-service:
        condition: service_started
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./configs/prometheus/config.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    restart: unless-stopped

  node_exporter:
    image: prom/node-exporter:latest
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--path.rootfs=/rootfs"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./configs/grafana:/etc/grafana/provisioning:ro
    depends_on:
      - prometheus
    restart: unless-stopped

  postfix:
    build:
      context: .
      dockerfile: microservices/postfix/Dockerfile
    volumes:
      - ./configs/postfix/main.cf:/etc/postfix/main.cf:ro
      - ./configs/postfix/master.cf:/etc/postfix/master.cf:ro
      - ./certs/postfix:/etc/ssl/postfix:ro
      - postfix_queue:/var/spool/postfix
    ports:
      - "25:25"
      - "587:587"
    hostname: mail.e-smail.ru
    restart: unless-stopped

volumes:
  postgres_data:
  minio_data:
  prometheus_data:
  grafana_data:
  postfix_queue:
