# dev config

port: 8083

jwt:
  secret: super-secret-key
  expire_hours: 24

cors:
  allowed_origins:
    - https://e-smail.ru

  allowed_methods:
    - POST
    - GET
    - OPTIONS
    - PUT
    - DELETE

  allowed_headers:
    - Content-Type
    - Authorization
    - X-CSRF-Token

logger:
  level: debug
  environment: development
  output_path: stdout
  error_output_path: stderr

postgres:
  host: folder-postgres
  port: 5432
  user: postgres
  password: postgres
  dbname: folders_db
  sslmode: disable
  migrations_path: "file://db/migrations"

grpc:
  folder_port: "50053"

grpc_clients:
  email_service: "email-service:50052"