CREATE TABLE folders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id BIGINT NOT NULL,

    name TEXT NOT NULL,

    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    UNIQUE(user_id, name)
);

CREATE TABLE folder_emails (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    folder_id BIGINT NOT NULL REFERENCES folders(id) ON DELETE CASCADE,

    email_id BIGINT NOT NULL,

    created_at timestamptz NOT NULL DEFAULT NOW(),

    UNIQUE(folder_id, email_id)
);