FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build \
    -ldflags="-s -w" \
    -o ./build/folder-service \
    ./cmd/folder/main.go

# ─────────────────────────────────────────────
FROM alpine:latest

RUN apk --no-cache add ca-certificates tzdata

WORKDIR /app

COPY --from=builder /app/build/folder-service .

EXPOSE 8083 50053

ENTRYPOINT ["./folder-service", "--config", "configs/folder/config.yaml"]
