// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/folder/folder.proto

package folder

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserFoldersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserFoldersRequest) Reset() {
	*x = GetUserFoldersRequest{}
	mi := &file_proto_folder_folder_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserFoldersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserFoldersRequest) ProtoMessage() {}

func (x *GetUserFoldersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_folder_folder_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserFoldersRequest.ProtoReflect.Descriptor instead.
func (*GetUserFoldersRequest) Descriptor() ([]byte, []int) {
	return file_proto_folder_folder_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserFoldersRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserFoldersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Folders       []*Folder              `protobuf:"bytes,1,rep,name=folders,proto3" json:"folders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserFoldersResponse) Reset() {
	*x = GetUserFoldersResponse{}
	mi := &file_proto_folder_folder_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserFoldersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserFoldersResponse) ProtoMessage() {}

func (x *GetUserFoldersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_folder_folder_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserFoldersResponse.ProtoReflect.Descriptor instead.
func (*GetUserFoldersResponse) Descriptor() ([]byte, []int) {
	return file_proto_folder_folder_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserFoldersResponse) GetFolders() []*Folder {
	if x != nil {
		return x.Folders
	}
	return nil
}

type Folder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Folder) Reset() {
	*x = Folder{}
	mi := &file_proto_folder_folder_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Folder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Folder) ProtoMessage() {}

func (x *Folder) ProtoReflect() protoreflect.Message {
	mi := &file_proto_folder_folder_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Folder.ProtoReflect.Descriptor instead.
func (*Folder) Descriptor() ([]byte, []int) {
	return file_proto_folder_folder_proto_rawDescGZIP(), []int{2}
}

func (x *Folder) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Folder) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_proto_folder_folder_proto protoreflect.FileDescriptor

const file_proto_folder_folder_proto_rawDesc = "" +
	"\n" +
	"\x19proto/folder/folder.proto\x12\x06folder\"0\n" +
	"\x15GetUserFoldersRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"B\n" +
	"\x16GetUserFoldersResponse\x12(\n" +
	"\afolders\x18\x01 \x03(\v2\x0e.folder.FolderR\afolders\",\n" +
	"\x06Folder\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name2`\n" +
	"\rFolderService\x12O\n" +
	"\x0eGetUserFolders\x12\x1d.folder.GetUserFoldersRequest\x1a\x1e.folder.GetUserFoldersResponseB\x10Z\x0e./proto/folderb\x06proto3"

var (
	file_proto_folder_folder_proto_rawDescOnce sync.Once
	file_proto_folder_folder_proto_rawDescData []byte
)

func file_proto_folder_folder_proto_rawDescGZIP() []byte {
	file_proto_folder_folder_proto_rawDescOnce.Do(func() {
		file_proto_folder_folder_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_folder_folder_proto_rawDesc), len(file_proto_folder_folder_proto_rawDesc)))
	})
	return file_proto_folder_folder_proto_rawDescData
}

var file_proto_folder_folder_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_folder_folder_proto_goTypes = []any{
	(*GetUserFoldersRequest)(nil),  // 0: folder.GetUserFoldersRequest
	(*GetUserFoldersResponse)(nil), // 1: folder.GetUserFoldersResponse
	(*Folder)(nil),                 // 2: folder.Folder
}
var file_proto_folder_folder_proto_depIdxs = []int32{
	2, // 0: folder.GetUserFoldersResponse.folders:type_name -> folder.Folder
	0, // 1: folder.FolderService.GetUserFolders:input_type -> folder.GetUserFoldersRequest
	1, // 2: folder.FolderService.GetUserFolders:output_type -> folder.GetUserFoldersResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_folder_folder_proto_init() }
func file_proto_folder_folder_proto_init() {
	if File_proto_folder_folder_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_folder_folder_proto_rawDesc), len(file_proto_folder_folder_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_folder_folder_proto_goTypes,
		DependencyIndexes: file_proto_folder_folder_proto_depIdxs,
		MessageInfos:      file_proto_folder_folder_proto_msgTypes,
	}.Build()
	File_proto_folder_folder_proto = out.File
	file_proto_folder_folder_proto_goTypes = nil
	file_proto_folder_folder_proto_depIdxs = nil
}
