// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package handler

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson408d1214DecodeGithubComGoParkMailRu20261PushToMainMicroservicesFolderDeliveryHttp(in *jlexer.Lexer, out *GetEmailsFromFolderResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "emails":
			if in.IsNull() {
				in.Skip()
				out.Emails = nil
			} else {
				in.Delim('[')
				if out.Emails == nil {
					if !in.IsDelim(']') {
						out.Emails = make([]EmailResponse, 0, 0)
					} else {
						out.Emails = []EmailResponse{}
					}
				} else {
					out.Emails = (out.Emails)[:0]
				}
				for !in.IsDelim(']') {
					var v1 EmailResponse
					if in.IsNull() {
						in.Skip()
					} else {
						(v1).UnmarshalEasyJSON(in)
					}
					out.Emails = append(out.Emails, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "limit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Limit = int(in.Int())
			}
		case "offset":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Offset = int(in.Int())
			}
		case "total":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Total = int(in.Int())
			}
		case "unread_count":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UnreadCount = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson408d1214EncodeGithubComGoParkMailRu20261PushToMainMicroservicesFolderDeliveryHttp(out *jwriter.Writer, in GetEmailsFromFolderResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"emails\":"
		out.RawString(prefix[1:])
		if in.Emails == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Emails {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix)
		out.Int(int(in.Limit))
	}
	{
		const prefix string = ",\"offset\":"
		out.RawString(prefix)
		out.Int(int(in.Offset))
	}
	{
		const prefix string = ",\"total\":"
		out.RawString(prefix)
		out.Int(int(in.Total))
	}
	{
		const prefix string = ",\"unread_count\":"
		out.RawString(prefix)
		out.Int(int(in.UnreadCount))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetEmailsFromFolderResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson408d1214EncodeGithubComGoParkMailRu20261PushToMainMicroservicesFolderDeliveryHttp(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetEmailsFromFolderResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson408d1214EncodeGithubComGoParkMailRu20261PushToMainMicroservicesFolderDeliveryHttp(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetEmailsFromFolderResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson408d1214DecodeGithubComGoParkMailRu20261PushToMainMicroservicesFolderDeliveryHttp(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetEmailsFromFolderResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson408d1214DecodeGithubComGoParkMailRu20261PushToMainMicroservicesFolderDeliveryHttp(l, v)
}
func easyjson408d1214DecodeGithubComGoParkMailRu20261PushToMainMicroservicesFolderDeliveryHttp1(in *jlexer.Lexer, out *EmailResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int64(in.Int64())
			}
		case "sender_email":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SenderEmail = string(in.String())
			}
		case "sender_name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SenderName = string(in.String())
			}
		case "sender_surname":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SenderSurname = string(in.String())
			}
		case "receiver_list":
			if in.IsNull() {
				in.Skip()
				out.ReceiverList = nil
			} else {
				in.Delim('[')
				if out.ReceiverList == nil {
					if !in.IsDelim(']') {
						out.ReceiverList = make([]string, 0, 4)
					} else {
						out.ReceiverList = []string{}
					}
				} else {
					out.ReceiverList = (out.ReceiverList)[:0]
				}
				for !in.IsDelim(']') {
					var v4 string
					if in.IsNull() {
						in.Skip()
					} else {
						v4 = string(in.String())
					}
					out.ReceiverList = append(out.ReceiverList, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "header":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Header = string(in.String())
			}
		case "body":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Body = string(in.String())
			}
		case "created_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.CreatedAt).UnmarshalJSON(data))
				}
			}
		case "is_read":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsRead = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson408d1214EncodeGithubComGoParkMailRu20261PushToMainMicroservicesFolderDeliveryHttp1(out *jwriter.Writer, in EmailResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"sender_email\":"
		out.RawString(prefix)
		out.String(string(in.SenderEmail))
	}
	{
		const prefix string = ",\"sender_name\":"
		out.RawString(prefix)
		out.String(string(in.SenderName))
	}
	{
		const prefix string = ",\"sender_surname\":"
		out.RawString(prefix)
		out.String(string(in.SenderSurname))
	}
	{
		const prefix string = ",\"receiver_list\":"
		out.RawString(prefix)
		if in.ReceiverList == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.ReceiverList {
				if v5 > 0 {
					out.RawByte(',')
				}
				out.String(string(v6))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"header\":"
		out.RawString(prefix)
		out.String(string(in.Header))
	}
	{
		const prefix string = ",\"body\":"
		out.RawString(prefix)
		out.String(string(in.Body))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"is_read\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsRead))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v EmailResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson408d1214EncodeGithubComGoParkMailRu20261PushToMainMicroservicesFolderDeliveryHttp1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v EmailResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson408d1214EncodeGithubComGoParkMailRu20261PushToMainMicroservicesFolderDeliveryHttp1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *EmailResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson408d1214DecodeGithubComGoParkMailRu20261PushToMainMicroservicesFolderDeliveryHttp1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *EmailResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson408d1214DecodeGithubComGoParkMailRu20261PushToMainMicroservicesFolderDeliveryHttp1(l, v)
}
func easyjson408d1214DecodeGithubComGoParkMailRu20261PushToMainMicroservicesFolderDeliveryHttp2(in *jlexer.Lexer, out *DeleteEmailsFromFolderRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "emails_id":
			if in.IsNull() {
				in.Skip()
				out.EmailsID = nil
			} else {
				in.Delim('[')
				if out.EmailsID == nil {
					if !in.IsDelim(']') {
						out.EmailsID = make([]int64, 0, 8)
					} else {
						out.EmailsID = []int64{}
					}
				} else {
					out.EmailsID = (out.EmailsID)[:0]
				}
				for !in.IsDelim(']') {
					var v7 int64
					if in.IsNull() {
						in.Skip()
					} else {
						v7 = int64(in.Int64())
					}
					out.EmailsID = append(out.EmailsID, v7)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson408d1214EncodeGithubComGoParkMailRu20261PushToMainMicroservicesFolderDeliveryHttp2(out *jwriter.Writer, in DeleteEmailsFromFolderRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"emails_id\":"
		out.RawString(prefix[1:])
		if in.EmailsID == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v8, v9 := range in.EmailsID {
				if v8 > 0 {
					out.RawByte(',')
				}
				out.Int64(int64(v9))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v DeleteEmailsFromFolderRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson408d1214EncodeGithubComGoParkMailRu20261PushToMainMicroservicesFolderDeliveryHttp2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v DeleteEmailsFromFolderRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson408d1214EncodeGithubComGoParkMailRu20261PushToMainMicroservicesFolderDeliveryHttp2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *DeleteEmailsFromFolderRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson408d1214DecodeGithubComGoParkMailRu20261PushToMainMicroservicesFolderDeliveryHttp2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *DeleteEmailsFromFolderRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson408d1214DecodeGithubComGoParkMailRu20261PushToMainMicroservicesFolderDeliveryHttp2(l, v)
}
func easyjson408d1214DecodeGithubComGoParkMailRu20261PushToMainMicroservicesFolderDeliveryHttp3(in *jlexer.Lexer, out *CreateNewFolderResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "folder_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson408d1214EncodeGithubComGoParkMailRu20261PushToMainMicroservicesFolderDeliveryHttp3(out *jwriter.Writer, in CreateNewFolderResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"folder_id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateNewFolderResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson408d1214EncodeGithubComGoParkMailRu20261PushToMainMicroservicesFolderDeliveryHttp3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateNewFolderResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson408d1214EncodeGithubComGoParkMailRu20261PushToMainMicroservicesFolderDeliveryHttp3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateNewFolderResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson408d1214DecodeGithubComGoParkMailRu20261PushToMainMicroservicesFolderDeliveryHttp3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateNewFolderResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson408d1214DecodeGithubComGoParkMailRu20261PushToMainMicroservicesFolderDeliveryHttp3(l, v)
}
func easyjson408d1214DecodeGithubComGoParkMailRu20261PushToMainMicroservicesFolderDeliveryHttp4(in *jlexer.Lexer, out *CreateNewFolderRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "folder_name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FolderName = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson408d1214EncodeGithubComGoParkMailRu20261PushToMainMicroservicesFolderDeliveryHttp4(out *jwriter.Writer, in CreateNewFolderRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"folder_name\":"
		out.RawString(prefix[1:])
		out.String(string(in.FolderName))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateNewFolderRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson408d1214EncodeGithubComGoParkMailRu20261PushToMainMicroservicesFolderDeliveryHttp4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateNewFolderRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson408d1214EncodeGithubComGoParkMailRu20261PushToMainMicroservicesFolderDeliveryHttp4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateNewFolderRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson408d1214DecodeGithubComGoParkMailRu20261PushToMainMicroservicesFolderDeliveryHttp4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateNewFolderRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson408d1214DecodeGithubComGoParkMailRu20261PushToMainMicroservicesFolderDeliveryHttp4(l, v)
}
func easyjson408d1214DecodeGithubComGoParkMailRu20261PushToMainMicroservicesFolderDeliveryHttp5(in *jlexer.Lexer, out *ChangeFolderNameRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "folder_name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FolderName = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson408d1214EncodeGithubComGoParkMailRu20261PushToMainMicroservicesFolderDeliveryHttp5(out *jwriter.Writer, in ChangeFolderNameRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"folder_name\":"
		out.RawString(prefix[1:])
		out.String(string(in.FolderName))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ChangeFolderNameRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson408d1214EncodeGithubComGoParkMailRu20261PushToMainMicroservicesFolderDeliveryHttp5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ChangeFolderNameRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson408d1214EncodeGithubComGoParkMailRu20261PushToMainMicroservicesFolderDeliveryHttp5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ChangeFolderNameRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson408d1214DecodeGithubComGoParkMailRu20261PushToMainMicroservicesFolderDeliveryHttp5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ChangeFolderNameRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson408d1214DecodeGithubComGoParkMailRu20261PushToMainMicroservicesFolderDeliveryHttp5(l, v)
}
func easyjson408d1214DecodeGithubComGoParkMailRu20261PushToMainMicroservicesFolderDeliveryHttp6(in *jlexer.Lexer, out *AddEmailsInFolderRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "emails_id":
			if in.IsNull() {
				in.Skip()
				out.EmailsID = nil
			} else {
				in.Delim('[')
				if out.EmailsID == nil {
					if !in.IsDelim(']') {
						out.EmailsID = make([]int64, 0, 8)
					} else {
						out.EmailsID = []int64{}
					}
				} else {
					out.EmailsID = (out.EmailsID)[:0]
				}
				for !in.IsDelim(']') {
					var v10 int64
					if in.IsNull() {
						in.Skip()
					} else {
						v10 = int64(in.Int64())
					}
					out.EmailsID = append(out.EmailsID, v10)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson408d1214EncodeGithubComGoParkMailRu20261PushToMainMicroservicesFolderDeliveryHttp6(out *jwriter.Writer, in AddEmailsInFolderRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"emails_id\":"
		out.RawString(prefix[1:])
		if in.EmailsID == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v11, v12 := range in.EmailsID {
				if v11 > 0 {
					out.RawByte(',')
				}
				out.Int64(int64(v12))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AddEmailsInFolderRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson408d1214EncodeGithubComGoParkMailRu20261PushToMainMicroservicesFolderDeliveryHttp6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AddEmailsInFolderRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson408d1214EncodeGithubComGoParkMailRu20261PushToMainMicroservicesFolderDeliveryHttp6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AddEmailsInFolderRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson408d1214DecodeGithubComGoParkMailRu20261PushToMainMicroservicesFolderDeliveryHttp6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AddEmailsInFolderRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson408d1214DecodeGithubComGoParkMailRu20261PushToMainMicroservicesFolderDeliveryHttp6(l, v)
}
