// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package handler

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson56de76c1DecodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp(in *jlexer.Lexer, out *UpdateDraftRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "header":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Header = string(in.String())
			}
		case "body":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Body = string(in.String())
			}
		case "receivers":
			if in.IsNull() {
				in.Skip()
				out.Receivers = nil
			} else {
				in.Delim('[')
				if out.Receivers == nil {
					if !in.IsDelim(']') {
						out.Receivers = make([]string, 0, 4)
					} else {
						out.Receivers = []string{}
					}
				} else {
					out.Receivers = (out.Receivers)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					if in.IsNull() {
						in.Skip()
					} else {
						v1 = string(in.String())
					}
					out.Receivers = append(out.Receivers, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "is_anonymous":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsAnonymous = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson56de76c1EncodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp(out *jwriter.Writer, in UpdateDraftRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"header\":"
		out.RawString(prefix[1:])
		out.String(string(in.Header))
	}
	{
		const prefix string = ",\"body\":"
		out.RawString(prefix)
		out.String(string(in.Body))
	}
	{
		const prefix string = ",\"receivers\":"
		out.RawString(prefix)
		if in.Receivers == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Receivers {
				if v2 > 0 {
					out.RawByte(',')
				}
				out.String(string(v3))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"is_anonymous\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsAnonymous))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UpdateDraftRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson56de76c1EncodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UpdateDraftRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson56de76c1EncodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UpdateDraftRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson56de76c1DecodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UpdateDraftRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson56de76c1DecodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp(l, v)
}
func easyjson56de76c1DecodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp1(in *jlexer.Lexer, out *SendEmailResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "email_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int64(in.Int64())
			}
		case "from":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SenderID = int64(in.Int64())
			}
		case "header":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Header = string(in.String())
			}
		case "body":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Body = string(in.String())
			}
		case "is_anonymous":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsAnonymous = bool(in.Bool())
			}
		case "parent_email_id":
			if in.IsNull() {
				in.Skip()
				out.ParentEmailID = nil
			} else {
				if out.ParentEmailID == nil {
					out.ParentEmailID = new(int64)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.ParentEmailID = int64(in.Int64())
				}
			}
		case "created_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.CreatedAt).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson56de76c1EncodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp1(out *jwriter.Writer, in SendEmailResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"email_id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"from\":"
		out.RawString(prefix)
		out.Int64(int64(in.SenderID))
	}
	{
		const prefix string = ",\"header\":"
		out.RawString(prefix)
		out.String(string(in.Header))
	}
	{
		const prefix string = ",\"body\":"
		out.RawString(prefix)
		out.String(string(in.Body))
	}
	{
		const prefix string = ",\"is_anonymous\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsAnonymous))
	}
	if in.ParentEmailID != nil {
		const prefix string = ",\"parent_email_id\":"
		out.RawString(prefix)
		out.Int64(int64(*in.ParentEmailID))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SendEmailResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson56de76c1EncodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SendEmailResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson56de76c1EncodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SendEmailResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson56de76c1DecodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SendEmailResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson56de76c1DecodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp1(l, v)
}
func easyjson56de76c1DecodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp2(in *jlexer.Lexer, out *SendEmailRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "header":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Header = string(in.String())
			}
		case "body":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Body = string(in.String())
			}
		case "receivers":
			if in.IsNull() {
				in.Skip()
				out.Receivers = nil
			} else {
				in.Delim('[')
				if out.Receivers == nil {
					if !in.IsDelim(']') {
						out.Receivers = make([]string, 0, 4)
					} else {
						out.Receivers = []string{}
					}
				} else {
					out.Receivers = (out.Receivers)[:0]
				}
				for !in.IsDelim(']') {
					var v4 string
					if in.IsNull() {
						in.Skip()
					} else {
						v4 = string(in.String())
					}
					out.Receivers = append(out.Receivers, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "is_anonymous":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsAnonymous = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson56de76c1EncodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp2(out *jwriter.Writer, in SendEmailRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"header\":"
		out.RawString(prefix[1:])
		out.String(string(in.Header))
	}
	{
		const prefix string = ",\"body\":"
		out.RawString(prefix)
		out.String(string(in.Body))
	}
	{
		const prefix string = ",\"receivers\":"
		out.RawString(prefix)
		if in.Receivers == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.Receivers {
				if v5 > 0 {
					out.RawByte(',')
				}
				out.String(string(v6))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"is_anonymous\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsAnonymous))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SendEmailRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson56de76c1EncodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SendEmailRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson56de76c1EncodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SendEmailRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson56de76c1DecodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SendEmailRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson56de76c1DecodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp2(l, v)
}
func easyjson56de76c1DecodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp3(in *jlexer.Lexer, out *ReplyRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "header":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Header = string(in.String())
			}
		case "body":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Body = string(in.String())
			}
		case "is_anonymous":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsAnonymous = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson56de76c1EncodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp3(out *jwriter.Writer, in ReplyRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"header\":"
		out.RawString(prefix[1:])
		out.String(string(in.Header))
	}
	{
		const prefix string = ",\"body\":"
		out.RawString(prefix)
		out.String(string(in.Body))
	}
	{
		const prefix string = ",\"is_anonymous\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsAnonymous))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ReplyRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson56de76c1EncodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ReplyRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson56de76c1EncodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ReplyRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson56de76c1DecodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ReplyRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson56de76c1DecodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp3(l, v)
}
func easyjson56de76c1DecodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp4(in *jlexer.Lexer, out *MyEmailResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int64(in.Int64())
			}
		case "header":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Header = string(in.String())
			}
		case "body":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Body = string(in.String())
			}
		case "created_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.CreatedAt).UnmarshalJSON(data))
				}
			}
		case "is_read":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsRead = bool(in.Bool())
			}
		case "is_starred":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsStarred = bool(in.Bool())
			}
		case "is_anonymous":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsAnonymous = bool(in.Bool())
			}
		case "parent_email_id":
			if in.IsNull() {
				in.Skip()
				out.ParentEmailID = nil
			} else {
				if out.ParentEmailID == nil {
					out.ParentEmailID = new(int64)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.ParentEmailID = int64(in.Int64())
				}
			}
		case "receivers_emails":
			if in.IsNull() {
				in.Skip()
				out.ReceiversEmails = nil
			} else {
				in.Delim('[')
				if out.ReceiversEmails == nil {
					if !in.IsDelim(']') {
						out.ReceiversEmails = make([]string, 0, 4)
					} else {
						out.ReceiversEmails = []string{}
					}
				} else {
					out.ReceiversEmails = (out.ReceiversEmails)[:0]
				}
				for !in.IsDelim(']') {
					var v7 string
					if in.IsNull() {
						in.Skip()
					} else {
						v7 = string(in.String())
					}
					out.ReceiversEmails = append(out.ReceiversEmails, v7)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson56de76c1EncodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp4(out *jwriter.Writer, in MyEmailResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"header\":"
		out.RawString(prefix)
		out.String(string(in.Header))
	}
	{
		const prefix string = ",\"body\":"
		out.RawString(prefix)
		out.String(string(in.Body))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"is_read\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsRead))
	}
	{
		const prefix string = ",\"is_starred\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsStarred))
	}
	{
		const prefix string = ",\"is_anonymous\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsAnonymous))
	}
	if in.ParentEmailID != nil {
		const prefix string = ",\"parent_email_id\":"
		out.RawString(prefix)
		out.Int64(int64(*in.ParentEmailID))
	}
	{
		const prefix string = ",\"receivers_emails\":"
		out.RawString(prefix)
		if in.ReceiversEmails == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v8, v9 := range in.ReceiversEmails {
				if v8 > 0 {
					out.RawByte(',')
				}
				out.String(string(v9))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MyEmailResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson56de76c1EncodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MyEmailResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson56de76c1EncodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MyEmailResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson56de76c1DecodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MyEmailResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson56de76c1DecodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp4(l, v)
}
func easyjson56de76c1DecodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp5(in *jlexer.Lexer, out *MarkEmailsAsReadRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "email_ids":
			if in.IsNull() {
				in.Skip()
				out.EmailIDs = nil
			} else {
				in.Delim('[')
				if out.EmailIDs == nil {
					if !in.IsDelim(']') {
						out.EmailIDs = make([]int64, 0, 8)
					} else {
						out.EmailIDs = []int64{}
					}
				} else {
					out.EmailIDs = (out.EmailIDs)[:0]
				}
				for !in.IsDelim(']') {
					var v10 int64
					if in.IsNull() {
						in.Skip()
					} else {
						v10 = int64(in.Int64())
					}
					out.EmailIDs = append(out.EmailIDs, v10)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson56de76c1EncodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp5(out *jwriter.Writer, in MarkEmailsAsReadRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"email_ids\":"
		out.RawString(prefix[1:])
		if in.EmailIDs == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v11, v12 := range in.EmailIDs {
				if v11 > 0 {
					out.RawByte(',')
				}
				out.Int64(int64(v12))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MarkEmailsAsReadRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson56de76c1EncodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MarkEmailsAsReadRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson56de76c1EncodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MarkEmailsAsReadRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson56de76c1DecodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MarkEmailsAsReadRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson56de76c1DecodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp5(l, v)
}
func easyjson56de76c1DecodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp6(in *jlexer.Lexer, out *IDsRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "ids":
			if in.IsNull() {
				in.Skip()
				out.IDs = nil
			} else {
				in.Delim('[')
				if out.IDs == nil {
					if !in.IsDelim(']') {
						out.IDs = make([]int64, 0, 8)
					} else {
						out.IDs = []int64{}
					}
				} else {
					out.IDs = (out.IDs)[:0]
				}
				for !in.IsDelim(']') {
					var v13 int64
					if in.IsNull() {
						in.Skip()
					} else {
						v13 = int64(in.Int64())
					}
					out.IDs = append(out.IDs, v13)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson56de76c1EncodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp6(out *jwriter.Writer, in IDsRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"ids\":"
		out.RawString(prefix[1:])
		if in.IDs == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v14, v15 := range in.IDs {
				if v14 > 0 {
					out.RawByte(',')
				}
				out.Int64(int64(v15))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v IDsRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson56de76c1EncodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v IDsRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson56de76c1EncodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *IDsRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson56de76c1DecodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *IDsRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson56de76c1DecodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp6(l, v)
}
func easyjson56de76c1DecodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp7(in *jlexer.Lexer, out *GetMyEmailsResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "emails":
			if in.IsNull() {
				in.Skip()
				out.Emails = nil
			} else {
				in.Delim('[')
				if out.Emails == nil {
					if !in.IsDelim(']') {
						out.Emails = make([]MyEmailResponse, 0, 0)
					} else {
						out.Emails = []MyEmailResponse{}
					}
				} else {
					out.Emails = (out.Emails)[:0]
				}
				for !in.IsDelim(']') {
					var v16 MyEmailResponse
					if in.IsNull() {
						in.Skip()
					} else {
						(v16).UnmarshalEasyJSON(in)
					}
					out.Emails = append(out.Emails, v16)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "limit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Limit = int(in.Int())
			}
		case "offset":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Offset = int(in.Int())
			}
		case "total":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Total = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson56de76c1EncodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp7(out *jwriter.Writer, in GetMyEmailsResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"emails\":"
		out.RawString(prefix[1:])
		if in.Emails == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v17, v18 := range in.Emails {
				if v17 > 0 {
					out.RawByte(',')
				}
				(v18).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix)
		out.Int(int(in.Limit))
	}
	{
		const prefix string = ",\"offset\":"
		out.RawString(prefix)
		out.Int(int(in.Offset))
	}
	{
		const prefix string = ",\"total\":"
		out.RawString(prefix)
		out.Int(int(in.Total))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetMyEmailsResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson56de76c1EncodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetMyEmailsResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson56de76c1EncodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetMyEmailsResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson56de76c1DecodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetMyEmailsResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson56de76c1DecodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp7(l, v)
}
func easyjson56de76c1DecodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp8(in *jlexer.Lexer, out *GetEmailsResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "emails":
			if in.IsNull() {
				in.Skip()
				out.Emails = nil
			} else {
				in.Delim('[')
				if out.Emails == nil {
					if !in.IsDelim(']') {
						out.Emails = make([]EmailResponse, 0, 0)
					} else {
						out.Emails = []EmailResponse{}
					}
				} else {
					out.Emails = (out.Emails)[:0]
				}
				for !in.IsDelim(']') {
					var v19 EmailResponse
					if in.IsNull() {
						in.Skip()
					} else {
						(v19).UnmarshalEasyJSON(in)
					}
					out.Emails = append(out.Emails, v19)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "limit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Limit = int(in.Int())
			}
		case "offset":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Offset = int(in.Int())
			}
		case "total":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Total = int(in.Int())
			}
		case "unread_count":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UnreadCount = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson56de76c1EncodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp8(out *jwriter.Writer, in GetEmailsResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"emails\":"
		out.RawString(prefix[1:])
		if in.Emails == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v20, v21 := range in.Emails {
				if v20 > 0 {
					out.RawByte(',')
				}
				(v21).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix)
		out.Int(int(in.Limit))
	}
	{
		const prefix string = ",\"offset\":"
		out.RawString(prefix)
		out.Int(int(in.Offset))
	}
	{
		const prefix string = ",\"total\":"
		out.RawString(prefix)
		out.Int(int(in.Total))
	}
	{
		const prefix string = ",\"unread_count\":"
		out.RawString(prefix)
		out.Int(int(in.UnreadCount))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetEmailsResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson56de76c1EncodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp8(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetEmailsResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson56de76c1EncodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp8(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetEmailsResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson56de76c1DecodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp8(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetEmailsResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson56de76c1DecodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp8(l, v)
}
func easyjson56de76c1DecodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp9(in *jlexer.Lexer, out *GetEmailResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int64(in.Int64())
			}
		case "sender_email":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SenderEmail = string(in.String())
			}
		case "sender_name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SenderName = string(in.String())
			}
		case "sender_surname":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SenderSurname = string(in.String())
			}
		case "header":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Header = string(in.String())
			}
		case "body":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Body = string(in.String())
			}
		case "created_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.CreatedAt).UnmarshalJSON(data))
				}
			}
		case "sender_image_path":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SenderImagePath = string(in.String())
			}
		case "receiver_list":
			if in.IsNull() {
				in.Skip()
				out.ReceiverList = nil
			} else {
				in.Delim('[')
				if out.ReceiverList == nil {
					if !in.IsDelim(']') {
						out.ReceiverList = make([]string, 0, 4)
					} else {
						out.ReceiverList = []string{}
					}
				} else {
					out.ReceiverList = (out.ReceiverList)[:0]
				}
				for !in.IsDelim(']') {
					var v22 string
					if in.IsNull() {
						in.Skip()
					} else {
						v22 = string(in.String())
					}
					out.ReceiverList = append(out.ReceiverList, v22)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "is_anonymous":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsAnonymous = bool(in.Bool())
			}
		case "parent_email_id":
			if in.IsNull() {
				in.Skip()
				out.ParentEmailID = nil
			} else {
				if out.ParentEmailID == nil {
					out.ParentEmailID = new(int64)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.ParentEmailID = int64(in.Int64())
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson56de76c1EncodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp9(out *jwriter.Writer, in GetEmailResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"sender_email\":"
		out.RawString(prefix)
		out.String(string(in.SenderEmail))
	}
	{
		const prefix string = ",\"sender_name\":"
		out.RawString(prefix)
		out.String(string(in.SenderName))
	}
	{
		const prefix string = ",\"sender_surname\":"
		out.RawString(prefix)
		out.String(string(in.SenderSurname))
	}
	{
		const prefix string = ",\"header\":"
		out.RawString(prefix)
		out.String(string(in.Header))
	}
	{
		const prefix string = ",\"body\":"
		out.RawString(prefix)
		out.String(string(in.Body))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"sender_image_path\":"
		out.RawString(prefix)
		out.String(string(in.SenderImagePath))
	}
	{
		const prefix string = ",\"receiver_list\":"
		out.RawString(prefix)
		if in.ReceiverList == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v23, v24 := range in.ReceiverList {
				if v23 > 0 {
					out.RawByte(',')
				}
				out.String(string(v24))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"is_anonymous\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsAnonymous))
	}
	if in.ParentEmailID != nil {
		const prefix string = ",\"parent_email_id\":"
		out.RawString(prefix)
		out.Int64(int64(*in.ParentEmailID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetEmailResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson56de76c1EncodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp9(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetEmailResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson56de76c1EncodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp9(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetEmailResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson56de76c1DecodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp9(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetEmailResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson56de76c1DecodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp9(l, v)
}
func easyjson56de76c1DecodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp10(in *jlexer.Lexer, out *GetDraftsResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "drafts":
			if in.IsNull() {
				in.Skip()
				out.Drafts = nil
			} else {
				in.Delim('[')
				if out.Drafts == nil {
					if !in.IsDelim(']') {
						out.Drafts = make([]DraftResponse, 0, 0)
					} else {
						out.Drafts = []DraftResponse{}
					}
				} else {
					out.Drafts = (out.Drafts)[:0]
				}
				for !in.IsDelim(']') {
					var v25 DraftResponse
					if in.IsNull() {
						in.Skip()
					} else {
						(v25).UnmarshalEasyJSON(in)
					}
					out.Drafts = append(out.Drafts, v25)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "limit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Limit = int(in.Int())
			}
		case "offset":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Offset = int(in.Int())
			}
		case "total":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Total = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson56de76c1EncodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp10(out *jwriter.Writer, in GetDraftsResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"drafts\":"
		out.RawString(prefix[1:])
		if in.Drafts == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v26, v27 := range in.Drafts {
				if v26 > 0 {
					out.RawByte(',')
				}
				(v27).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix)
		out.Int(int(in.Limit))
	}
	{
		const prefix string = ",\"offset\":"
		out.RawString(prefix)
		out.Int(int(in.Offset))
	}
	{
		const prefix string = ",\"total\":"
		out.RawString(prefix)
		out.Int(int(in.Total))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetDraftsResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson56de76c1EncodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp10(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetDraftsResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson56de76c1EncodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp10(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetDraftsResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson56de76c1DecodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp10(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetDraftsResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson56de76c1DecodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp10(l, v)
}
func easyjson56de76c1DecodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp11(in *jlexer.Lexer, out *GetAttachmentsResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "attachments":
			if in.IsNull() {
				in.Skip()
				out.Attachments = nil
			} else {
				in.Delim('[')
				if out.Attachments == nil {
					if !in.IsDelim(']') {
						out.Attachments = make([]AttachmentResponse, 0, 0)
					} else {
						out.Attachments = []AttachmentResponse{}
					}
				} else {
					out.Attachments = (out.Attachments)[:0]
				}
				for !in.IsDelim(']') {
					var v28 AttachmentResponse
					if in.IsNull() {
						in.Skip()
					} else {
						(v28).UnmarshalEasyJSON(in)
					}
					out.Attachments = append(out.Attachments, v28)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson56de76c1EncodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp11(out *jwriter.Writer, in GetAttachmentsResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"attachments\":"
		out.RawString(prefix[1:])
		if in.Attachments == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v29, v30 := range in.Attachments {
				if v29 > 0 {
					out.RawByte(',')
				}
				(v30).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetAttachmentsResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson56de76c1EncodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp11(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetAttachmentsResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson56de76c1EncodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp11(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetAttachmentsResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson56de76c1DecodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp11(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetAttachmentsResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson56de76c1DecodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp11(l, v)
}
func easyjson56de76c1DecodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp12(in *jlexer.Lexer, out *ForwardEmailRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "email_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.EmailID = int64(in.Int64())
			}
		case "receivers":
			if in.IsNull() {
				in.Skip()
				out.Receivers = nil
			} else {
				in.Delim('[')
				if out.Receivers == nil {
					if !in.IsDelim(']') {
						out.Receivers = make([]string, 0, 4)
					} else {
						out.Receivers = []string{}
					}
				} else {
					out.Receivers = (out.Receivers)[:0]
				}
				for !in.IsDelim(']') {
					var v31 string
					if in.IsNull() {
						in.Skip()
					} else {
						v31 = string(in.String())
					}
					out.Receivers = append(out.Receivers, v31)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson56de76c1EncodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp12(out *jwriter.Writer, in ForwardEmailRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"email_id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.EmailID))
	}
	{
		const prefix string = ",\"receivers\":"
		out.RawString(prefix)
		if in.Receivers == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v32, v33 := range in.Receivers {
				if v32 > 0 {
					out.RawByte(',')
				}
				out.String(string(v33))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ForwardEmailRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson56de76c1EncodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp12(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ForwardEmailRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson56de76c1EncodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp12(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ForwardEmailRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson56de76c1DecodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp12(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ForwardEmailRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson56de76c1DecodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp12(l, v)
}
func easyjson56de76c1DecodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp13(in *jlexer.Lexer, out *EmailResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int64(in.Int64())
			}
		case "sender_email":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SenderEmail = string(in.String())
			}
		case "sender_name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SenderName = string(in.String())
			}
		case "sender_surname":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SenderSurname = string(in.String())
			}
		case "receiver_list":
			if in.IsNull() {
				in.Skip()
				out.ReceiverList = nil
			} else {
				in.Delim('[')
				if out.ReceiverList == nil {
					if !in.IsDelim(']') {
						out.ReceiverList = make([]string, 0, 4)
					} else {
						out.ReceiverList = []string{}
					}
				} else {
					out.ReceiverList = (out.ReceiverList)[:0]
				}
				for !in.IsDelim(']') {
					var v34 string
					if in.IsNull() {
						in.Skip()
					} else {
						v34 = string(in.String())
					}
					out.ReceiverList = append(out.ReceiverList, v34)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "header":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Header = string(in.String())
			}
		case "body":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Body = string(in.String())
			}
		case "created_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.CreatedAt).UnmarshalJSON(data))
				}
			}
		case "is_read":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsRead = bool(in.Bool())
			}
		case "is_starred":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsStarred = bool(in.Bool())
			}
		case "is_anonymous":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsAnonymous = bool(in.Bool())
			}
		case "parent_email_id":
			if in.IsNull() {
				in.Skip()
				out.ParentEmailID = nil
			} else {
				if out.ParentEmailID == nil {
					out.ParentEmailID = new(int64)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.ParentEmailID = int64(in.Int64())
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson56de76c1EncodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp13(out *jwriter.Writer, in EmailResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"sender_email\":"
		out.RawString(prefix)
		out.String(string(in.SenderEmail))
	}
	{
		const prefix string = ",\"sender_name\":"
		out.RawString(prefix)
		out.String(string(in.SenderName))
	}
	{
		const prefix string = ",\"sender_surname\":"
		out.RawString(prefix)
		out.String(string(in.SenderSurname))
	}
	{
		const prefix string = ",\"receiver_list\":"
		out.RawString(prefix)
		if in.ReceiverList == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v35, v36 := range in.ReceiverList {
				if v35 > 0 {
					out.RawByte(',')
				}
				out.String(string(v36))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"header\":"
		out.RawString(prefix)
		out.String(string(in.Header))
	}
	{
		const prefix string = ",\"body\":"
		out.RawString(prefix)
		out.String(string(in.Body))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"is_read\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsRead))
	}
	{
		const prefix string = ",\"is_starred\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsStarred))
	}
	{
		const prefix string = ",\"is_anonymous\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsAnonymous))
	}
	if in.ParentEmailID != nil {
		const prefix string = ",\"parent_email_id\":"
		out.RawString(prefix)
		out.Int64(int64(*in.ParentEmailID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v EmailResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson56de76c1EncodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp13(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v EmailResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson56de76c1EncodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp13(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *EmailResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson56de76c1DecodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp13(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *EmailResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson56de76c1DecodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp13(l, v)
}
func easyjson56de76c1DecodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp14(in *jlexer.Lexer, out *DraftResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int64(in.Int64())
			}
		case "sender_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SenderID = int64(in.Int64())
			}
		case "header":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Header = string(in.String())
			}
		case "body":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Body = string(in.String())
			}
		case "receivers":
			if in.IsNull() {
				in.Skip()
				out.Receivers = nil
			} else {
				in.Delim('[')
				if out.Receivers == nil {
					if !in.IsDelim(']') {
						out.Receivers = make([]string, 0, 4)
					} else {
						out.Receivers = []string{}
					}
				} else {
					out.Receivers = (out.Receivers)[:0]
				}
				for !in.IsDelim(']') {
					var v37 string
					if in.IsNull() {
						in.Skip()
					} else {
						v37 = string(in.String())
					}
					out.Receivers = append(out.Receivers, v37)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "is_anonymous":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsAnonymous = bool(in.Bool())
			}
		case "created_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.CreatedAt).UnmarshalJSON(data))
				}
			}
		case "updated_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.UpdatedAt).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson56de76c1EncodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp14(out *jwriter.Writer, in DraftResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"sender_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.SenderID))
	}
	{
		const prefix string = ",\"header\":"
		out.RawString(prefix)
		out.String(string(in.Header))
	}
	{
		const prefix string = ",\"body\":"
		out.RawString(prefix)
		out.String(string(in.Body))
	}
	{
		const prefix string = ",\"receivers\":"
		out.RawString(prefix)
		if in.Receivers == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v38, v39 := range in.Receivers {
				if v38 > 0 {
					out.RawByte(',')
				}
				out.String(string(v39))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"is_anonymous\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsAnonymous))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"updated_at\":"
		out.RawString(prefix)
		out.Raw((in.UpdatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v DraftResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson56de76c1EncodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp14(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v DraftResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson56de76c1EncodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp14(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *DraftResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson56de76c1DecodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp14(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *DraftResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson56de76c1DecodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp14(l, v)
}
func easyjson56de76c1DecodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp15(in *jlexer.Lexer, out *CreateDraftRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "header":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Header = string(in.String())
			}
		case "body":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Body = string(in.String())
			}
		case "receivers":
			if in.IsNull() {
				in.Skip()
				out.Receivers = nil
			} else {
				in.Delim('[')
				if out.Receivers == nil {
					if !in.IsDelim(']') {
						out.Receivers = make([]string, 0, 4)
					} else {
						out.Receivers = []string{}
					}
				} else {
					out.Receivers = (out.Receivers)[:0]
				}
				for !in.IsDelim(']') {
					var v40 string
					if in.IsNull() {
						in.Skip()
					} else {
						v40 = string(in.String())
					}
					out.Receivers = append(out.Receivers, v40)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "is_anonymous":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsAnonymous = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson56de76c1EncodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp15(out *jwriter.Writer, in CreateDraftRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"header\":"
		out.RawString(prefix[1:])
		out.String(string(in.Header))
	}
	{
		const prefix string = ",\"body\":"
		out.RawString(prefix)
		out.String(string(in.Body))
	}
	{
		const prefix string = ",\"receivers\":"
		out.RawString(prefix)
		if in.Receivers == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v41, v42 := range in.Receivers {
				if v41 > 0 {
					out.RawByte(',')
				}
				out.String(string(v42))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"is_anonymous\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsAnonymous))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateDraftRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson56de76c1EncodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp15(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateDraftRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson56de76c1EncodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp15(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateDraftRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson56de76c1DecodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp15(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateDraftRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson56de76c1DecodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp15(l, v)
}
func easyjson56de76c1DecodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp16(in *jlexer.Lexer, out *AttachmentResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int64(in.Int64())
			}
		case "email_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.EmailID = int64(in.Int64())
			}
		case "file_name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FileName = string(in.String())
			}
		case "content_type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ContentType = string(in.String())
			}
		case "size_bytes":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SizeBytes = int64(in.Int64())
			}
		case "created_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.CreatedAt).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson56de76c1EncodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp16(out *jwriter.Writer, in AttachmentResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"email_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.EmailID))
	}
	{
		const prefix string = ",\"file_name\":"
		out.RawString(prefix)
		out.String(string(in.FileName))
	}
	{
		const prefix string = ",\"content_type\":"
		out.RawString(prefix)
		out.String(string(in.ContentType))
	}
	{
		const prefix string = ",\"size_bytes\":"
		out.RawString(prefix)
		out.Int64(int64(in.SizeBytes))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AttachmentResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson56de76c1EncodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp16(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AttachmentResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson56de76c1EncodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp16(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AttachmentResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson56de76c1DecodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp16(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AttachmentResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson56de76c1DecodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp16(l, v)
}
func easyjson56de76c1DecodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp17(in *jlexer.Lexer, out *AnonymousRejectedResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "error":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Error = string(in.String())
			}
		case "rejected_emails":
			if in.IsNull() {
				in.Skip()
				out.RejectedEmails = nil
			} else {
				in.Delim('[')
				if out.RejectedEmails == nil {
					if !in.IsDelim(']') {
						out.RejectedEmails = make([]string, 0, 4)
					} else {
						out.RejectedEmails = []string{}
					}
				} else {
					out.RejectedEmails = (out.RejectedEmails)[:0]
				}
				for !in.IsDelim(']') {
					var v43 string
					if in.IsNull() {
						in.Skip()
					} else {
						v43 = string(in.String())
					}
					out.RejectedEmails = append(out.RejectedEmails, v43)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "draft_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DraftID = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson56de76c1EncodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp17(out *jwriter.Writer, in AnonymousRejectedResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"error\":"
		out.RawString(prefix[1:])
		out.String(string(in.Error))
	}
	{
		const prefix string = ",\"rejected_emails\":"
		out.RawString(prefix)
		if in.RejectedEmails == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v44, v45 := range in.RejectedEmails {
				if v44 > 0 {
					out.RawByte(',')
				}
				out.String(string(v45))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"draft_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.DraftID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AnonymousRejectedResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson56de76c1EncodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp17(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AnonymousRejectedResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson56de76c1EncodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp17(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AnonymousRejectedResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson56de76c1DecodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp17(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AnonymousRejectedResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson56de76c1DecodeGithubComGoParkMailRu20261PushToMainMicroservicesEmailDeliveryHttp17(l, v)
}
