# dev config
port: 8080

jwt:
  secret: super-secret-key
  expire_hours: 24

cors:
  allowed_origins:
    - http://e-smail.ru
    - https://e-smail.ru
  allowed_methods:
    - POST
    - GET
    - OPTIONS
    - PUT
    - DELETE
  allowed_headers:
    - Content-Type
    - Authorization

logger:
  level: debug
  environment: development
  output_path: stdout
  error_output_path: stderr

postgres:
  host: postgres
  port: 5432
  user: postgres
  password: postgres
  dbname: pushtomain
  sslmode: disable
  migrations_path: "file://db/migrations"

minio:
  endpoint: "http://minio:9000"
  region: "us-east-1"
  sslmode: false
  access_key: ""
  secret_key: ""
