// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2026_1_PushToMain/internal/app/email/service (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=../../../../mocks/app/email/mock_email_repository.go -package=mocks github.com/go-park-mail-ru/2026_1_PushToMain/internal/app/email/service Repository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	models "github.com/go-park-mail-ru/2026_1_PushToMain/internal/app/email/models"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// AddEmailReceivers mocks base method.
func (m *MockRepository) AddEmailReceivers(ctx context.Context, emailID int64, receiverIDs []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddEmailReceivers", ctx, emailID, receiverIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddEmailReceivers indicates an expected call of AddEmailReceivers.
func (mr *MockRepositoryMockRecorder) AddEmailReceivers(ctx, emailID, receiverIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddEmailReceivers", reflect.TypeOf((*MockRepository)(nil).AddEmailReceivers), ctx, emailID, receiverIDs)
}

// AddEmailReceiversWithTx mocks base method.
func (m *MockRepository) AddEmailReceiversWithTx(ctx context.Context, tx *sql.Tx, emailID int64, receiverIDs []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddEmailReceiversWithTx", ctx, tx, emailID, receiverIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddEmailReceiversWithTx indicates an expected call of AddEmailReceiversWithTx.
func (mr *MockRepositoryMockRecorder) AddEmailReceiversWithTx(ctx, tx, emailID, receiverIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddEmailReceiversWithTx", reflect.TypeOf((*MockRepository)(nil).AddEmailReceiversWithTx), ctx, tx, emailID, receiverIDs)
}

// BeginTx mocks base method.
func (m *MockRepository) BeginTx(ctx context.Context) (*sql.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTx", ctx)
	ret0, _ := ret[0].(*sql.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTx indicates an expected call of BeginTx.
func (mr *MockRepositoryMockRecorder) BeginTx(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTx", reflect.TypeOf((*MockRepository)(nil).BeginTx), ctx)
}

// CheckEmailAccess mocks base method.
func (m *MockRepository) CheckEmailAccess(ctx context.Context, emailID, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckEmailAccess", ctx, emailID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckEmailAccess indicates an expected call of CheckEmailAccess.
func (mr *MockRepositoryMockRecorder) CheckEmailAccess(ctx, emailID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckEmailAccess", reflect.TypeOf((*MockRepository)(nil).CheckEmailAccess), ctx, emailID, userID)
}

// CheckUserEmailExists mocks base method.
func (m *MockRepository) CheckUserEmailExists(ctx context.Context, emailID, userID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckUserEmailExists", ctx, emailID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckUserEmailExists indicates an expected call of CheckUserEmailExists.
func (mr *MockRepositoryMockRecorder) CheckUserEmailExists(ctx, emailID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckUserEmailExists", reflect.TypeOf((*MockRepository)(nil).CheckUserEmailExists), ctx, emailID, userID)
}

// DeleteEmailForReceiver mocks base method.
func (m *MockRepository) DeleteEmailForReceiver(ctx context.Context, emailID, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEmailForReceiver", ctx, emailID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEmailForReceiver indicates an expected call of DeleteEmailForReceiver.
func (mr *MockRepositoryMockRecorder) DeleteEmailForReceiver(ctx, emailID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEmailForReceiver", reflect.TypeOf((*MockRepository)(nil).DeleteEmailForReceiver), ctx, emailID, userID)
}

// DeleteEmailForSender mocks base method.
func (m *MockRepository) DeleteEmailForSender(ctx context.Context, emailID, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEmailForSender", ctx, emailID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEmailForSender indicates an expected call of DeleteEmailForSender.
func (mr *MockRepositoryMockRecorder) DeleteEmailForSender(ctx, emailID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEmailForSender", reflect.TypeOf((*MockRepository)(nil).DeleteEmailForSender), ctx, emailID, userID)
}

// GetEmailByID mocks base method.
func (m *MockRepository) GetEmailByID(ctx context.Context, emailID int64) (*models.EmailWithAvatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmailByID", ctx, emailID)
	ret0, _ := ret[0].(*models.EmailWithAvatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmailByID indicates an expected call of GetEmailByID.
func (mr *MockRepositoryMockRecorder) GetEmailByID(ctx, emailID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmailByID", reflect.TypeOf((*MockRepository)(nil).GetEmailByID), ctx, emailID)
}

// GetEmailsByReceiver mocks base method.
func (m *MockRepository) GetEmailsByReceiver(ctx context.Context, userID int64, limit, offset int) ([]models.EmailWithMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmailsByReceiver", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]models.EmailWithMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmailsByReceiver indicates an expected call of GetEmailsByReceiver.
func (mr *MockRepositoryMockRecorder) GetEmailsByReceiver(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmailsByReceiver", reflect.TypeOf((*MockRepository)(nil).GetEmailsByReceiver), ctx, userID, limit, offset)
}

// GetEmailsBySender mocks base method.
func (m *MockRepository) GetEmailsBySender(ctx context.Context, userID int64, limit, offset int) ([]models.EmailWithMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmailsBySender", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]models.EmailWithMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmailsBySender indicates an expected call of GetEmailsBySender.
func (mr *MockRepositoryMockRecorder) GetEmailsBySender(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmailsBySender", reflect.TypeOf((*MockRepository)(nil).GetEmailsBySender), ctx, userID, limit, offset)
}

// GetEmailsCount mocks base method.
func (m *MockRepository) GetEmailsCount(ctx context.Context, userID int64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmailsCount", ctx, userID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmailsCount indicates an expected call of GetEmailsCount.
func (mr *MockRepositoryMockRecorder) GetEmailsCount(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmailsCount", reflect.TypeOf((*MockRepository)(nil).GetEmailsCount), ctx, userID)
}

// GetUnreadEmailsCount mocks base method.
func (m *MockRepository) GetUnreadEmailsCount(ctx context.Context, userID int64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUnreadEmailsCount", ctx, userID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUnreadEmailsCount indicates an expected call of GetUnreadEmailsCount.
func (mr *MockRepositoryMockRecorder) GetUnreadEmailsCount(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUnreadEmailsCount", reflect.TypeOf((*MockRepository)(nil).GetUnreadEmailsCount), ctx, userID)
}

// GetUserEmailsCount mocks base method.
func (m *MockRepository) GetUserEmailsCount(ctx context.Context, userID int64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserEmailsCount", ctx, userID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserEmailsCount indicates an expected call of GetUserEmailsCount.
func (mr *MockRepositoryMockRecorder) GetUserEmailsCount(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserEmailsCount", reflect.TypeOf((*MockRepository)(nil).GetUserEmailsCount), ctx, userID)
}

// GetUsersByEmails mocks base method.
func (m *MockRepository) GetUsersByEmails(ctx context.Context, emails []string) ([]*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersByEmails", ctx, emails)
	ret0, _ := ret[0].([]*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersByEmails indicates an expected call of GetUsersByEmails.
func (mr *MockRepositoryMockRecorder) GetUsersByEmails(ctx, emails any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersByEmails", reflect.TypeOf((*MockRepository)(nil).GetUsersByEmails), ctx, emails)
}

// MarkEmailAsRead mocks base method.
func (m *MockRepository) MarkEmailAsRead(ctx context.Context, emailID, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkEmailAsRead", ctx, emailID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkEmailAsRead indicates an expected call of MarkEmailAsRead.
func (mr *MockRepositoryMockRecorder) MarkEmailAsRead(ctx, emailID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkEmailAsRead", reflect.TypeOf((*MockRepository)(nil).MarkEmailAsRead), ctx, emailID, userID)
}

// MarkEmailAsUnRead mocks base method.
func (m *MockRepository) MarkEmailAsUnRead(ctx context.Context, emailID, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkEmailAsUnRead", ctx, emailID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkEmailAsUnRead indicates an expected call of MarkEmailAsUnRead.
func (mr *MockRepositoryMockRecorder) MarkEmailAsUnRead(ctx, emailID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkEmailAsUnRead", reflect.TypeOf((*MockRepository)(nil).MarkEmailAsUnRead), ctx, emailID, userID)
}

// SaveEmail mocks base method.
func (m *MockRepository) SaveEmail(ctx context.Context, email models.Email) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveEmail", ctx, email)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveEmail indicates an expected call of SaveEmail.
func (mr *MockRepositoryMockRecorder) SaveEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveEmail", reflect.TypeOf((*MockRepository)(nil).SaveEmail), ctx, email)
}

// SaveEmailWithTx mocks base method.
func (m *MockRepository) SaveEmailWithTx(ctx context.Context, tx *sql.Tx, email models.Email) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveEmailWithTx", ctx, tx, email)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveEmailWithTx indicates an expected call of SaveEmailWithTx.
func (mr *MockRepositoryMockRecorder) SaveEmailWithTx(ctx, tx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveEmailWithTx", reflect.TypeOf((*MockRepository)(nil).SaveEmailWithTx), ctx, tx, email)
}
