// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2026_1_PushToMain/microservices/email/service (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=../../../mocks/app/email/mock_email_repository.go -package=mocks github.com/go-park-mail-ru/2026_1_PushToMain/microservices/email/service Repository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	models "github.com/go-park-mail-ru/2026_1_PushToMain/microservices/email/models"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// AddEmailUserWithTx mocks base method.
func (m *MockRepository) AddEmailUserWithTx(ctx context.Context, tx *sql.Tx, emailID, userID int64, isSender bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddEmailUserWithTx", ctx, tx, emailID, userID, isSender)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddEmailUserWithTx indicates an expected call of AddEmailUserWithTx.
func (mr *MockRepositoryMockRecorder) AddEmailUserWithTx(ctx, tx, emailID, userID, isSender any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddEmailUserWithTx", reflect.TypeOf((*MockRepository)(nil).AddEmailUserWithTx), ctx, tx, emailID, userID, isSender)
}

// BeginTx mocks base method.
func (m *MockRepository) BeginTx(ctx context.Context) (*sql.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTx", ctx)
	ret0, _ := ret[0].(*sql.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTx indicates an expected call of BeginTx.
func (mr *MockRepositoryMockRecorder) BeginTx(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTx", reflect.TypeOf((*MockRepository)(nil).BeginTx), ctx)
}

// CheckEmailAccess mocks base method.
func (m *MockRepository) CheckEmailAccess(ctx context.Context, emailID, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckEmailAccess", ctx, emailID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckEmailAccess indicates an expected call of CheckEmailAccess.
func (mr *MockRepositoryMockRecorder) CheckEmailAccess(ctx, emailID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckEmailAccess", reflect.TypeOf((*MockRepository)(nil).CheckEmailAccess), ctx, emailID, userID)
}

// CheckUserEmailExists mocks base method.
func (m *MockRepository) CheckUserEmailExists(ctx context.Context, emailID, userID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckUserEmailExists", ctx, emailID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckUserEmailExists indicates an expected call of CheckUserEmailExists.
func (mr *MockRepositoryMockRecorder) CheckUserEmailExists(ctx, emailID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckUserEmailExists", reflect.TypeOf((*MockRepository)(nil).CheckUserEmailExists), ctx, emailID, userID)
}

// CountDraftsByUser mocks base method.
func (m *MockRepository) CountDraftsByUser(ctx context.Context, userID int64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountDraftsByUser", ctx, userID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountDraftsByUser indicates an expected call of CountDraftsByUser.
func (mr *MockRepositoryMockRecorder) CountDraftsByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountDraftsByUser", reflect.TypeOf((*MockRepository)(nil).CountDraftsByUser), ctx, userID)
}

// CreateDraft mocks base method.
func (m *MockRepository) CreateDraft(ctx context.Context, draft models.Draft) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDraft", ctx, draft)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDraft indicates an expected call of CreateDraft.
func (mr *MockRepositoryMockRecorder) CreateDraft(ctx, draft any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDraft", reflect.TypeOf((*MockRepository)(nil).CreateDraft), ctx, draft)
}

// DeleteDraftsBatch mocks base method.
func (m *MockRepository) DeleteDraftsBatch(ctx context.Context, userID int64, draftIDs []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDraftsBatch", ctx, userID, draftIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDraftsBatch indicates an expected call of DeleteDraftsBatch.
func (mr *MockRepositoryMockRecorder) DeleteDraftsBatch(ctx, userID, draftIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDraftsBatch", reflect.TypeOf((*MockRepository)(nil).DeleteDraftsBatch), ctx, userID, draftIDs)
}

// GetDraftByID mocks base method.
func (m *MockRepository) GetDraftByID(ctx context.Context, draftID, userID int64) (*models.Draft, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDraftByID", ctx, draftID, userID)
	ret0, _ := ret[0].(*models.Draft)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDraftByID indicates an expected call of GetDraftByID.
func (mr *MockRepositoryMockRecorder) GetDraftByID(ctx, draftID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDraftByID", reflect.TypeOf((*MockRepository)(nil).GetDraftByID), ctx, draftID, userID)
}

// GetDrafts mocks base method.
func (m *MockRepository) GetDrafts(ctx context.Context, userID int64, limit, offset int) ([]models.Draft, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDrafts", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]models.Draft)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDrafts indicates an expected call of GetDrafts.
func (mr *MockRepositoryMockRecorder) GetDrafts(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDrafts", reflect.TypeOf((*MockRepository)(nil).GetDrafts), ctx, userID, limit, offset)
}

// GetEmailByID mocks base method.
func (m *MockRepository) GetEmailByID(ctx context.Context, emailID int64) (*models.EmailWithAvatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmailByID", ctx, emailID)
	ret0, _ := ret[0].(*models.EmailWithAvatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmailByID indicates an expected call of GetEmailByID.
func (mr *MockRepositoryMockRecorder) GetEmailByID(ctx, emailID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmailByID", reflect.TypeOf((*MockRepository)(nil).GetEmailByID), ctx, emailID)
}

// GetEmailsByIDs mocks base method.
func (m *MockRepository) GetEmailsByIDs(ctx context.Context, emailIDs []int64, userID int64) ([]models.EmailWithMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmailsByIDs", ctx, emailIDs, userID)
	ret0, _ := ret[0].([]models.EmailWithMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmailsByIDs indicates an expected call of GetEmailsByIDs.
func (mr *MockRepositoryMockRecorder) GetEmailsByIDs(ctx, emailIDs, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmailsByIDs", reflect.TypeOf((*MockRepository)(nil).GetEmailsByIDs), ctx, emailIDs, userID)
}

// GetEmailsByReceiver mocks base method.
func (m *MockRepository) GetEmailsByReceiver(ctx context.Context, userID int64, limit, offset int) ([]models.EmailWithMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmailsByReceiver", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]models.EmailWithMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmailsByReceiver indicates an expected call of GetEmailsByReceiver.
func (mr *MockRepositoryMockRecorder) GetEmailsByReceiver(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmailsByReceiver", reflect.TypeOf((*MockRepository)(nil).GetEmailsByReceiver), ctx, userID, limit, offset)
}

// GetEmailsBySender mocks base method.
func (m *MockRepository) GetEmailsBySender(ctx context.Context, userID int64, limit, offset int) ([]models.EmailWithMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmailsBySender", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]models.EmailWithMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmailsBySender indicates an expected call of GetEmailsBySender.
func (mr *MockRepositoryMockRecorder) GetEmailsBySender(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmailsBySender", reflect.TypeOf((*MockRepository)(nil).GetEmailsBySender), ctx, userID, limit, offset)
}

// GetEmailsCount mocks base method.
func (m *MockRepository) GetEmailsCount(ctx context.Context, userID int64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmailsCount", ctx, userID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmailsCount indicates an expected call of GetEmailsCount.
func (mr *MockRepositoryMockRecorder) GetEmailsCount(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmailsCount", reflect.TypeOf((*MockRepository)(nil).GetEmailsCount), ctx, userID)
}

// GetFavoriteEmails mocks base method.
func (m *MockRepository) GetFavoriteEmails(ctx context.Context, userID int64, limit, offset int) ([]models.EmailWithMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFavoriteEmails", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]models.EmailWithMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFavoriteEmails indicates an expected call of GetFavoriteEmails.
func (mr *MockRepositoryMockRecorder) GetFavoriteEmails(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFavoriteEmails", reflect.TypeOf((*MockRepository)(nil).GetFavoriteEmails), ctx, userID, limit, offset)
}

// GetSenderEmailsCount mocks base method.
func (m *MockRepository) GetSenderEmailsCount(ctx context.Context, userID int64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSenderEmailsCount", ctx, userID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSenderEmailsCount indicates an expected call of GetSenderEmailsCount.
func (mr *MockRepositoryMockRecorder) GetSenderEmailsCount(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSenderEmailsCount", reflect.TypeOf((*MockRepository)(nil).GetSenderEmailsCount), ctx, userID)
}

// GetSpamEmails mocks base method.
func (m *MockRepository) GetSpamEmails(ctx context.Context, userID int64, limit, offset int) ([]models.EmailWithMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSpamEmails", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]models.EmailWithMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSpamEmails indicates an expected call of GetSpamEmails.
func (mr *MockRepositoryMockRecorder) GetSpamEmails(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSpamEmails", reflect.TypeOf((*MockRepository)(nil).GetSpamEmails), ctx, userID, limit, offset)
}

// GetSpamEmailsCount mocks base method.
func (m *MockRepository) GetSpamEmailsCount(ctx context.Context, userID int64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSpamEmailsCount", ctx, userID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSpamEmailsCount indicates an expected call of GetSpamEmailsCount.
func (mr *MockRepositoryMockRecorder) GetSpamEmailsCount(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSpamEmailsCount", reflect.TypeOf((*MockRepository)(nil).GetSpamEmailsCount), ctx, userID)
}

// GetTrashEmails mocks base method.
func (m *MockRepository) GetTrashEmails(ctx context.Context, userID int64, limit, offset int) ([]models.EmailWithMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTrashEmails", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]models.EmailWithMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTrashEmails indicates an expected call of GetTrashEmails.
func (mr *MockRepositoryMockRecorder) GetTrashEmails(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTrashEmails", reflect.TypeOf((*MockRepository)(nil).GetTrashEmails), ctx, userID, limit, offset)
}

// GetTrashEmailsCount mocks base method.
func (m *MockRepository) GetTrashEmailsCount(ctx context.Context, userID int64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTrashEmailsCount", ctx, userID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTrashEmailsCount indicates an expected call of GetTrashEmailsCount.
func (mr *MockRepositoryMockRecorder) GetTrashEmailsCount(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTrashEmailsCount", reflect.TypeOf((*MockRepository)(nil).GetTrashEmailsCount), ctx, userID)
}

// GetUnreadEmailsCount mocks base method.
func (m *MockRepository) GetUnreadEmailsCount(ctx context.Context, userID int64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUnreadEmailsCount", ctx, userID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUnreadEmailsCount indicates an expected call of GetUnreadEmailsCount.
func (mr *MockRepositoryMockRecorder) GetUnreadEmailsCount(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUnreadEmailsCount", reflect.TypeOf((*MockRepository)(nil).GetUnreadEmailsCount), ctx, userID)
}

// GetUnreadSpamCount mocks base method.
func (m *MockRepository) GetUnreadSpamCount(ctx context.Context, userID int64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUnreadSpamCount", ctx, userID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUnreadSpamCount indicates an expected call of GetUnreadSpamCount.
func (mr *MockRepositoryMockRecorder) GetUnreadSpamCount(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUnreadSpamCount", reflect.TypeOf((*MockRepository)(nil).GetUnreadSpamCount), ctx, userID)
}

// GetUnreadTrashCount mocks base method.
func (m *MockRepository) GetUnreadTrashCount(ctx context.Context, userID int64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUnreadTrashCount", ctx, userID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUnreadTrashCount indicates an expected call of GetUnreadTrashCount.
func (mr *MockRepositoryMockRecorder) GetUnreadTrashCount(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUnreadTrashCount", reflect.TypeOf((*MockRepository)(nil).GetUnreadTrashCount), ctx, userID)
}

// GetUserEmailFlags mocks base method.
func (m *MockRepository) GetUserEmailFlags(ctx context.Context, emailID, userID int64, isSender bool) (*models.UserEmail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserEmailFlags", ctx, emailID, userID, isSender)
	ret0, _ := ret[0].(*models.UserEmail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserEmailFlags indicates an expected call of GetUserEmailFlags.
func (mr *MockRepositoryMockRecorder) GetUserEmailFlags(ctx, emailID, userID, isSender any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserEmailFlags", reflect.TypeOf((*MockRepository)(nil).GetUserEmailFlags), ctx, emailID, userID, isSender)
}

// GetUsersByEmails mocks base method.
func (m *MockRepository) GetUsersByEmails(ctx context.Context, emails []string) ([]*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersByEmails", ctx, emails)
	ret0, _ := ret[0].([]*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersByEmails indicates an expected call of GetUsersByEmails.
func (mr *MockRepositoryMockRecorder) GetUsersByEmails(ctx, emails any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersByEmails", reflect.TypeOf((*MockRepository)(nil).GetUsersByEmails), ctx, emails)
}

// HardDeleteBatch mocks base method.
func (m *MockRepository) HardDeleteBatch(ctx context.Context, userID int64, emailIDs []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HardDeleteBatch", ctx, userID, emailIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// HardDeleteBatch indicates an expected call of HardDeleteBatch.
func (mr *MockRepositoryMockRecorder) HardDeleteBatch(ctx, userID, emailIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HardDeleteBatch", reflect.TypeOf((*MockRepository)(nil).HardDeleteBatch), ctx, userID, emailIDs)
}

// MarkDraftAsSentTx mocks base method.
func (m *MockRepository) MarkDraftAsSentTx(ctx context.Context, tx *sql.Tx, draftID, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkDraftAsSentTx", ctx, tx, draftID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkDraftAsSentTx indicates an expected call of MarkDraftAsSentTx.
func (mr *MockRepositoryMockRecorder) MarkDraftAsSentTx(ctx, tx, draftID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkDraftAsSentTx", reflect.TypeOf((*MockRepository)(nil).MarkDraftAsSentTx), ctx, tx, draftID, userID)
}

// MarkEmailAsRead mocks base method.
func (m *MockRepository) MarkEmailAsRead(ctx context.Context, emailID, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkEmailAsRead", ctx, emailID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkEmailAsRead indicates an expected call of MarkEmailAsRead.
func (mr *MockRepositoryMockRecorder) MarkEmailAsRead(ctx, emailID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkEmailAsRead", reflect.TypeOf((*MockRepository)(nil).MarkEmailAsRead), ctx, emailID, userID)
}

// MarkEmailAsUnRead mocks base method.
func (m *MockRepository) MarkEmailAsUnRead(ctx context.Context, emailID, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkEmailAsUnRead", ctx, emailID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkEmailAsUnRead indicates an expected call of MarkEmailAsUnRead.
func (mr *MockRepositoryMockRecorder) MarkEmailAsUnRead(ctx, emailID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkEmailAsUnRead", reflect.TypeOf((*MockRepository)(nil).MarkEmailAsUnRead), ctx, emailID, userID)
}

// MarkSendersAsSpamBatch mocks base method.
func (m *MockRepository) MarkSendersAsSpamBatch(ctx context.Context, userID int64, emailIDs []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkSendersAsSpamBatch", ctx, userID, emailIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkSendersAsSpamBatch indicates an expected call of MarkSendersAsSpamBatch.
func (mr *MockRepositoryMockRecorder) MarkSendersAsSpamBatch(ctx, userID, emailIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkSendersAsSpamBatch", reflect.TypeOf((*MockRepository)(nil).MarkSendersAsSpamBatch), ctx, userID, emailIDs)
}

// SaveEmail mocks base method.
func (m *MockRepository) SaveEmail(ctx context.Context, email models.Email) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveEmail", ctx, email)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveEmail indicates an expected call of SaveEmail.
func (mr *MockRepositoryMockRecorder) SaveEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveEmail", reflect.TypeOf((*MockRepository)(nil).SaveEmail), ctx, email)
}

// SaveEmailWithTx mocks base method.
func (m *MockRepository) SaveEmailWithTx(ctx context.Context, tx *sql.Tx, email models.Email) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveEmailWithTx", ctx, tx, email)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveEmailWithTx indicates an expected call of SaveEmailWithTx.
func (mr *MockRepositoryMockRecorder) SaveEmailWithTx(ctx, tx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveEmailWithTx", reflect.TypeOf((*MockRepository)(nil).SaveEmailWithTx), ctx, tx, email)
}

// SetSpamBatch mocks base method.
func (m *MockRepository) SetSpamBatch(ctx context.Context, userID int64, emailIDs []int64, spam bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSpamBatch", ctx, userID, emailIDs, spam)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetSpamBatch indicates an expected call of SetSpamBatch.
func (mr *MockRepositoryMockRecorder) SetSpamBatch(ctx, userID, emailIDs, spam any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSpamBatch", reflect.TypeOf((*MockRepository)(nil).SetSpamBatch), ctx, userID, emailIDs, spam)
}

// SetStarredBatch mocks base method.
func (m *MockRepository) SetStarredBatch(ctx context.Context, userID int64, emailIDs []int64, starred bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetStarredBatch", ctx, userID, emailIDs, starred)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetStarredBatch indicates an expected call of SetStarredBatch.
func (mr *MockRepositoryMockRecorder) SetStarredBatch(ctx, userID, emailIDs, starred any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStarredBatch", reflect.TypeOf((*MockRepository)(nil).SetStarredBatch), ctx, userID, emailIDs, starred)
}

// SetTrashedBatch mocks base method.
func (m *MockRepository) SetTrashedBatch(ctx context.Context, userID int64, emailIDs []int64, trashed bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetTrashedBatch", ctx, userID, emailIDs, trashed)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetTrashedBatch indicates an expected call of SetTrashedBatch.
func (mr *MockRepositoryMockRecorder) SetTrashedBatch(ctx, userID, emailIDs, trashed any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTrashedBatch", reflect.TypeOf((*MockRepository)(nil).SetTrashedBatch), ctx, userID, emailIDs, trashed)
}

// UnmarkSendersAsSpamBatch mocks base method.
func (m *MockRepository) UnmarkSendersAsSpamBatch(ctx context.Context, userID int64, emailIDs []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnmarkSendersAsSpamBatch", ctx, userID, emailIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnmarkSendersAsSpamBatch indicates an expected call of UnmarkSendersAsSpamBatch.
func (mr *MockRepositoryMockRecorder) UnmarkSendersAsSpamBatch(ctx, userID, emailIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnmarkSendersAsSpamBatch", reflect.TypeOf((*MockRepository)(nil).UnmarkSendersAsSpamBatch), ctx, userID, emailIDs)
}

// UpdateDraft mocks base method.
func (m *MockRepository) UpdateDraft(ctx context.Context, draft models.Draft) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDraft", ctx, draft)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDraft indicates an expected call of UpdateDraft.
func (mr *MockRepositoryMockRecorder) UpdateDraft(ctx, draft any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDraft", reflect.TypeOf((*MockRepository)(nil).UpdateDraft), ctx, draft)
}
