// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2026_1_PushToMain/microservices/email/delivery/http (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -destination=../../../../mocks/app/email/mock_email_service.go -package=mocks github.com/go-park-mail-ru/2026_1_PushToMain/microservices/email/delivery/http Service
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	service "github.com/go-park-mail-ru/2026_1_PushToMain/microservices/email/service"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// CreateDraft mocks base method.
func (m *MockService) CreateDraft(ctx context.Context, cmd service.CreateDraftInput) (*service.DraftResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDraft", ctx, cmd)
	ret0, _ := ret[0].(*service.DraftResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDraft indicates an expected call of CreateDraft.
func (mr *MockServiceMockRecorder) CreateDraft(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDraft", reflect.TypeOf((*MockService)(nil).CreateDraft), ctx, cmd)
}

// Delete mocks base method.
func (m *MockService) Delete(ctx context.Context, cmd service.BatchInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockServiceMockRecorder) Delete(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockService)(nil).Delete), ctx, cmd)
}

// DeleteDrafts mocks base method.
func (m *MockService) DeleteDrafts(ctx context.Context, cmd service.DeleteDraftsInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDrafts", ctx, cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDrafts indicates an expected call of DeleteDrafts.
func (mr *MockServiceMockRecorder) DeleteDrafts(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDrafts", reflect.TypeOf((*MockService)(nil).DeleteDrafts), ctx, cmd)
}

// Favorite mocks base method.
func (m *MockService) Favorite(ctx context.Context, cmd service.BatchInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Favorite", ctx, cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// Favorite indicates an expected call of Favorite.
func (mr *MockServiceMockRecorder) Favorite(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Favorite", reflect.TypeOf((*MockService)(nil).Favorite), ctx, cmd)
}

// ForwardEmail mocks base method.
func (m *MockService) ForwardEmail(ctx context.Context, cmd service.ForwardEmailInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForwardEmail", ctx, cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// ForwardEmail indicates an expected call of ForwardEmail.
func (mr *MockServiceMockRecorder) ForwardEmail(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForwardEmail", reflect.TypeOf((*MockService)(nil).ForwardEmail), ctx, cmd)
}

// GetDraftByID mocks base method.
func (m *MockService) GetDraftByID(ctx context.Context, cmd service.GetDraftInput) (*service.DraftResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDraftByID", ctx, cmd)
	ret0, _ := ret[0].(*service.DraftResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDraftByID indicates an expected call of GetDraftByID.
func (mr *MockServiceMockRecorder) GetDraftByID(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDraftByID", reflect.TypeOf((*MockService)(nil).GetDraftByID), ctx, cmd)
}

// GetDrafts mocks base method.
func (m *MockService) GetDrafts(ctx context.Context, cmd service.GetDraftsInput) (*service.GetDraftsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDrafts", ctx, cmd)
	ret0, _ := ret[0].(*service.GetDraftsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDrafts indicates an expected call of GetDrafts.
func (mr *MockServiceMockRecorder) GetDrafts(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDrafts", reflect.TypeOf((*MockService)(nil).GetDrafts), ctx, cmd)
}

// GetEmailByID mocks base method.
func (m *MockService) GetEmailByID(ctx context.Context, cmd service.GetEmailInput) (*service.GetEmailResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmailByID", ctx, cmd)
	ret0, _ := ret[0].(*service.GetEmailResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmailByID indicates an expected call of GetEmailByID.
func (mr *MockServiceMockRecorder) GetEmailByID(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmailByID", reflect.TypeOf((*MockService)(nil).GetEmailByID), ctx, cmd)
}

// GetEmailsByReceiver mocks base method.
func (m *MockService) GetEmailsByReceiver(ctx context.Context, cmd service.GetEmailsInput) (*service.GetEmailsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmailsByReceiver", ctx, cmd)
	ret0, _ := ret[0].(*service.GetEmailsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmailsByReceiver indicates an expected call of GetEmailsByReceiver.
func (mr *MockServiceMockRecorder) GetEmailsByReceiver(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmailsByReceiver", reflect.TypeOf((*MockService)(nil).GetEmailsByReceiver), ctx, cmd)
}

// GetEmailsBySender mocks base method.
func (m *MockService) GetEmailsBySender(ctx context.Context, cmd service.GetMyEmailsInput) (*service.GetMyEmailsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmailsBySender", ctx, cmd)
	ret0, _ := ret[0].(*service.GetMyEmailsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmailsBySender indicates an expected call of GetEmailsBySender.
func (mr *MockServiceMockRecorder) GetEmailsBySender(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmailsBySender", reflect.TypeOf((*MockService)(nil).GetEmailsBySender), ctx, cmd)
}

// GetFavoriteEmails mocks base method.
func (m *MockService) GetFavoriteEmails(ctx context.Context, cmd service.GetEmailsInput) (*service.GetEmailsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFavoriteEmails", ctx, cmd)
	ret0, _ := ret[0].(*service.GetEmailsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFavoriteEmails indicates an expected call of GetFavoriteEmails.
func (mr *MockServiceMockRecorder) GetFavoriteEmails(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFavoriteEmails", reflect.TypeOf((*MockService)(nil).GetFavoriteEmails), ctx, cmd)
}

// GetSpamEmails mocks base method.
func (m *MockService) GetSpamEmails(ctx context.Context, cmd service.GetEmailsInput) (*service.GetEmailsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSpamEmails", ctx, cmd)
	ret0, _ := ret[0].(*service.GetEmailsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSpamEmails indicates an expected call of GetSpamEmails.
func (mr *MockServiceMockRecorder) GetSpamEmails(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSpamEmails", reflect.TypeOf((*MockService)(nil).GetSpamEmails), ctx, cmd)
}

// GetTrashEmails mocks base method.
func (m *MockService) GetTrashEmails(ctx context.Context, cmd service.GetEmailsInput) (*service.GetEmailsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTrashEmails", ctx, cmd)
	ret0, _ := ret[0].(*service.GetEmailsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTrashEmails indicates an expected call of GetTrashEmails.
func (mr *MockServiceMockRecorder) GetTrashEmails(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTrashEmails", reflect.TypeOf((*MockService)(nil).GetTrashEmails), ctx, cmd)
}

// MarkEmailAsRead mocks base method.
func (m *MockService) MarkEmailAsRead(ctx context.Context, cmd service.MarkAsReadInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkEmailAsRead", ctx, cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkEmailAsRead indicates an expected call of MarkEmailAsRead.
func (mr *MockServiceMockRecorder) MarkEmailAsRead(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkEmailAsRead", reflect.TypeOf((*MockService)(nil).MarkEmailAsRead), ctx, cmd)
}

// MarkEmailAsUnRead mocks base method.
func (m *MockService) MarkEmailAsUnRead(ctx context.Context, cmd service.MarkAsReadInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkEmailAsUnRead", ctx, cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkEmailAsUnRead indicates an expected call of MarkEmailAsUnRead.
func (mr *MockServiceMockRecorder) MarkEmailAsUnRead(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkEmailAsUnRead", reflect.TypeOf((*MockService)(nil).MarkEmailAsUnRead), ctx, cmd)
}

// SendDraft mocks base method.
func (m *MockService) SendDraft(ctx context.Context, cmd service.SendDraftInput) (*service.SendEmailResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendDraft", ctx, cmd)
	ret0, _ := ret[0].(*service.SendEmailResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendDraft indicates an expected call of SendDraft.
func (mr *MockServiceMockRecorder) SendDraft(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendDraft", reflect.TypeOf((*MockService)(nil).SendDraft), ctx, cmd)
}

// SendEmail mocks base method.
func (m *MockService) SendEmail(ctx context.Context, cmd service.SendEmailInput) (*service.SendEmailResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendEmail", ctx, cmd)
	ret0, _ := ret[0].(*service.SendEmailResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendEmail indicates an expected call of SendEmail.
func (mr *MockServiceMockRecorder) SendEmail(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendEmail", reflect.TypeOf((*MockService)(nil).SendEmail), ctx, cmd)
}

// Spam mocks base method.
func (m *MockService) Spam(ctx context.Context, cmd service.BatchInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Spam", ctx, cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// Spam indicates an expected call of Spam.
func (mr *MockServiceMockRecorder) Spam(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Spam", reflect.TypeOf((*MockService)(nil).Spam), ctx, cmd)
}

// Trash mocks base method.
func (m *MockService) Trash(ctx context.Context, cmd service.BatchInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Trash", ctx, cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// Trash indicates an expected call of Trash.
func (mr *MockServiceMockRecorder) Trash(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Trash", reflect.TypeOf((*MockService)(nil).Trash), ctx, cmd)
}

// Unfavorite mocks base method.
func (m *MockService) Unfavorite(ctx context.Context, cmd service.BatchInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unfavorite", ctx, cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unfavorite indicates an expected call of Unfavorite.
func (mr *MockServiceMockRecorder) Unfavorite(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unfavorite", reflect.TypeOf((*MockService)(nil).Unfavorite), ctx, cmd)
}

// UnmarkSpamSenders mocks base method.
func (m *MockService) UnmarkSpamSenders(ctx context.Context, cmd service.BatchInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnmarkSpamSenders", ctx, cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnmarkSpamSenders indicates an expected call of UnmarkSpamSenders.
func (mr *MockServiceMockRecorder) UnmarkSpamSenders(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnmarkSpamSenders", reflect.TypeOf((*MockService)(nil).UnmarkSpamSenders), ctx, cmd)
}

// Unspam mocks base method.
func (m *MockService) Unspam(ctx context.Context, cmd service.BatchInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unspam", ctx, cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unspam indicates an expected call of Unspam.
func (mr *MockServiceMockRecorder) Unspam(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unspam", reflect.TypeOf((*MockService)(nil).Unspam), ctx, cmd)
}

// Untrash mocks base method.
func (m *MockService) Untrash(ctx context.Context, cmd service.BatchInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Untrash", ctx, cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// Untrash indicates an expected call of Untrash.
func (mr *MockServiceMockRecorder) Untrash(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Untrash", reflect.TypeOf((*MockService)(nil).Untrash), ctx, cmd)
}

// UpdateDraft mocks base method.
func (m *MockService) UpdateDraft(ctx context.Context, cmd service.UpdateDraftInput) (*service.DraftResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDraft", ctx, cmd)
	ret0, _ := ret[0].(*service.DraftResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateDraft indicates an expected call of UpdateDraft.
func (mr *MockServiceMockRecorder) UpdateDraft(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDraft", reflect.TypeOf((*MockService)(nil).UpdateDraft), ctx, cmd)
}
