// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2026_1_PushToMain/microservices/email/delivery/http (interfaces: Service)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	service "github.com/go-park-mail-ru/2026_1_PushToMain/microservices/email/service"
	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// BlockSenders mocks base method.
func (m *MockService) BlockSenders(arg0 context.Context, arg1 service.BatchInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlockSenders", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// BlockSenders indicates an expected call of BlockSenders.
func (mr *MockServiceMockRecorder) BlockSenders(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlockSenders", reflect.TypeOf((*MockService)(nil).BlockSenders), arg0, arg1)
}

// CreateDraft mocks base method.
func (m *MockService) CreateDraft(arg0 context.Context, arg1 service.CreateDraftInput) (*service.DraftResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDraft", arg0, arg1)
	ret0, _ := ret[0].(*service.DraftResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDraft indicates an expected call of CreateDraft.
func (mr *MockServiceMockRecorder) CreateDraft(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDraft", reflect.TypeOf((*MockService)(nil).CreateDraft), arg0, arg1)
}

// Delete mocks base method.
func (m *MockService) Delete(arg0 context.Context, arg1 service.BatchInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockServiceMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockService)(nil).Delete), arg0, arg1)
}

// DeleteAttachments mocks base method.
func (m *MockService) DeleteAttachments(arg0 context.Context, arg1 service.DeleteAttachmentsInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAttachments", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAttachments indicates an expected call of DeleteAttachments.
func (mr *MockServiceMockRecorder) DeleteAttachments(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAttachments", reflect.TypeOf((*MockService)(nil).DeleteAttachments), arg0, arg1)
}

// DeleteDrafts mocks base method.
func (m *MockService) DeleteDrafts(arg0 context.Context, arg1 service.DeleteDraftsInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDrafts", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDrafts indicates an expected call of DeleteDrafts.
func (mr *MockServiceMockRecorder) DeleteDrafts(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDrafts", reflect.TypeOf((*MockService)(nil).DeleteDrafts), arg0, arg1)
}

// DownloadAttachment mocks base method.
func (m *MockService) DownloadAttachment(arg0 context.Context, arg1 service.DownloadAttachmentInput) (*service.DownloadAttachmentResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadAttachment", arg0, arg1)
	ret0, _ := ret[0].(*service.DownloadAttachmentResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DownloadAttachment indicates an expected call of DownloadAttachment.
func (mr *MockServiceMockRecorder) DownloadAttachment(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadAttachment", reflect.TypeOf((*MockService)(nil).DownloadAttachment), arg0, arg1)
}

// Favorite mocks base method.
func (m *MockService) Favorite(arg0 context.Context, arg1 service.BatchInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Favorite", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Favorite indicates an expected call of Favorite.
func (mr *MockServiceMockRecorder) Favorite(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Favorite", reflect.TypeOf((*MockService)(nil).Favorite), arg0, arg1)
}

// ForwardEmail mocks base method.
func (m *MockService) ForwardEmail(arg0 context.Context, arg1 service.ForwardEmailInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForwardEmail", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ForwardEmail indicates an expected call of ForwardEmail.
func (mr *MockServiceMockRecorder) ForwardEmail(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForwardEmail", reflect.TypeOf((*MockService)(nil).ForwardEmail), arg0, arg1)
}

// GetAllEmailsByUser mocks base method.
func (m *MockService) GetAllEmailsByUser(arg0 context.Context, arg1 service.GetEmailsInput) (*service.GetEmailsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllEmailsByUser", arg0, arg1)
	ret0, _ := ret[0].(*service.GetEmailsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllEmailsByUser indicates an expected call of GetAllEmailsByUser.
func (mr *MockServiceMockRecorder) GetAllEmailsByUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllEmailsByUser", reflect.TypeOf((*MockService)(nil).GetAllEmailsByUser), arg0, arg1)
}

// GetAttachments mocks base method.
func (m *MockService) GetAttachments(arg0 context.Context, arg1 service.GetAttachmentsInput) (*service.GetAttachmentsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAttachments", arg0, arg1)
	ret0, _ := ret[0].(*service.GetAttachmentsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAttachments indicates an expected call of GetAttachments.
func (mr *MockServiceMockRecorder) GetAttachments(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAttachments", reflect.TypeOf((*MockService)(nil).GetAttachments), arg0, arg1)
}

// GetDraftByID mocks base method.
func (m *MockService) GetDraftByID(arg0 context.Context, arg1 service.GetDraftInput) (*service.DraftResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDraftByID", arg0, arg1)
	ret0, _ := ret[0].(*service.DraftResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDraftByID indicates an expected call of GetDraftByID.
func (mr *MockServiceMockRecorder) GetDraftByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDraftByID", reflect.TypeOf((*MockService)(nil).GetDraftByID), arg0, arg1)
}

// GetDrafts mocks base method.
func (m *MockService) GetDrafts(arg0 context.Context, arg1 service.GetDraftsInput) (*service.GetDraftsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDrafts", arg0, arg1)
	ret0, _ := ret[0].(*service.GetDraftsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDrafts indicates an expected call of GetDrafts.
func (mr *MockServiceMockRecorder) GetDrafts(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDrafts", reflect.TypeOf((*MockService)(nil).GetDrafts), arg0, arg1)
}

// GetEmailByID mocks base method.
func (m *MockService) GetEmailByID(arg0 context.Context, arg1 service.GetEmailInput) (*service.GetEmailResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmailByID", arg0, arg1)
	ret0, _ := ret[0].(*service.GetEmailResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmailByID indicates an expected call of GetEmailByID.
func (mr *MockServiceMockRecorder) GetEmailByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmailByID", reflect.TypeOf((*MockService)(nil).GetEmailByID), arg0, arg1)
}

// GetEmailsByReceiver mocks base method.
func (m *MockService) GetEmailsByReceiver(arg0 context.Context, arg1 service.GetEmailsInput) (*service.GetEmailsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmailsByReceiver", arg0, arg1)
	ret0, _ := ret[0].(*service.GetEmailsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmailsByReceiver indicates an expected call of GetEmailsByReceiver.
func (mr *MockServiceMockRecorder) GetEmailsByReceiver(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmailsByReceiver", reflect.TypeOf((*MockService)(nil).GetEmailsByReceiver), arg0, arg1)
}

// GetEmailsBySender mocks base method.
func (m *MockService) GetEmailsBySender(arg0 context.Context, arg1 service.GetMyEmailsInput) (*service.GetMyEmailsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmailsBySender", arg0, arg1)
	ret0, _ := ret[0].(*service.GetMyEmailsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmailsBySender indicates an expected call of GetEmailsBySender.
func (mr *MockServiceMockRecorder) GetEmailsBySender(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmailsBySender", reflect.TypeOf((*MockService)(nil).GetEmailsBySender), arg0, arg1)
}

// GetFavoriteEmails mocks base method.
func (m *MockService) GetFavoriteEmails(arg0 context.Context, arg1 service.GetEmailsInput) (*service.GetEmailsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFavoriteEmails", arg0, arg1)
	ret0, _ := ret[0].(*service.GetEmailsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFavoriteEmails indicates an expected call of GetFavoriteEmails.
func (mr *MockServiceMockRecorder) GetFavoriteEmails(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFavoriteEmails", reflect.TypeOf((*MockService)(nil).GetFavoriteEmails), arg0, arg1)
}

// GetSpamEmails mocks base method.
func (m *MockService) GetSpamEmails(arg0 context.Context, arg1 service.GetEmailsInput) (*service.GetEmailsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSpamEmails", arg0, arg1)
	ret0, _ := ret[0].(*service.GetEmailsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSpamEmails indicates an expected call of GetSpamEmails.
func (mr *MockServiceMockRecorder) GetSpamEmails(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSpamEmails", reflect.TypeOf((*MockService)(nil).GetSpamEmails), arg0, arg1)
}

// GetTrashEmails mocks base method.
func (m *MockService) GetTrashEmails(arg0 context.Context, arg1 service.GetEmailsInput) (*service.GetEmailsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTrashEmails", arg0, arg1)
	ret0, _ := ret[0].(*service.GetEmailsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTrashEmails indicates an expected call of GetTrashEmails.
func (mr *MockServiceMockRecorder) GetTrashEmails(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTrashEmails", reflect.TypeOf((*MockService)(nil).GetTrashEmails), arg0, arg1)
}

// MarkEmailAsRead mocks base method.
func (m *MockService) MarkEmailAsRead(arg0 context.Context, arg1 service.MarkAsReadInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkEmailAsRead", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkEmailAsRead indicates an expected call of MarkEmailAsRead.
func (mr *MockServiceMockRecorder) MarkEmailAsRead(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkEmailAsRead", reflect.TypeOf((*MockService)(nil).MarkEmailAsRead), arg0, arg1)
}

// MarkEmailAsUnRead mocks base method.
func (m *MockService) MarkEmailAsUnRead(arg0 context.Context, arg1 service.MarkAsReadInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkEmailAsUnRead", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkEmailAsUnRead indicates an expected call of MarkEmailAsUnRead.
func (mr *MockServiceMockRecorder) MarkEmailAsUnRead(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkEmailAsUnRead", reflect.TypeOf((*MockService)(nil).MarkEmailAsUnRead), arg0, arg1)
}

// SendDraft mocks base method.
func (m *MockService) SendDraft(arg0 context.Context, arg1 service.SendDraftInput) (*service.SendEmailResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendDraft", arg0, arg1)
	ret0, _ := ret[0].(*service.SendEmailResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendDraft indicates an expected call of SendDraft.
func (mr *MockServiceMockRecorder) SendDraft(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendDraft", reflect.TypeOf((*MockService)(nil).SendDraft), arg0, arg1)
}

// SendEmail mocks base method.
func (m *MockService) SendEmail(arg0 context.Context, arg1 service.SendEmailInput) (*service.SendEmailResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendEmail", arg0, arg1)
	ret0, _ := ret[0].(*service.SendEmailResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendEmail indicates an expected call of SendEmail.
func (mr *MockServiceMockRecorder) SendEmail(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendEmail", reflect.TypeOf((*MockService)(nil).SendEmail), arg0, arg1)
}

// Spam mocks base method.
func (m *MockService) Spam(arg0 context.Context, arg1 service.BatchInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Spam", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Spam indicates an expected call of Spam.
func (mr *MockServiceMockRecorder) Spam(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Spam", reflect.TypeOf((*MockService)(nil).Spam), arg0, arg1)
}

// Trash mocks base method.
func (m *MockService) Trash(arg0 context.Context, arg1 service.BatchInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Trash", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Trash indicates an expected call of Trash.
func (mr *MockServiceMockRecorder) Trash(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Trash", reflect.TypeOf((*MockService)(nil).Trash), arg0, arg1)
}

// UnblockSenders mocks base method.
func (m *MockService) UnblockSenders(arg0 context.Context, arg1 service.BatchInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnblockSenders", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnblockSenders indicates an expected call of UnblockSenders.
func (mr *MockServiceMockRecorder) UnblockSenders(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnblockSenders", reflect.TypeOf((*MockService)(nil).UnblockSenders), arg0, arg1)
}

// Unfavorite mocks base method.
func (m *MockService) Unfavorite(arg0 context.Context, arg1 service.BatchInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unfavorite", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unfavorite indicates an expected call of Unfavorite.
func (mr *MockServiceMockRecorder) Unfavorite(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unfavorite", reflect.TypeOf((*MockService)(nil).Unfavorite), arg0, arg1)
}

// Unspam mocks base method.
func (m *MockService) Unspam(arg0 context.Context, arg1 service.BatchInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unspam", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unspam indicates an expected call of Unspam.
func (mr *MockServiceMockRecorder) Unspam(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unspam", reflect.TypeOf((*MockService)(nil).Unspam), arg0, arg1)
}

// Untrash mocks base method.
func (m *MockService) Untrash(arg0 context.Context, arg1 service.BatchInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Untrash", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Untrash indicates an expected call of Untrash.
func (mr *MockServiceMockRecorder) Untrash(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Untrash", reflect.TypeOf((*MockService)(nil).Untrash), arg0, arg1)
}

// UpdateDraft mocks base method.
func (m *MockService) UpdateDraft(arg0 context.Context, arg1 service.UpdateDraftInput) (*service.DraftResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDraft", arg0, arg1)
	ret0, _ := ret[0].(*service.DraftResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateDraft indicates an expected call of UpdateDraft.
func (mr *MockServiceMockRecorder) UpdateDraft(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDraft", reflect.TypeOf((*MockService)(nil).UpdateDraft), arg0, arg1)
}

// UploadAttachment mocks base method.
func (m *MockService) UploadAttachment(arg0 context.Context, arg1 service.UploadAttachmentInput) (*service.AttachmentResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadAttachment", arg0, arg1)
	ret0, _ := ret[0].(*service.AttachmentResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadAttachment indicates an expected call of UploadAttachment.
func (mr *MockServiceMockRecorder) UploadAttachment(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadAttachment", reflect.TypeOf((*MockService)(nil).UploadAttachment), arg0, arg1)
}
