// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2026_1_PushToMain/microservices/email/service (interfaces: Repository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	models "github.com/go-park-mail-ru/2026_1_PushToMain/microservices/email/models"
	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// BeginTx mocks base method.
func (m *MockRepository) BeginTx(arg0 context.Context) (*sql.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTx", arg0)
	ret0, _ := ret[0].(*sql.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTx indicates an expected call of BeginTx.
func (mr *MockRepositoryMockRecorder) BeginTx(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTx", reflect.TypeOf((*MockRepository)(nil).BeginTx), arg0)
}

// BlockSendersBatch mocks base method.
func (m *MockRepository) BlockSendersBatch(arg0 context.Context, arg1 int64, arg2 []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlockSendersBatch", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// BlockSendersBatch indicates an expected call of BlockSendersBatch.
func (mr *MockRepositoryMockRecorder) BlockSendersBatch(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlockSendersBatch", reflect.TypeOf((*MockRepository)(nil).BlockSendersBatch), arg0, arg1, arg2)
}

// CheckEmailAccess mocks base method.
func (m *MockRepository) CheckEmailAccess(arg0 context.Context, arg1, arg2 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckEmailAccess", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckEmailAccess indicates an expected call of CheckEmailAccess.
func (mr *MockRepositoryMockRecorder) CheckEmailAccess(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckEmailAccess", reflect.TypeOf((*MockRepository)(nil).CheckEmailAccess), arg0, arg1, arg2)
}

// CountDrafts mocks base method.
func (m *MockRepository) CountDrafts(arg0 context.Context, arg1 int64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountDrafts", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountDrafts indicates an expected call of CountDrafts.
func (mr *MockRepositoryMockRecorder) CountDrafts(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountDrafts", reflect.TypeOf((*MockRepository)(nil).CountDrafts), arg0, arg1)
}

// CountSentEmails mocks base method.
func (m *MockRepository) CountSentEmails(arg0 context.Context, arg1 int64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountSentEmails", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountSentEmails indicates an expected call of CountSentEmails.
func (mr *MockRepositoryMockRecorder) CountSentEmails(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountSentEmails", reflect.TypeOf((*MockRepository)(nil).CountSentEmails), arg0, arg1)
}

// CreateDraft mocks base method.
func (m *MockRepository) CreateDraft(arg0 context.Context, arg1 models.Draft) (*models.Draft, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDraft", arg0, arg1)
	ret0, _ := ret[0].(*models.Draft)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDraft indicates an expected call of CreateDraft.
func (mr *MockRepositoryMockRecorder) CreateDraft(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDraft", reflect.TypeOf((*MockRepository)(nil).CreateDraft), arg0, arg1)
}

// DeleteAttachments mocks base method.
func (m *MockRepository) DeleteAttachments(arg0 context.Context, arg1 *sql.Tx, arg2 []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAttachments", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAttachments indicates an expected call of DeleteAttachments.
func (mr *MockRepositoryMockRecorder) DeleteAttachments(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAttachments", reflect.TypeOf((*MockRepository)(nil).DeleteAttachments), arg0, arg1, arg2)
}

// DeleteDraftsBatch mocks base method.
func (m *MockRepository) DeleteDraftsBatch(arg0 context.Context, arg1 int64, arg2 []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDraftsBatch", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDraftsBatch indicates an expected call of DeleteDraftsBatch.
func (mr *MockRepositoryMockRecorder) DeleteDraftsBatch(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDraftsBatch", reflect.TypeOf((*MockRepository)(nil).DeleteDraftsBatch), arg0, arg1, arg2)
}

// DeleteUserEmailsBatch mocks base method.
func (m *MockRepository) DeleteUserEmailsBatch(arg0 context.Context, arg1 int64, arg2 []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserEmailsBatch", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserEmailsBatch indicates an expected call of DeleteUserEmailsBatch.
func (mr *MockRepositoryMockRecorder) DeleteUserEmailsBatch(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserEmailsBatch", reflect.TypeOf((*MockRepository)(nil).DeleteUserEmailsBatch), arg0, arg1, arg2)
}

// GetAllEmails mocks base method.
func (m *MockRepository) GetAllEmails(arg0 context.Context, arg1 int64, arg2, arg3 int) ([]models.EmailWithMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllEmails", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]models.EmailWithMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllEmails indicates an expected call of GetAllEmails.
func (mr *MockRepositoryMockRecorder) GetAllEmails(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllEmails", reflect.TypeOf((*MockRepository)(nil).GetAllEmails), arg0, arg1, arg2, arg3)
}

// GetAttachmentByID mocks base method.
func (m *MockRepository) GetAttachmentByID(arg0 context.Context, arg1, arg2 int64) (*models.Attachment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAttachmentByID", arg0, arg1, arg2)
	ret0, _ := ret[0].(*models.Attachment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAttachmentByID indicates an expected call of GetAttachmentByID.
func (mr *MockRepositoryMockRecorder) GetAttachmentByID(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAttachmentByID", reflect.TypeOf((*MockRepository)(nil).GetAttachmentByID), arg0, arg1, arg2)
}

// GetAttachmentsByEmailIDs mocks base method.
func (m *MockRepository) GetAttachmentsByEmailIDs(arg0 context.Context, arg1 []int64) ([]models.Attachment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAttachmentsByEmailIDs", arg0, arg1)
	ret0, _ := ret[0].([]models.Attachment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAttachmentsByEmailIDs indicates an expected call of GetAttachmentsByEmailIDs.
func (mr *MockRepositoryMockRecorder) GetAttachmentsByEmailIDs(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAttachmentsByEmailIDs", reflect.TypeOf((*MockRepository)(nil).GetAttachmentsByEmailIDs), arg0, arg1)
}

// GetDeletedEmailIDs mocks base method.
func (m *MockRepository) GetDeletedEmailIDs(arg0 context.Context, arg1 int64, arg2 []int64) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeletedEmailIDs", arg0, arg1, arg2)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeletedEmailIDs indicates an expected call of GetDeletedEmailIDs.
func (mr *MockRepositoryMockRecorder) GetDeletedEmailIDs(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeletedEmailIDs", reflect.TypeOf((*MockRepository)(nil).GetDeletedEmailIDs), arg0, arg1, arg2)
}

// GetDraftByID mocks base method.
func (m *MockRepository) GetDraftByID(arg0 context.Context, arg1, arg2 int64) (*models.Draft, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDraftByID", arg0, arg1, arg2)
	ret0, _ := ret[0].(*models.Draft)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDraftByID indicates an expected call of GetDraftByID.
func (mr *MockRepositoryMockRecorder) GetDraftByID(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDraftByID", reflect.TypeOf((*MockRepository)(nil).GetDraftByID), arg0, arg1, arg2)
}

// GetDrafts mocks base method.
func (m *MockRepository) GetDrafts(arg0 context.Context, arg1 int64, arg2, arg3 int) ([]models.Draft, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDrafts", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]models.Draft)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDrafts indicates an expected call of GetDrafts.
func (mr *MockRepositoryMockRecorder) GetDrafts(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDrafts", reflect.TypeOf((*MockRepository)(nil).GetDrafts), arg0, arg1, arg2, arg3)
}

// GetEmailByID mocks base method.
func (m *MockRepository) GetEmailByID(arg0 context.Context, arg1 int64) (*models.EmailWithAvatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmailByID", arg0, arg1)
	ret0, _ := ret[0].(*models.EmailWithAvatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmailByID indicates an expected call of GetEmailByID.
func (mr *MockRepositoryMockRecorder) GetEmailByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmailByID", reflect.TypeOf((*MockRepository)(nil).GetEmailByID), arg0, arg1)
}

// GetEmailIdsByUserEmailIds mocks base method.
func (m *MockRepository) GetEmailIdsByUserEmailIds(arg0 context.Context, arg1 []int64) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmailIdsByUserEmailIds", arg0, arg1)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmailIdsByUserEmailIds indicates an expected call of GetEmailIdsByUserEmailIds.
func (mr *MockRepositoryMockRecorder) GetEmailIdsByUserEmailIds(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmailIdsByUserEmailIds", reflect.TypeOf((*MockRepository)(nil).GetEmailIdsByUserEmailIds), arg0, arg1)
}

// GetFavoriteEmails mocks base method.
func (m *MockRepository) GetFavoriteEmails(arg0 context.Context, arg1 int64, arg2, arg3 int) ([]models.EmailWithMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFavoriteEmails", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]models.EmailWithMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFavoriteEmails indicates an expected call of GetFavoriteEmails.
func (mr *MockRepositoryMockRecorder) GetFavoriteEmails(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFavoriteEmails", reflect.TypeOf((*MockRepository)(nil).GetFavoriteEmails), arg0, arg1, arg2, arg3)
}

// GetFavoritesStats mocks base method.
func (m *MockRepository) GetFavoritesStats(arg0 context.Context, arg1 int64) (models.MailboxStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFavoritesStats", arg0, arg1)
	ret0, _ := ret[0].(models.MailboxStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFavoritesStats indicates an expected call of GetFavoritesStats.
func (mr *MockRepositoryMockRecorder) GetFavoritesStats(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFavoritesStats", reflect.TypeOf((*MockRepository)(nil).GetFavoritesStats), arg0, arg1)
}

// GetInboxEmails mocks base method.
func (m *MockRepository) GetInboxEmails(arg0 context.Context, arg1 int64, arg2, arg3 int) ([]models.EmailWithMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInboxEmails", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]models.EmailWithMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInboxEmails indicates an expected call of GetInboxEmails.
func (mr *MockRepositoryMockRecorder) GetInboxEmails(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInboxEmails", reflect.TypeOf((*MockRepository)(nil).GetInboxEmails), arg0, arg1, arg2, arg3)
}

// GetInboxStats mocks base method.
func (m *MockRepository) GetInboxStats(arg0 context.Context, arg1 int64) (models.MailboxStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInboxStats", arg0, arg1)
	ret0, _ := ret[0].(models.MailboxStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInboxStats indicates an expected call of GetInboxStats.
func (mr *MockRepositoryMockRecorder) GetInboxStats(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInboxStats", reflect.TypeOf((*MockRepository)(nil).GetInboxStats), arg0, arg1)
}

// GetReceivedStats mocks base method.
func (m *MockRepository) GetReceivedStats(arg0 context.Context, arg1 int64) (models.MailboxStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReceivedStats", arg0, arg1)
	ret0, _ := ret[0].(models.MailboxStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReceivedStats indicates an expected call of GetReceivedStats.
func (mr *MockRepositoryMockRecorder) GetReceivedStats(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReceivedStats", reflect.TypeOf((*MockRepository)(nil).GetReceivedStats), arg0, arg1)
}

// GetSentEmails mocks base method.
func (m *MockRepository) GetSentEmails(arg0 context.Context, arg1 int64, arg2, arg3 int) ([]models.EmailWithMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSentEmails", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]models.EmailWithMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSentEmails indicates an expected call of GetSentEmails.
func (mr *MockRepositoryMockRecorder) GetSentEmails(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSentEmails", reflect.TypeOf((*MockRepository)(nil).GetSentEmails), arg0, arg1, arg2, arg3)
}

// GetSpamEmailIDs mocks base method.
func (m *MockRepository) GetSpamEmailIDs(arg0 context.Context, arg1 int64, arg2 []int64) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSpamEmailIDs", arg0, arg1, arg2)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSpamEmailIDs indicates an expected call of GetSpamEmailIDs.
func (mr *MockRepositoryMockRecorder) GetSpamEmailIDs(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSpamEmailIDs", reflect.TypeOf((*MockRepository)(nil).GetSpamEmailIDs), arg0, arg1, arg2)
}

// GetSpamEmails mocks base method.
func (m *MockRepository) GetSpamEmails(arg0 context.Context, arg1 int64, arg2, arg3 int) ([]models.EmailWithMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSpamEmails", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]models.EmailWithMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSpamEmails indicates an expected call of GetSpamEmails.
func (mr *MockRepositoryMockRecorder) GetSpamEmails(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSpamEmails", reflect.TypeOf((*MockRepository)(nil).GetSpamEmails), arg0, arg1, arg2, arg3)
}

// GetSpamStats mocks base method.
func (m *MockRepository) GetSpamStats(arg0 context.Context, arg1 int64) (models.MailboxStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSpamStats", arg0, arg1)
	ret0, _ := ret[0].(models.MailboxStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSpamStats indicates an expected call of GetSpamStats.
func (mr *MockRepositoryMockRecorder) GetSpamStats(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSpamStats", reflect.TypeOf((*MockRepository)(nil).GetSpamStats), arg0, arg1)
}

// GetTrashEmails mocks base method.
func (m *MockRepository) GetTrashEmails(arg0 context.Context, arg1 int64, arg2, arg3 int) ([]models.EmailWithMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTrashEmails", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]models.EmailWithMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTrashEmails indicates an expected call of GetTrashEmails.
func (mr *MockRepositoryMockRecorder) GetTrashEmails(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTrashEmails", reflect.TypeOf((*MockRepository)(nil).GetTrashEmails), arg0, arg1, arg2, arg3)
}

// GetTrashStats mocks base method.
func (m *MockRepository) GetTrashStats(arg0 context.Context, arg1 int64) (models.MailboxStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTrashStats", arg0, arg1)
	ret0, _ := ret[0].(models.MailboxStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTrashStats indicates an expected call of GetTrashStats.
func (mr *MockRepositoryMockRecorder) GetTrashStats(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTrashStats", reflect.TypeOf((*MockRepository)(nil).GetTrashStats), arg0, arg1)
}

// GetUserEmailID mocks base method.
func (m *MockRepository) GetUserEmailID(arg0 context.Context, arg1, arg2 int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserEmailID", arg0, arg1, arg2)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserEmailID indicates an expected call of GetUserEmailID.
func (mr *MockRepositoryMockRecorder) GetUserEmailID(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserEmailID", reflect.TypeOf((*MockRepository)(nil).GetUserEmailID), arg0, arg1, arg2)
}

// InsertAttachment mocks base method.
func (m *MockRepository) InsertAttachment(arg0 context.Context, arg1 *sql.Tx, arg2 models.Attachment) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertAttachment", arg0, arg1, arg2)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertAttachment indicates an expected call of InsertAttachment.
func (mr *MockRepositoryMockRecorder) InsertAttachment(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertAttachment", reflect.TypeOf((*MockRepository)(nil).InsertAttachment), arg0, arg1, arg2)
}

// InsertEmail mocks base method.
func (m *MockRepository) InsertEmail(arg0 context.Context, arg1 *sql.Tx, arg2 models.Email) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertEmail", arg0, arg1, arg2)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertEmail indicates an expected call of InsertEmail.
func (mr *MockRepositoryMockRecorder) InsertEmail(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertEmail", reflect.TypeOf((*MockRepository)(nil).InsertEmail), arg0, arg1, arg2)
}

// InsertEmailRecipients mocks base method.
func (m *MockRepository) InsertEmailRecipients(arg0 context.Context, arg1 *sql.Tx, arg2 int64, arg3 []models.Recipient) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertEmailRecipients", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertEmailRecipients indicates an expected call of InsertEmailRecipients.
func (mr *MockRepositoryMockRecorder) InsertEmailRecipients(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertEmailRecipients", reflect.TypeOf((*MockRepository)(nil).InsertEmailRecipients), arg0, arg1, arg2, arg3)
}

// InsertExternalEmail mocks base method.
func (m *MockRepository) InsertExternalEmail(arg0 context.Context, arg1 *sql.Tx, arg2, arg3, arg4 string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertExternalEmail", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertExternalEmail indicates an expected call of InsertExternalEmail.
func (mr *MockRepositoryMockRecorder) InsertExternalEmail(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertExternalEmail", reflect.TypeOf((*MockRepository)(nil).InsertExternalEmail), arg0, arg1, arg2, arg3, arg4)
}

// InsertUserEmail mocks base method.
func (m *MockRepository) InsertUserEmail(arg0 context.Context, arg1 *sql.Tx, arg2, arg3 int64, arg4, arg5 bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertUserEmail", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertUserEmail indicates an expected call of InsertUserEmail.
func (mr *MockRepositoryMockRecorder) InsertUserEmail(arg0, arg1, arg2, arg3, arg4, arg5 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertUserEmail", reflect.TypeOf((*MockRepository)(nil).InsertUserEmail), arg0, arg1, arg2, arg3, arg4, arg5)
}

// MarkDraftAsSentTx mocks base method.
func (m *MockRepository) MarkDraftAsSentTx(arg0 context.Context, arg1 *sql.Tx, arg2, arg3 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkDraftAsSentTx", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkDraftAsSentTx indicates an expected call of MarkDraftAsSentTx.
func (mr *MockRepositoryMockRecorder) MarkDraftAsSentTx(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkDraftAsSentTx", reflect.TypeOf((*MockRepository)(nil).MarkDraftAsSentTx), arg0, arg1, arg2, arg3)
}

// ReadEmails mocks base method.
func (m *MockRepository) ReadEmails(arg0 context.Context, arg1 int64, arg2 []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadEmails", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReadEmails indicates an expected call of ReadEmails.
func (mr *MockRepositoryMockRecorder) ReadEmails(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadEmails", reflect.TypeOf((*MockRepository)(nil).ReadEmails), arg0, arg1, arg2)
}

// SpamEmails mocks base method.
func (m *MockRepository) SpamEmails(arg0 context.Context, arg1 int64, arg2 []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SpamEmails", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SpamEmails indicates an expected call of SpamEmails.
func (mr *MockRepositoryMockRecorder) SpamEmails(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SpamEmails", reflect.TypeOf((*MockRepository)(nil).SpamEmails), arg0, arg1, arg2)
}

// StarEmails mocks base method.
func (m *MockRepository) StarEmails(arg0 context.Context, arg1 int64, arg2 []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StarEmails", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// StarEmails indicates an expected call of StarEmails.
func (mr *MockRepositoryMockRecorder) StarEmails(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StarEmails", reflect.TypeOf((*MockRepository)(nil).StarEmails), arg0, arg1, arg2)
}

// SwitchIsInbox mocks base method.
func (m *MockRepository) SwitchIsInbox(arg0 context.Context, arg1, arg2 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SwitchIsInbox", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SwitchIsInbox indicates an expected call of SwitchIsInbox.
func (mr *MockRepositoryMockRecorder) SwitchIsInbox(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SwitchIsInbox", reflect.TypeOf((*MockRepository)(nil).SwitchIsInbox), arg0, arg1, arg2)
}

// TrashEmails mocks base method.
func (m *MockRepository) TrashEmails(arg0 context.Context, arg1 int64, arg2 []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TrashEmails", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// TrashEmails indicates an expected call of TrashEmails.
func (mr *MockRepositoryMockRecorder) TrashEmails(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrashEmails", reflect.TypeOf((*MockRepository)(nil).TrashEmails), arg0, arg1, arg2)
}

// UnblockSendersBatch mocks base method.
func (m *MockRepository) UnblockSendersBatch(arg0 context.Context, arg1 int64, arg2 []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnblockSendersBatch", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnblockSendersBatch indicates an expected call of UnblockSendersBatch.
func (mr *MockRepositoryMockRecorder) UnblockSendersBatch(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnblockSendersBatch", reflect.TypeOf((*MockRepository)(nil).UnblockSendersBatch), arg0, arg1, arg2)
}

// UnreadEmails mocks base method.
func (m *MockRepository) UnreadEmails(arg0 context.Context, arg1 int64, arg2 []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnreadEmails", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnreadEmails indicates an expected call of UnreadEmails.
func (mr *MockRepositoryMockRecorder) UnreadEmails(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnreadEmails", reflect.TypeOf((*MockRepository)(nil).UnreadEmails), arg0, arg1, arg2)
}

// UnspamEmails mocks base method.
func (m *MockRepository) UnspamEmails(arg0 context.Context, arg1 int64, arg2 []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnspamEmails", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnspamEmails indicates an expected call of UnspamEmails.
func (mr *MockRepositoryMockRecorder) UnspamEmails(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnspamEmails", reflect.TypeOf((*MockRepository)(nil).UnspamEmails), arg0, arg1, arg2)
}

// UnstarEmails mocks base method.
func (m *MockRepository) UnstarEmails(arg0 context.Context, arg1 int64, arg2 []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnstarEmails", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnstarEmails indicates an expected call of UnstarEmails.
func (mr *MockRepositoryMockRecorder) UnstarEmails(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnstarEmails", reflect.TypeOf((*MockRepository)(nil).UnstarEmails), arg0, arg1, arg2)
}

// UntrashEmails mocks base method.
func (m *MockRepository) UntrashEmails(arg0 context.Context, arg1 int64, arg2 []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UntrashEmails", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UntrashEmails indicates an expected call of UntrashEmails.
func (mr *MockRepositoryMockRecorder) UntrashEmails(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UntrashEmails", reflect.TypeOf((*MockRepository)(nil).UntrashEmails), arg0, arg1, arg2)
}

// UpdateDraft mocks base method.
func (m *MockRepository) UpdateDraft(arg0 context.Context, arg1 int64, arg2 models.Draft) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDraft", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDraft indicates an expected call of UpdateDraft.
func (mr *MockRepositoryMockRecorder) UpdateDraft(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDraft", reflect.TypeOf((*MockRepository)(nil).UpdateDraft), arg0, arg1, arg2)
}
