// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/email/email.proto

package email

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendSystemEmailRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RecipientUserId int64                  `protobuf:"varint,1,opt,name=recipient_user_id,json=recipientUserId,proto3" json:"recipient_user_id,omitempty"`
	RecipientEmail  string                 `protobuf:"bytes,2,opt,name=recipient_email,json=recipientEmail,proto3" json:"recipient_email,omitempty"`
	SystemEmail     string                 `protobuf:"bytes,3,opt,name=system_email,json=systemEmail,proto3" json:"system_email,omitempty"`
	Header          string                 `protobuf:"bytes,4,opt,name=header,proto3" json:"header,omitempty"`
	Body            string                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SendSystemEmailRequest) Reset() {
	*x = SendSystemEmailRequest{}
	mi := &file_proto_email_email_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSystemEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSystemEmailRequest) ProtoMessage() {}

func (x *SendSystemEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_email_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSystemEmailRequest.ProtoReflect.Descriptor instead.
func (*SendSystemEmailRequest) Descriptor() ([]byte, []int) {
	return file_proto_email_email_proto_rawDescGZIP(), []int{0}
}

func (x *SendSystemEmailRequest) GetRecipientUserId() int64 {
	if x != nil {
		return x.RecipientUserId
	}
	return 0
}

func (x *SendSystemEmailRequest) GetRecipientEmail() string {
	if x != nil {
		return x.RecipientEmail
	}
	return ""
}

func (x *SendSystemEmailRequest) GetSystemEmail() string {
	if x != nil {
		return x.SystemEmail
	}
	return ""
}

func (x *SendSystemEmailRequest) GetHeader() string {
	if x != nil {
		return x.Header
	}
	return ""
}

func (x *SendSystemEmailRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type SendSystemEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSystemEmailResponse) Reset() {
	*x = SendSystemEmailResponse{}
	mi := &file_proto_email_email_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSystemEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSystemEmailResponse) ProtoMessage() {}

func (x *SendSystemEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_email_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSystemEmailResponse.ProtoReflect.Descriptor instead.
func (*SendSystemEmailResponse) Descriptor() ([]byte, []int) {
	return file_proto_email_email_proto_rawDescGZIP(), []int{1}
}

func (x *SendSystemEmailResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetEmailIdsByUserEmailIdsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserEmailIds  []int64                `protobuf:"varint,1,rep,packed,name=user_email_ids,json=userEmailIds,proto3" json:"user_email_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmailIdsByUserEmailIdsRequest) Reset() {
	*x = GetEmailIdsByUserEmailIdsRequest{}
	mi := &file_proto_email_email_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmailIdsByUserEmailIdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmailIdsByUserEmailIdsRequest) ProtoMessage() {}

func (x *GetEmailIdsByUserEmailIdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_email_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmailIdsByUserEmailIdsRequest.ProtoReflect.Descriptor instead.
func (*GetEmailIdsByUserEmailIdsRequest) Descriptor() ([]byte, []int) {
	return file_proto_email_email_proto_rawDescGZIP(), []int{2}
}

func (x *GetEmailIdsByUserEmailIdsRequest) GetUserEmailIds() []int64 {
	if x != nil {
		return x.UserEmailIds
	}
	return nil
}

type GetEmailIdsByUserEmailIdsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmailIds      []int64                `protobuf:"varint,1,rep,packed,name=email_ids,json=emailIds,proto3" json:"email_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmailIdsByUserEmailIdsResponse) Reset() {
	*x = GetEmailIdsByUserEmailIdsResponse{}
	mi := &file_proto_email_email_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmailIdsByUserEmailIdsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmailIdsByUserEmailIdsResponse) ProtoMessage() {}

func (x *GetEmailIdsByUserEmailIdsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_email_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmailIdsByUserEmailIdsResponse.ProtoReflect.Descriptor instead.
func (*GetEmailIdsByUserEmailIdsResponse) Descriptor() ([]byte, []int) {
	return file_proto_email_email_proto_rawDescGZIP(), []int{3}
}

func (x *GetEmailIdsByUserEmailIdsResponse) GetEmailIds() []int64 {
	if x != nil {
		return x.EmailIds
	}
	return nil
}

type GetUserEmailIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmailId       int64                  `protobuf:"varint,1,opt,name=email_id,json=emailId,proto3" json:"email_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserEmailIDRequest) Reset() {
	*x = GetUserEmailIDRequest{}
	mi := &file_proto_email_email_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserEmailIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserEmailIDRequest) ProtoMessage() {}

func (x *GetUserEmailIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_email_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserEmailIDRequest.ProtoReflect.Descriptor instead.
func (*GetUserEmailIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_email_email_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserEmailIDRequest) GetEmailId() int64 {
	if x != nil {
		return x.EmailId
	}
	return 0
}

func (x *GetUserEmailIDRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserEmailIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserEmailId   int64                  `protobuf:"varint,1,opt,name=user_email_id,json=userEmailId,proto3" json:"user_email_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserEmailIDResponse) Reset() {
	*x = GetUserEmailIDResponse{}
	mi := &file_proto_email_email_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserEmailIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserEmailIDResponse) ProtoMessage() {}

func (x *GetUserEmailIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_email_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserEmailIDResponse.ProtoReflect.Descriptor instead.
func (*GetUserEmailIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_email_email_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserEmailIDResponse) GetUserEmailId() int64 {
	if x != nil {
		return x.UserEmailId
	}
	return 0
}

type SwitchIsInboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EmailId       int64                  `protobuf:"varint,2,opt,name=email_id,json=emailId,proto3" json:"email_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwitchIsInboxRequest) Reset() {
	*x = SwitchIsInboxRequest{}
	mi := &file_proto_email_email_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchIsInboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchIsInboxRequest) ProtoMessage() {}

func (x *SwitchIsInboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_email_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchIsInboxRequest.ProtoReflect.Descriptor instead.
func (*SwitchIsInboxRequest) Descriptor() ([]byte, []int) {
	return file_proto_email_email_proto_rawDescGZIP(), []int{6}
}

func (x *SwitchIsInboxRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SwitchIsInboxRequest) GetEmailId() int64 {
	if x != nil {
		return x.EmailId
	}
	return 0
}

type SwitchIsInboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwitchIsInboxResponse) Reset() {
	*x = SwitchIsInboxResponse{}
	mi := &file_proto_email_email_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchIsInboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchIsInboxResponse) ProtoMessage() {}

func (x *SwitchIsInboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_email_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchIsInboxResponse.ProtoReflect.Descriptor instead.
func (*SwitchIsInboxResponse) Descriptor() ([]byte, []int) {
	return file_proto_email_email_proto_rawDescGZIP(), []int{7}
}

func (x *SwitchIsInboxResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type Email struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SenderId  *int64                 `protobuf:"varint,2,opt,name=sender_id,json=senderId,proto3,oneof" json:"sender_id,omitempty"`
	Header    string                 `protobuf:"bytes,3,opt,name=header,proto3" json:"header,omitempty"`
	Body      string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	CreatedAt string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Помечено как анонимное при отправке.
	IsAnonymous   bool `protobuf:"varint,6,opt,name=is_anonymous,json=isAnonymous,proto3" json:"is_anonymous,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Email) Reset() {
	*x = Email{}
	mi := &file_proto_email_email_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Email) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Email) ProtoMessage() {}

func (x *Email) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_email_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Email.ProtoReflect.Descriptor instead.
func (*Email) Descriptor() ([]byte, []int) {
	return file_proto_email_email_proto_rawDescGZIP(), []int{8}
}

func (x *Email) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Email) GetSenderId() int64 {
	if x != nil && x.SenderId != nil {
		return *x.SenderId
	}
	return 0
}

func (x *Email) GetHeader() string {
	if x != nil {
		return x.Header
	}
	return ""
}

func (x *Email) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Email) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Email) GetIsAnonymous() bool {
	if x != nil {
		return x.IsAnonymous
	}
	return false
}

type GetEmailByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmailId       int64                  `protobuf:"varint,1,opt,name=email_id,json=emailId,proto3" json:"email_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmailByIdRequest) Reset() {
	*x = GetEmailByIdRequest{}
	mi := &file_proto_email_email_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmailByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmailByIdRequest) ProtoMessage() {}

func (x *GetEmailByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_email_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmailByIdRequest.ProtoReflect.Descriptor instead.
func (*GetEmailByIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_email_email_proto_rawDescGZIP(), []int{9}
}

func (x *GetEmailByIdRequest) GetEmailId() int64 {
	if x != nil {
		return x.EmailId
	}
	return 0
}

func (x *GetEmailByIdRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetEmailByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         *Email                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmailByIdResponse) Reset() {
	*x = GetEmailByIdResponse{}
	mi := &file_proto_email_email_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmailByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmailByIdResponse) ProtoMessage() {}

func (x *GetEmailByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_email_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmailByIdResponse.ProtoReflect.Descriptor instead.
func (*GetEmailByIdResponse) Descriptor() ([]byte, []int) {
	return file_proto_email_email_proto_rawDescGZIP(), []int{10}
}

func (x *GetEmailByIdResponse) GetEmail() *Email {
	if x != nil {
		return x.Email
	}
	return nil
}

type CheckEmailAccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmailId       int64                  `protobuf:"varint,1,opt,name=email_id,json=emailId,proto3" json:"email_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckEmailAccessRequest) Reset() {
	*x = CheckEmailAccessRequest{}
	mi := &file_proto_email_email_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckEmailAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckEmailAccessRequest) ProtoMessage() {}

func (x *CheckEmailAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_email_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckEmailAccessRequest.ProtoReflect.Descriptor instead.
func (*CheckEmailAccessRequest) Descriptor() ([]byte, []int) {
	return file_proto_email_email_proto_rawDescGZIP(), []int{11}
}

func (x *CheckEmailAccessRequest) GetEmailId() int64 {
	if x != nil {
		return x.EmailId
	}
	return 0
}

func (x *CheckEmailAccessRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CheckEmailAccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasAccess     bool                   `protobuf:"varint,1,opt,name=has_access,json=hasAccess,proto3" json:"has_access,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckEmailAccessResponse) Reset() {
	*x = CheckEmailAccessResponse{}
	mi := &file_proto_email_email_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckEmailAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckEmailAccessResponse) ProtoMessage() {}

func (x *CheckEmailAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_email_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckEmailAccessResponse.ProtoReflect.Descriptor instead.
func (*CheckEmailAccessResponse) Descriptor() ([]byte, []int) {
	return file_proto_email_email_proto_rawDescGZIP(), []int{12}
}

func (x *CheckEmailAccessResponse) GetHasAccess() bool {
	if x != nil {
		return x.HasAccess
	}
	return false
}

type FolderEmail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SenderEmail   string                 `protobuf:"bytes,2,opt,name=sender_email,json=senderEmail,proto3" json:"sender_email,omitempty"`
	SenderName    string                 `protobuf:"bytes,3,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`
	SenderSurname string                 `protobuf:"bytes,4,opt,name=sender_surname,json=senderSurname,proto3" json:"sender_surname,omitempty"`
	ReceiverList  []string               `protobuf:"bytes,5,rep,name=receiver_list,json=receiverList,proto3" json:"receiver_list,omitempty"`
	Header        string                 `protobuf:"bytes,6,opt,name=header,proto3" json:"header,omitempty"`
	Body          string                 `protobuf:"bytes,7,opt,name=body,proto3" json:"body,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	IsRead        bool                   `protobuf:"varint,9,opt,name=is_read,json=isRead,proto3" json:"is_read,omitempty"`
	// Если true — frontend показывает "Отправлено анонимно" вместо sender_*.
	// ВНИМАНИЕ: сервер сам решает, очищать ли sender_* для конкретного зрителя
	// (см. service.GetEmailsByIDs / buildEmailsResult).
	IsAnonymous   bool `protobuf:"varint,10,opt,name=is_anonymous,json=isAnonymous,proto3" json:"is_anonymous,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FolderEmail) Reset() {
	*x = FolderEmail{}
	mi := &file_proto_email_email_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FolderEmail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FolderEmail) ProtoMessage() {}

func (x *FolderEmail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_email_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FolderEmail.ProtoReflect.Descriptor instead.
func (*FolderEmail) Descriptor() ([]byte, []int) {
	return file_proto_email_email_proto_rawDescGZIP(), []int{13}
}

func (x *FolderEmail) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FolderEmail) GetSenderEmail() string {
	if x != nil {
		return x.SenderEmail
	}
	return ""
}

func (x *FolderEmail) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *FolderEmail) GetSenderSurname() string {
	if x != nil {
		return x.SenderSurname
	}
	return ""
}

func (x *FolderEmail) GetReceiverList() []string {
	if x != nil {
		return x.ReceiverList
	}
	return nil
}

func (x *FolderEmail) GetHeader() string {
	if x != nil {
		return x.Header
	}
	return ""
}

func (x *FolderEmail) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *FolderEmail) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *FolderEmail) GetIsRead() bool {
	if x != nil {
		return x.IsRead
	}
	return false
}

func (x *FolderEmail) GetIsAnonymous() bool {
	if x != nil {
		return x.IsAnonymous
	}
	return false
}

type GetEmailsByIdsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmailIds      []int64                `protobuf:"varint,1,rep,packed,name=email_ids,json=emailIds,proto3" json:"email_ids,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmailsByIdsRequest) Reset() {
	*x = GetEmailsByIdsRequest{}
	mi := &file_proto_email_email_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmailsByIdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmailsByIdsRequest) ProtoMessage() {}

func (x *GetEmailsByIdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_email_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmailsByIdsRequest.ProtoReflect.Descriptor instead.
func (*GetEmailsByIdsRequest) Descriptor() ([]byte, []int) {
	return file_proto_email_email_proto_rawDescGZIP(), []int{14}
}

func (x *GetEmailsByIdsRequest) GetEmailIds() []int64 {
	if x != nil {
		return x.EmailIds
	}
	return nil
}

func (x *GetEmailsByIdsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetEmailsByIdsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Emails        []*FolderEmail         `protobuf:"bytes,1,rep,name=emails,proto3" json:"emails,omitempty"`
	UnreadCount   int32                  `protobuf:"varint,2,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmailsByIdsResponse) Reset() {
	*x = GetEmailsByIdsResponse{}
	mi := &file_proto_email_email_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmailsByIdsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmailsByIdsResponse) ProtoMessage() {}

func (x *GetEmailsByIdsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_email_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmailsByIdsResponse.ProtoReflect.Descriptor instead.
func (*GetEmailsByIdsResponse) Descriptor() ([]byte, []int) {
	return file_proto_email_email_proto_rawDescGZIP(), []int{15}
}

func (x *GetEmailsByIdsResponse) GetEmails() []*FolderEmail {
	if x != nil {
		return x.Emails
	}
	return nil
}

func (x *GetEmailsByIdsResponse) GetUnreadCount() int32 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

type GetEmailForSupportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmailId       int64                  `protobuf:"varint,1,opt,name=email_id,json=emailId,proto3" json:"email_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmailForSupportRequest) Reset() {
	*x = GetEmailForSupportRequest{}
	mi := &file_proto_email_email_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmailForSupportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmailForSupportRequest) ProtoMessage() {}

func (x *GetEmailForSupportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_email_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmailForSupportRequest.ProtoReflect.Descriptor instead.
func (*GetEmailForSupportRequest) Descriptor() ([]byte, []int) {
	return file_proto_email_email_proto_rawDescGZIP(), []int{16}
}

func (x *GetEmailForSupportRequest) GetEmailId() int64 {
	if x != nil {
		return x.EmailId
	}
	return 0
}

type SupportSenderInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// user_id может быть nil только для внешних писем (LMTP-приём).
	// Для анонимных писем — всегда заполнен.
	UserId        *int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`
	Email         string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name          string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Surname       string `protobuf:"bytes,4,opt,name=surname,proto3" json:"surname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SupportSenderInfo) Reset() {
	*x = SupportSenderInfo{}
	mi := &file_proto_email_email_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupportSenderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupportSenderInfo) ProtoMessage() {}

func (x *SupportSenderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_email_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupportSenderInfo.ProtoReflect.Descriptor instead.
func (*SupportSenderInfo) Descriptor() ([]byte, []int) {
	return file_proto_email_email_proto_rawDescGZIP(), []int{17}
}

func (x *SupportSenderInfo) GetUserId() int64 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

func (x *SupportSenderInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SupportSenderInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SupportSenderInfo) GetSurname() string {
	if x != nil {
		return x.Surname
	}
	return ""
}

type SupportAttachment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SupportAttachment) Reset() {
	*x = SupportAttachment{}
	mi := &file_proto_email_email_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupportAttachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupportAttachment) ProtoMessage() {}

func (x *SupportAttachment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_email_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupportAttachment.ProtoReflect.Descriptor instead.
func (*SupportAttachment) Descriptor() ([]byte, []int) {
	return file_proto_email_email_proto_rawDescGZIP(), []int{18}
}

func (x *SupportAttachment) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SupportAttachment) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *SupportAttachment) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *SupportAttachment) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *SupportAttachment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetEmailForSupportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Sender        *SupportSenderInfo     `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	Recipients    []string               `protobuf:"bytes,3,rep,name=recipients,proto3" json:"recipients,omitempty"`
	Header        string                 `protobuf:"bytes,4,opt,name=header,proto3" json:"header,omitempty"`
	Body          string                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	IsAnonymous   bool                   `protobuf:"varint,7,opt,name=is_anonymous,json=isAnonymous,proto3" json:"is_anonymous,omitempty"`
	IsDraft       bool                   `protobuf:"varint,8,opt,name=is_draft,json=isDraft,proto3" json:"is_draft,omitempty"`
	Attachments   []*SupportAttachment   `protobuf:"bytes,9,rep,name=attachments,proto3" json:"attachments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmailForSupportResponse) Reset() {
	*x = GetEmailForSupportResponse{}
	mi := &file_proto_email_email_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmailForSupportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmailForSupportResponse) ProtoMessage() {}

func (x *GetEmailForSupportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_email_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmailForSupportResponse.ProtoReflect.Descriptor instead.
func (*GetEmailForSupportResponse) Descriptor() ([]byte, []int) {
	return file_proto_email_email_proto_rawDescGZIP(), []int{19}
}

func (x *GetEmailForSupportResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetEmailForSupportResponse) GetSender() *SupportSenderInfo {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *GetEmailForSupportResponse) GetRecipients() []string {
	if x != nil {
		return x.Recipients
	}
	return nil
}

func (x *GetEmailForSupportResponse) GetHeader() string {
	if x != nil {
		return x.Header
	}
	return ""
}

func (x *GetEmailForSupportResponse) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *GetEmailForSupportResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetEmailForSupportResponse) GetIsAnonymous() bool {
	if x != nil {
		return x.IsAnonymous
	}
	return false
}

func (x *GetEmailForSupportResponse) GetIsDraft() bool {
	if x != nil {
		return x.IsDraft
	}
	return false
}

func (x *GetEmailForSupportResponse) GetAttachments() []*SupportAttachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

var File_proto_email_email_proto protoreflect.FileDescriptor

const file_proto_email_email_proto_rawDesc = "" +
	"\n" +
	"\x17proto/email/email.proto\x12\x05email\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbc\x01\n" +
	"\x16SendSystemEmailRequest\x12*\n" +
	"\x11recipient_user_id\x18\x01 \x01(\x03R\x0frecipientUserId\x12'\n" +
	"\x0frecipient_email\x18\x02 \x01(\tR\x0erecipientEmail\x12!\n" +
	"\fsystem_email\x18\x03 \x01(\tR\vsystemEmail\x12\x16\n" +
	"\x06header\x18\x04 \x01(\tR\x06header\x12\x12\n" +
	"\x04body\x18\x05 \x01(\tR\x04body\"3\n" +
	"\x17SendSystemEmailResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"H\n" +
	" GetEmailIdsByUserEmailIdsRequest\x12$\n" +
	"\x0euser_email_ids\x18\x01 \x03(\x03R\fuserEmailIds\"@\n" +
	"!GetEmailIdsByUserEmailIdsResponse\x12\x1b\n" +
	"\temail_ids\x18\x01 \x03(\x03R\bemailIds\"K\n" +
	"\x15GetUserEmailIDRequest\x12\x19\n" +
	"\bemail_id\x18\x01 \x01(\x03R\aemailId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"<\n" +
	"\x16GetUserEmailIDResponse\x12\"\n" +
	"\ruser_email_id\x18\x01 \x01(\x03R\vuserEmailId\"J\n" +
	"\x14SwitchIsInboxRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\bemail_id\x18\x02 \x01(\x03R\aemailId\"1\n" +
	"\x15SwitchIsInboxResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xb5\x01\n" +
	"\x05Email\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12 \n" +
	"\tsender_id\x18\x02 \x01(\x03H\x00R\bsenderId\x88\x01\x01\x12\x16\n" +
	"\x06header\x18\x03 \x01(\tR\x06header\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12!\n" +
	"\fis_anonymous\x18\x06 \x01(\bR\visAnonymousB\f\n" +
	"\n" +
	"_sender_id\"I\n" +
	"\x13GetEmailByIdRequest\x12\x19\n" +
	"\bemail_id\x18\x01 \x01(\x03R\aemailId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\":\n" +
	"\x14GetEmailByIdResponse\x12\"\n" +
	"\x05email\x18\x01 \x01(\v2\f.email.EmailR\x05email\"M\n" +
	"\x17CheckEmailAccessRequest\x12\x19\n" +
	"\bemail_id\x18\x01 \x01(\x03R\aemailId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"9\n" +
	"\x18CheckEmailAccessResponse\x12\x1d\n" +
	"\n" +
	"has_access\x18\x01 \x01(\bR\thasAccess\"\xd0\x02\n" +
	"\vFolderEmail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12!\n" +
	"\fsender_email\x18\x02 \x01(\tR\vsenderEmail\x12\x1f\n" +
	"\vsender_name\x18\x03 \x01(\tR\n" +
	"senderName\x12%\n" +
	"\x0esender_surname\x18\x04 \x01(\tR\rsenderSurname\x12#\n" +
	"\rreceiver_list\x18\x05 \x03(\tR\freceiverList\x12\x16\n" +
	"\x06header\x18\x06 \x01(\tR\x06header\x12\x12\n" +
	"\x04body\x18\a \x01(\tR\x04body\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x17\n" +
	"\ais_read\x18\t \x01(\bR\x06isRead\x12!\n" +
	"\fis_anonymous\x18\n" +
	" \x01(\bR\visAnonymous\"M\n" +
	"\x15GetEmailsByIdsRequest\x12\x1b\n" +
	"\temail_ids\x18\x01 \x03(\x03R\bemailIds\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"g\n" +
	"\x16GetEmailsByIdsResponse\x12*\n" +
	"\x06emails\x18\x01 \x03(\v2\x12.email.FolderEmailR\x06emails\x12!\n" +
	"\funread_count\x18\x02 \x01(\x05R\vunreadCount\"6\n" +
	"\x19GetEmailForSupportRequest\x12\x19\n" +
	"\bemail_id\x18\x01 \x01(\x03R\aemailId\"\x81\x01\n" +
	"\x11SupportSenderInfo\x12\x1c\n" +
	"\auser_id\x18\x01 \x01(\x03H\x00R\x06userId\x88\x01\x01\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\asurname\x18\x04 \x01(\tR\asurnameB\n" +
	"\n" +
	"\b_user_id\"\xbc\x01\n" +
	"\x11SupportAttachment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x03R\tsizeBytes\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xdf\x02\n" +
	"\x1aGetEmailForSupportResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x120\n" +
	"\x06sender\x18\x02 \x01(\v2\x18.email.SupportSenderInfoR\x06sender\x12\x1e\n" +
	"\n" +
	"recipients\x18\x03 \x03(\tR\n" +
	"recipients\x12\x16\n" +
	"\x06header\x18\x04 \x01(\tR\x06header\x12\x12\n" +
	"\x04body\x18\x05 \x01(\tR\x04body\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12!\n" +
	"\fis_anonymous\x18\a \x01(\bR\visAnonymous\x12\x19\n" +
	"\bis_draft\x18\b \x01(\bR\aisDraft\x12:\n" +
	"\vattachments\x18\t \x03(\v2\x18.email.SupportAttachmentR\vattachments2\xb3\x05\n" +
	"\fEmailService\x12G\n" +
	"\fGetEmailById\x12\x1a.email.GetEmailByIdRequest\x1a\x1b.email.GetEmailByIdResponse\x12n\n" +
	"\x19GetEmailIdsByUserEmailIds\x12'.email.GetEmailIdsByUserEmailIdsRequest\x1a(.email.GetEmailIdsByUserEmailIdsResponse\x12S\n" +
	"\x10CheckEmailAccess\x12\x1e.email.CheckEmailAccessRequest\x1a\x1f.email.CheckEmailAccessResponse\x12M\n" +
	"\x0eGetEmailsByIds\x12\x1c.email.GetEmailsByIdsRequest\x1a\x1d.email.GetEmailsByIdsResponse\x12J\n" +
	"\rSwitchIsInbox\x12\x1b.email.SwitchIsInboxRequest\x1a\x1c.email.SwitchIsInboxResponse\x12M\n" +
	"\x0eGetUserEmailID\x12\x1c.email.GetUserEmailIDRequest\x1a\x1d.email.GetUserEmailIDResponse\x12P\n" +
	"\x0fSendSystemEmail\x12\x1d.email.SendSystemEmailRequest\x1a\x1e.email.SendSystemEmailResponse\x12Y\n" +
	"\x12GetEmailForSupport\x12 .email.GetEmailForSupportRequest\x1a!.email.GetEmailForSupportResponseB\x0fZ\r./proto/emailb\x06proto3"

var (
	file_proto_email_email_proto_rawDescOnce sync.Once
	file_proto_email_email_proto_rawDescData []byte
)

func file_proto_email_email_proto_rawDescGZIP() []byte {
	file_proto_email_email_proto_rawDescOnce.Do(func() {
		file_proto_email_email_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_email_email_proto_rawDesc), len(file_proto_email_email_proto_rawDesc)))
	})
	return file_proto_email_email_proto_rawDescData
}

var file_proto_email_email_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_proto_email_email_proto_goTypes = []any{
	(*SendSystemEmailRequest)(nil),            // 0: email.SendSystemEmailRequest
	(*SendSystemEmailResponse)(nil),           // 1: email.SendSystemEmailResponse
	(*GetEmailIdsByUserEmailIdsRequest)(nil),  // 2: email.GetEmailIdsByUserEmailIdsRequest
	(*GetEmailIdsByUserEmailIdsResponse)(nil), // 3: email.GetEmailIdsByUserEmailIdsResponse
	(*GetUserEmailIDRequest)(nil),             // 4: email.GetUserEmailIDRequest
	(*GetUserEmailIDResponse)(nil),            // 5: email.GetUserEmailIDResponse
	(*SwitchIsInboxRequest)(nil),              // 6: email.SwitchIsInboxRequest
	(*SwitchIsInboxResponse)(nil),             // 7: email.SwitchIsInboxResponse
	(*Email)(nil),                             // 8: email.Email
	(*GetEmailByIdRequest)(nil),               // 9: email.GetEmailByIdRequest
	(*GetEmailByIdResponse)(nil),              // 10: email.GetEmailByIdResponse
	(*CheckEmailAccessRequest)(nil),           // 11: email.CheckEmailAccessRequest
	(*CheckEmailAccessResponse)(nil),          // 12: email.CheckEmailAccessResponse
	(*FolderEmail)(nil),                       // 13: email.FolderEmail
	(*GetEmailsByIdsRequest)(nil),             // 14: email.GetEmailsByIdsRequest
	(*GetEmailsByIdsResponse)(nil),            // 15: email.GetEmailsByIdsResponse
	(*GetEmailForSupportRequest)(nil),         // 16: email.GetEmailForSupportRequest
	(*SupportSenderInfo)(nil),                 // 17: email.SupportSenderInfo
	(*SupportAttachment)(nil),                 // 18: email.SupportAttachment
	(*GetEmailForSupportResponse)(nil),        // 19: email.GetEmailForSupportResponse
	(*timestamppb.Timestamp)(nil),             // 20: google.protobuf.Timestamp
}
var file_proto_email_email_proto_depIdxs = []int32{
	8,  // 0: email.GetEmailByIdResponse.email:type_name -> email.Email
	20, // 1: email.FolderEmail.created_at:type_name -> google.protobuf.Timestamp
	13, // 2: email.GetEmailsByIdsResponse.emails:type_name -> email.FolderEmail
	20, // 3: email.SupportAttachment.created_at:type_name -> google.protobuf.Timestamp
	17, // 4: email.GetEmailForSupportResponse.sender:type_name -> email.SupportSenderInfo
	20, // 5: email.GetEmailForSupportResponse.created_at:type_name -> google.protobuf.Timestamp
	18, // 6: email.GetEmailForSupportResponse.attachments:type_name -> email.SupportAttachment
	9,  // 7: email.EmailService.GetEmailById:input_type -> email.GetEmailByIdRequest
	2,  // 8: email.EmailService.GetEmailIdsByUserEmailIds:input_type -> email.GetEmailIdsByUserEmailIdsRequest
	11, // 9: email.EmailService.CheckEmailAccess:input_type -> email.CheckEmailAccessRequest
	14, // 10: email.EmailService.GetEmailsByIds:input_type -> email.GetEmailsByIdsRequest
	6,  // 11: email.EmailService.SwitchIsInbox:input_type -> email.SwitchIsInboxRequest
	4,  // 12: email.EmailService.GetUserEmailID:input_type -> email.GetUserEmailIDRequest
	0,  // 13: email.EmailService.SendSystemEmail:input_type -> email.SendSystemEmailRequest
	16, // 14: email.EmailService.GetEmailForSupport:input_type -> email.GetEmailForSupportRequest
	10, // 15: email.EmailService.GetEmailById:output_type -> email.GetEmailByIdResponse
	3,  // 16: email.EmailService.GetEmailIdsByUserEmailIds:output_type -> email.GetEmailIdsByUserEmailIdsResponse
	12, // 17: email.EmailService.CheckEmailAccess:output_type -> email.CheckEmailAccessResponse
	15, // 18: email.EmailService.GetEmailsByIds:output_type -> email.GetEmailsByIdsResponse
	7,  // 19: email.EmailService.SwitchIsInbox:output_type -> email.SwitchIsInboxResponse
	5,  // 20: email.EmailService.GetUserEmailID:output_type -> email.GetUserEmailIDResponse
	1,  // 21: email.EmailService.SendSystemEmail:output_type -> email.SendSystemEmailResponse
	19, // 22: email.EmailService.GetEmailForSupport:output_type -> email.GetEmailForSupportResponse
	15, // [15:23] is the sub-list for method output_type
	7,  // [7:15] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_email_email_proto_init() }
func file_proto_email_email_proto_init() {
	if File_proto_email_email_proto != nil {
		return
	}
	file_proto_email_email_proto_msgTypes[8].OneofWrappers = []any{}
	file_proto_email_email_proto_msgTypes[17].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_email_email_proto_rawDesc), len(file_proto_email_email_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_email_email_proto_goTypes,
		DependencyIndexes: file_proto_email_email_proto_depIdxs,
		MessageInfos:      file_proto_email_email_proto_msgTypes,
	}.Build()
	File_proto_email_email_proto = out.File
	file_proto_email_email_proto_goTypes = nil
	file_proto_email_email_proto_depIdxs = nil
}
