// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/email/email.proto

package email

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Email struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SenderId      int64                  `protobuf:"varint,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Header        string                 `protobuf:"bytes,3,opt,name=header,proto3" json:"header,omitempty"`
	Body          string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Email) Reset() {
	*x = Email{}
	mi := &file_proto_email_email_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Email) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Email) ProtoMessage() {}

func (x *Email) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_email_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Email.ProtoReflect.Descriptor instead.
func (*Email) Descriptor() ([]byte, []int) {
	return file_proto_email_email_proto_rawDescGZIP(), []int{0}
}

func (x *Email) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Email) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *Email) GetHeader() string {
	if x != nil {
		return x.Header
	}
	return ""
}

func (x *Email) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Email) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetEmailByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmailId       int64                  `protobuf:"varint,1,opt,name=email_id,json=emailId,proto3" json:"email_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmailByIdRequest) Reset() {
	*x = GetEmailByIdRequest{}
	mi := &file_proto_email_email_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmailByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmailByIdRequest) ProtoMessage() {}

func (x *GetEmailByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_email_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmailByIdRequest.ProtoReflect.Descriptor instead.
func (*GetEmailByIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_email_email_proto_rawDescGZIP(), []int{1}
}

func (x *GetEmailByIdRequest) GetEmailId() int64 {
	if x != nil {
		return x.EmailId
	}
	return 0
}

func (x *GetEmailByIdRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetEmailByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         *Email                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmailByIdResponse) Reset() {
	*x = GetEmailByIdResponse{}
	mi := &file_proto_email_email_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmailByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmailByIdResponse) ProtoMessage() {}

func (x *GetEmailByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_email_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmailByIdResponse.ProtoReflect.Descriptor instead.
func (*GetEmailByIdResponse) Descriptor() ([]byte, []int) {
	return file_proto_email_email_proto_rawDescGZIP(), []int{2}
}

func (x *GetEmailByIdResponse) GetEmail() *Email {
	if x != nil {
		return x.Email
	}
	return nil
}

type CheckEmailAccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmailId       int64                  `protobuf:"varint,1,opt,name=email_id,json=emailId,proto3" json:"email_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckEmailAccessRequest) Reset() {
	*x = CheckEmailAccessRequest{}
	mi := &file_proto_email_email_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckEmailAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckEmailAccessRequest) ProtoMessage() {}

func (x *CheckEmailAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_email_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckEmailAccessRequest.ProtoReflect.Descriptor instead.
func (*CheckEmailAccessRequest) Descriptor() ([]byte, []int) {
	return file_proto_email_email_proto_rawDescGZIP(), []int{3}
}

func (x *CheckEmailAccessRequest) GetEmailId() int64 {
	if x != nil {
		return x.EmailId
	}
	return 0
}

func (x *CheckEmailAccessRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CheckEmailAccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasAccess     bool                   `protobuf:"varint,1,opt,name=has_access,json=hasAccess,proto3" json:"has_access,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckEmailAccessResponse) Reset() {
	*x = CheckEmailAccessResponse{}
	mi := &file_proto_email_email_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckEmailAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckEmailAccessResponse) ProtoMessage() {}

func (x *CheckEmailAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_email_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckEmailAccessResponse.ProtoReflect.Descriptor instead.
func (*CheckEmailAccessResponse) Descriptor() ([]byte, []int) {
	return file_proto_email_email_proto_rawDescGZIP(), []int{4}
}

func (x *CheckEmailAccessResponse) GetHasAccess() bool {
	if x != nil {
		return x.HasAccess
	}
	return false
}

var File_proto_email_email_proto protoreflect.FileDescriptor

const file_proto_email_email_proto_rawDesc = "" +
	"\n" +
	"\x17proto/email/email.proto\x12\x05email\"\x7f\n" +
	"\x05Email\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\x03R\bsenderId\x12\x16\n" +
	"\x06header\x18\x03 \x01(\tR\x06header\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"I\n" +
	"\x13GetEmailByIdRequest\x12\x19\n" +
	"\bemail_id\x18\x01 \x01(\x03R\aemailId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\":\n" +
	"\x14GetEmailByIdResponse\x12\"\n" +
	"\x05email\x18\x01 \x01(\v2\f.email.EmailR\x05email\"M\n" +
	"\x17CheckEmailAccessRequest\x12\x19\n" +
	"\bemail_id\x18\x01 \x01(\x03R\aemailId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"9\n" +
	"\x18CheckEmailAccessResponse\x12\x1d\n" +
	"\n" +
	"has_access\x18\x01 \x01(\bR\thasAccess2\xac\x01\n" +
	"\fEmailService\x12G\n" +
	"\fGetEmailById\x12\x1a.email.GetEmailByIdRequest\x1a\x1b.email.GetEmailByIdResponse\x12S\n" +
	"\x10CheckEmailAccess\x12\x1e.email.CheckEmailAccessRequest\x1a\x1f.email.CheckEmailAccessResponseB\x0fZ\r./proto/emailb\x06proto3"

var (
	file_proto_email_email_proto_rawDescOnce sync.Once
	file_proto_email_email_proto_rawDescData []byte
)

func file_proto_email_email_proto_rawDescGZIP() []byte {
	file_proto_email_email_proto_rawDescOnce.Do(func() {
		file_proto_email_email_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_email_email_proto_rawDesc), len(file_proto_email_email_proto_rawDesc)))
	})
	return file_proto_email_email_proto_rawDescData
}

var file_proto_email_email_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_email_email_proto_goTypes = []any{
	(*Email)(nil),                    // 0: email.Email
	(*GetEmailByIdRequest)(nil),      // 1: email.GetEmailByIdRequest
	(*GetEmailByIdResponse)(nil),     // 2: email.GetEmailByIdResponse
	(*CheckEmailAccessRequest)(nil),  // 3: email.CheckEmailAccessRequest
	(*CheckEmailAccessResponse)(nil), // 4: email.CheckEmailAccessResponse
}
var file_proto_email_email_proto_depIdxs = []int32{
	0, // 0: email.GetEmailByIdResponse.email:type_name -> email.Email
	1, // 1: email.EmailService.GetEmailById:input_type -> email.GetEmailByIdRequest
	3, // 2: email.EmailService.CheckEmailAccess:input_type -> email.CheckEmailAccessRequest
	2, // 3: email.EmailService.GetEmailById:output_type -> email.GetEmailByIdResponse
	4, // 4: email.EmailService.CheckEmailAccess:output_type -> email.CheckEmailAccessResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_email_email_proto_init() }
func file_proto_email_email_proto_init() {
	if File_proto_email_email_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_email_email_proto_rawDesc), len(file_proto_email_email_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_email_email_proto_goTypes,
		DependencyIndexes: file_proto_email_email_proto_depIdxs,
		MessageInfos:      file_proto_email_email_proto_msgTypes,
	}.Build()
	File_proto_email_email_proto = out.File
	file_proto_email_email_proto_goTypes = nil
	file_proto_email_email_proto_depIdxs = nil
}
