// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2026_1_PushToMain/microservices/folder/service (interfaces: EmailClient)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	email "github.com/go-park-mail-ru/2026_1_PushToMain/proto/email"
	gomock "github.com/golang/mock/gomock"
)

// MockEmailClient is a mock of EmailClient interface.
type MockEmailClient struct {
	ctrl     *gomock.Controller
	recorder *MockEmailClientMockRecorder
}

// MockEmailClientMockRecorder is the mock recorder for MockEmailClient.
type MockEmailClientMockRecorder struct {
	mock *MockEmailClient
}

// NewMockEmailClient creates a new mock instance.
func NewMockEmailClient(ctrl *gomock.Controller) *MockEmailClient {
	mock := &MockEmailClient{ctrl: ctrl}
	mock.recorder = &MockEmailClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailClient) EXPECT() *MockEmailClientMockRecorder {
	return m.recorder
}

// CheckEmailAccess mocks base method.
func (m *MockEmailClient) CheckEmailAccess(arg0 context.Context, arg1, arg2 int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckEmailAccess", arg0, arg1, arg2)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckEmailAccess indicates an expected call of CheckEmailAccess.
func (mr *MockEmailClientMockRecorder) CheckEmailAccess(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckEmailAccess", reflect.TypeOf((*MockEmailClient)(nil).CheckEmailAccess), arg0, arg1, arg2)
}

// GetEmailByID mocks base method.
func (m *MockEmailClient) GetEmailByID(arg0 context.Context, arg1, arg2 int64) (*email.Email, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmailByID", arg0, arg1, arg2)
	ret0, _ := ret[0].(*email.Email)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmailByID indicates an expected call of GetEmailByID.
func (mr *MockEmailClientMockRecorder) GetEmailByID(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmailByID", reflect.TypeOf((*MockEmailClient)(nil).GetEmailByID), arg0, arg1, arg2)
}

// GetEmailIdsByUserEmailIds mocks base method.
func (m *MockEmailClient) GetEmailIdsByUserEmailIds(arg0 context.Context, arg1 []int64) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmailIdsByUserEmailIds", arg0, arg1)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmailIdsByUserEmailIds indicates an expected call of GetEmailIdsByUserEmailIds.
func (mr *MockEmailClientMockRecorder) GetEmailIdsByUserEmailIds(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmailIdsByUserEmailIds", reflect.TypeOf((*MockEmailClient)(nil).GetEmailIdsByUserEmailIds), arg0, arg1)
}

// GetEmailsByIDs mocks base method.
func (m *MockEmailClient) GetEmailsByIDs(arg0 context.Context, arg1 []int64, arg2 int64) (*email.GetEmailsByIdsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmailsByIDs", arg0, arg1, arg2)
	ret0, _ := ret[0].(*email.GetEmailsByIdsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmailsByIDs indicates an expected call of GetEmailsByIDs.
func (mr *MockEmailClientMockRecorder) GetEmailsByIDs(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmailsByIDs", reflect.TypeOf((*MockEmailClient)(nil).GetEmailsByIDs), arg0, arg1, arg2)
}

// GetUserEmailID mocks base method.
func (m *MockEmailClient) GetUserEmailID(arg0 context.Context, arg1, arg2 int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserEmailID", arg0, arg1, arg2)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserEmailID indicates an expected call of GetUserEmailID.
func (mr *MockEmailClientMockRecorder) GetUserEmailID(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserEmailID", reflect.TypeOf((*MockEmailClient)(nil).GetUserEmailID), arg0, arg1, arg2)
}

// SwitchIsInbox mocks base method.
func (m *MockEmailClient) SwitchIsInbox(arg0 context.Context, arg1, arg2 int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SwitchIsInbox", arg0, arg1, arg2)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SwitchIsInbox indicates an expected call of SwitchIsInbox.
func (mr *MockEmailClientMockRecorder) SwitchIsInbox(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SwitchIsInbox", reflect.TypeOf((*MockEmailClient)(nil).SwitchIsInbox), arg0, arg1, arg2)
}
