// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2026_1_PushToMain/microservices/folder/service (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=../../../mocks/app/folder/mock_repository.go -package=mocks github.com/go-park-mail-ru/2026_1_PushToMain/microservices/folder/service Repository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/go-park-mail-ru/2026_1_PushToMain/microservices/folder/models"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// AddEmailToFolder mocks base method.
func (m *MockRepository) AddEmailToFolder(ctx context.Context, folderID, emailID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddEmailToFolder", ctx, folderID, emailID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddEmailToFolder indicates an expected call of AddEmailToFolder.
func (mr *MockRepositoryMockRecorder) AddEmailToFolder(ctx, folderID, emailID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddEmailToFolder", reflect.TypeOf((*MockRepository)(nil).AddEmailToFolder), ctx, folderID, emailID)
}

// CountEmailsInFolder mocks base method.
func (m *MockRepository) CountEmailsInFolder(ctx context.Context, folderID int64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountEmailsInFolder", ctx, folderID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountEmailsInFolder indicates an expected call of CountEmailsInFolder.
func (mr *MockRepositoryMockRecorder) CountEmailsInFolder(ctx, folderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountEmailsInFolder", reflect.TypeOf((*MockRepository)(nil).CountEmailsInFolder), ctx, folderID)
}

// CountUserFolders mocks base method.
func (m *MockRepository) CountUserFolders(ctx context.Context, userID int64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUserFolders", ctx, userID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUserFolders indicates an expected call of CountUserFolders.
func (mr *MockRepositoryMockRecorder) CountUserFolders(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUserFolders", reflect.TypeOf((*MockRepository)(nil).CountUserFolders), ctx, userID)
}

// CreateFolder mocks base method.
func (m *MockRepository) CreateFolder(ctx context.Context, folder models.Folder) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFolder", ctx, folder)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateFolder indicates an expected call of CreateFolder.
func (mr *MockRepositoryMockRecorder) CreateFolder(ctx, folder any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFolder", reflect.TypeOf((*MockRepository)(nil).CreateFolder), ctx, folder)
}

// DeleteEmailFromFolder mocks base method.
func (m *MockRepository) DeleteEmailFromFolder(ctx context.Context, folderID, emailID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEmailFromFolder", ctx, folderID, emailID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEmailFromFolder indicates an expected call of DeleteEmailFromFolder.
func (mr *MockRepositoryMockRecorder) DeleteEmailFromFolder(ctx, folderID, emailID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEmailFromFolder", reflect.TypeOf((*MockRepository)(nil).DeleteEmailFromFolder), ctx, folderID, emailID)
}

// DeleteFolder mocks base method.
func (m *MockRepository) DeleteFolder(ctx context.Context, folderID, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFolder", ctx, folderID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFolder indicates an expected call of DeleteFolder.
func (mr *MockRepositoryMockRecorder) DeleteFolder(ctx, folderID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFolder", reflect.TypeOf((*MockRepository)(nil).DeleteFolder), ctx, folderID, userID)
}

// GetFolderByID mocks base method.
func (m *MockRepository) GetFolderByID(ctx context.Context, folderID int64) (*models.Folder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFolderByID", ctx, folderID)
	ret0, _ := ret[0].(*models.Folder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFolderByID indicates an expected call of GetFolderByID.
func (mr *MockRepositoryMockRecorder) GetFolderByID(ctx, folderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFolderByID", reflect.TypeOf((*MockRepository)(nil).GetFolderByID), ctx, folderID)
}

// GetFolderByName mocks base method.
func (m *MockRepository) GetFolderByName(ctx context.Context, userID int64, name string) (*models.Folder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFolderByName", ctx, userID, name)
	ret0, _ := ret[0].(*models.Folder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFolderByName indicates an expected call of GetFolderByName.
func (mr *MockRepositoryMockRecorder) GetFolderByName(ctx, userID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFolderByName", reflect.TypeOf((*MockRepository)(nil).GetFolderByName), ctx, userID, name)
}

// GetFolderEmailIDs mocks base method.
func (m *MockRepository) GetFolderEmailIDs(ctx context.Context, folderID int64, limit, offset int) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFolderEmailIDs", ctx, folderID, limit, offset)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFolderEmailIDs indicates an expected call of GetFolderEmailIDs.
func (mr *MockRepositoryMockRecorder) GetFolderEmailIDs(ctx, folderID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFolderEmailIDs", reflect.TypeOf((*MockRepository)(nil).GetFolderEmailIDs), ctx, folderID, limit, offset)
}

// UpdateFolderName mocks base method.
func (m *MockRepository) UpdateFolderName(ctx context.Context, folderID int64, newName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFolderName", ctx, folderID, newName)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFolderName indicates an expected call of UpdateFolderName.
func (mr *MockRepositoryMockRecorder) UpdateFolderName(ctx, folderID, newName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFolderName", reflect.TypeOf((*MockRepository)(nil).UpdateFolderName), ctx, folderID, newName)
}
