// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2026_1_PushToMain/microservices/folder/service (interfaces: EmailClient)
//
// Generated by this command:
//
//	mockgen -destination=../../../mocks/app/folder/mock_email_client.go -package=mocks github.com/go-park-mail-ru/2026_1_PushToMain/microservices/folder/service EmailClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	email "github.com/go-park-mail-ru/2026_1_PushToMain/proto/email"
	gomock "go.uber.org/mock/gomock"
)

// MockEmailClient is a mock of EmailClient interface.
type MockEmailClient struct {
	ctrl     *gomock.Controller
	recorder *MockEmailClientMockRecorder
	isgomock struct{}
}

// MockEmailClientMockRecorder is the mock recorder for MockEmailClient.
type MockEmailClientMockRecorder struct {
	mock *MockEmailClient
}

// NewMockEmailClient creates a new mock instance.
func NewMockEmailClient(ctrl *gomock.Controller) *MockEmailClient {
	mock := &MockEmailClient{ctrl: ctrl}
	mock.recorder = &MockEmailClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailClient) EXPECT() *MockEmailClientMockRecorder {
	return m.recorder
}

// CheckEmailAccess mocks base method.
func (m *MockEmailClient) CheckEmailAccess(ctx context.Context, emailID, userID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckEmailAccess", ctx, emailID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckEmailAccess indicates an expected call of CheckEmailAccess.
func (mr *MockEmailClientMockRecorder) CheckEmailAccess(ctx, emailID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckEmailAccess", reflect.TypeOf((*MockEmailClient)(nil).CheckEmailAccess), ctx, emailID, userID)
}

// GetEmailByID mocks base method.
func (m *MockEmailClient) GetEmailByID(ctx context.Context, emailID, userID int64) (*email.Email, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmailByID", ctx, emailID, userID)
	ret0, _ := ret[0].(*email.Email)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmailByID indicates an expected call of GetEmailByID.
func (mr *MockEmailClientMockRecorder) GetEmailByID(ctx, emailID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmailByID", reflect.TypeOf((*MockEmailClient)(nil).GetEmailByID), ctx, emailID, userID)
}

// GetEmailsByIDs mocks base method.
func (m *MockEmailClient) GetEmailsByIDs(ctx context.Context, emailIDs []int64, userID int64) (*email.GetEmailsByIdsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmailsByIDs", ctx, emailIDs, userID)
	ret0, _ := ret[0].(*email.GetEmailsByIdsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmailsByIDs indicates an expected call of GetEmailsByIDs.
func (mr *MockEmailClientMockRecorder) GetEmailsByIDs(ctx, emailIDs, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmailsByIDs", reflect.TypeOf((*MockEmailClient)(nil).GetEmailsByIDs), ctx, emailIDs, userID)
}
