// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2026_1_PushToMain/microservices/folder/service (interfaces: Repository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/go-park-mail-ru/2026_1_PushToMain/microservices/folder/models"
	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// AddEmailToFolder mocks base method.
func (m *MockRepository) AddEmailToFolder(arg0 context.Context, arg1, arg2 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddEmailToFolder", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddEmailToFolder indicates an expected call of AddEmailToFolder.
func (mr *MockRepositoryMockRecorder) AddEmailToFolder(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddEmailToFolder", reflect.TypeOf((*MockRepository)(nil).AddEmailToFolder), arg0, arg1, arg2)
}

// CountEmailsInFolder mocks base method.
func (m *MockRepository) CountEmailsInFolder(arg0 context.Context, arg1 int64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountEmailsInFolder", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountEmailsInFolder indicates an expected call of CountEmailsInFolder.
func (mr *MockRepositoryMockRecorder) CountEmailsInFolder(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountEmailsInFolder", reflect.TypeOf((*MockRepository)(nil).CountEmailsInFolder), arg0, arg1)
}

// CountUserFolders mocks base method.
func (m *MockRepository) CountUserFolders(arg0 context.Context, arg1 int64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUserFolders", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUserFolders indicates an expected call of CountUserFolders.
func (mr *MockRepositoryMockRecorder) CountUserFolders(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUserFolders", reflect.TypeOf((*MockRepository)(nil).CountUserFolders), arg0, arg1)
}

// CreateFolder mocks base method.
func (m *MockRepository) CreateFolder(arg0 context.Context, arg1 models.Folder) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFolder", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateFolder indicates an expected call of CreateFolder.
func (mr *MockRepositoryMockRecorder) CreateFolder(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFolder", reflect.TypeOf((*MockRepository)(nil).CreateFolder), arg0, arg1)
}

// DeleteEmailFromFolder mocks base method.
func (m *MockRepository) DeleteEmailFromFolder(arg0 context.Context, arg1, arg2 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEmailFromFolder", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEmailFromFolder indicates an expected call of DeleteEmailFromFolder.
func (mr *MockRepositoryMockRecorder) DeleteEmailFromFolder(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEmailFromFolder", reflect.TypeOf((*MockRepository)(nil).DeleteEmailFromFolder), arg0, arg1, arg2)
}

// DeleteFolder mocks base method.
func (m *MockRepository) DeleteFolder(arg0 context.Context, arg1, arg2 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFolder", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFolder indicates an expected call of DeleteFolder.
func (mr *MockRepositoryMockRecorder) DeleteFolder(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFolder", reflect.TypeOf((*MockRepository)(nil).DeleteFolder), arg0, arg1, arg2)
}

// GetFolderByID mocks base method.
func (m *MockRepository) GetFolderByID(arg0 context.Context, arg1 int64) (*models.Folder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFolderByID", arg0, arg1)
	ret0, _ := ret[0].(*models.Folder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFolderByID indicates an expected call of GetFolderByID.
func (mr *MockRepositoryMockRecorder) GetFolderByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFolderByID", reflect.TypeOf((*MockRepository)(nil).GetFolderByID), arg0, arg1)
}

// GetFolderByName mocks base method.
func (m *MockRepository) GetFolderByName(arg0 context.Context, arg1 int64, arg2 string) (*models.Folder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFolderByName", arg0, arg1, arg2)
	ret0, _ := ret[0].(*models.Folder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFolderByName indicates an expected call of GetFolderByName.
func (mr *MockRepositoryMockRecorder) GetFolderByName(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFolderByName", reflect.TypeOf((*MockRepository)(nil).GetFolderByName), arg0, arg1, arg2)
}

// GetFolderEmailIDs mocks base method.
func (m *MockRepository) GetFolderEmailIDs(arg0 context.Context, arg1 int64, arg2, arg3 int) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFolderEmailIDs", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFolderEmailIDs indicates an expected call of GetFolderEmailIDs.
func (mr *MockRepositoryMockRecorder) GetFolderEmailIDs(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFolderEmailIDs", reflect.TypeOf((*MockRepository)(nil).GetFolderEmailIDs), arg0, arg1, arg2, arg3)
}

// GetUserFolders mocks base method.
func (m *MockRepository) GetUserFolders(arg0 context.Context, arg1 int64) ([]models.Folder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserFolders", arg0, arg1)
	ret0, _ := ret[0].([]models.Folder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserFolders indicates an expected call of GetUserFolders.
func (mr *MockRepositoryMockRecorder) GetUserFolders(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserFolders", reflect.TypeOf((*MockRepository)(nil).GetUserFolders), arg0, arg1)
}

// UpdateFolderName mocks base method.
func (m *MockRepository) UpdateFolderName(arg0 context.Context, arg1 int64, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFolderName", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFolderName indicates an expected call of UpdateFolderName.
func (mr *MockRepositoryMockRecorder) UpdateFolderName(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFolderName", reflect.TypeOf((*MockRepository)(nil).UpdateFolderName), arg0, arg1, arg2)
}
