// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2026_1_PushToMain/microservices/folder/delivery/http (interfaces: Service)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	service "github.com/go-park-mail-ru/2026_1_PushToMain/microservices/folder/service"
	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// AddEmailsInFolder mocks base method.
func (m *MockService) AddEmailsInFolder(arg0 context.Context, arg1 service.AddEmailsInFolderInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddEmailsInFolder", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddEmailsInFolder indicates an expected call of AddEmailsInFolder.
func (mr *MockServiceMockRecorder) AddEmailsInFolder(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddEmailsInFolder", reflect.TypeOf((*MockService)(nil).AddEmailsInFolder), arg0, arg1)
}

// ChangeFolderName mocks base method.
func (m *MockService) ChangeFolderName(arg0 context.Context, arg1 service.ChangeFolderNameInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeFolderName", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangeFolderName indicates an expected call of ChangeFolderName.
func (mr *MockServiceMockRecorder) ChangeFolderName(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeFolderName", reflect.TypeOf((*MockService)(nil).ChangeFolderName), arg0, arg1)
}

// CreateNewFolder mocks base method.
func (m *MockService) CreateNewFolder(arg0 context.Context, arg1 service.CreateNewFolderInput) (*service.CreateNewFolderResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNewFolder", arg0, arg1)
	ret0, _ := ret[0].(*service.CreateNewFolderResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNewFolder indicates an expected call of CreateNewFolder.
func (mr *MockServiceMockRecorder) CreateNewFolder(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNewFolder", reflect.TypeOf((*MockService)(nil).CreateNewFolder), arg0, arg1)
}

// DeleteEmailsFromFolder mocks base method.
func (m *MockService) DeleteEmailsFromFolder(arg0 context.Context, arg1 service.DeleteEmailsFromFolderInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEmailsFromFolder", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEmailsFromFolder indicates an expected call of DeleteEmailsFromFolder.
func (mr *MockServiceMockRecorder) DeleteEmailsFromFolder(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEmailsFromFolder", reflect.TypeOf((*MockService)(nil).DeleteEmailsFromFolder), arg0, arg1)
}

// DeleteFolder mocks base method.
func (m *MockService) DeleteFolder(arg0 context.Context, arg1 service.DeleteFolderInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFolder", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFolder indicates an expected call of DeleteFolder.
func (mr *MockServiceMockRecorder) DeleteFolder(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFolder", reflect.TypeOf((*MockService)(nil).DeleteFolder), arg0, arg1)
}

// GetEmailsFromFolder mocks base method.
func (m *MockService) GetEmailsFromFolder(arg0 context.Context, arg1 service.GetEmailsFromFolderInput) (*service.GetEmailsFromFolderResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmailsFromFolder", arg0, arg1)
	ret0, _ := ret[0].(*service.GetEmailsFromFolderResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmailsFromFolder indicates an expected call of GetEmailsFromFolder.
func (mr *MockServiceMockRecorder) GetEmailsFromFolder(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmailsFromFolder", reflect.TypeOf((*MockService)(nil).GetEmailsFromFolder), arg0, arg1)
}
