// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2026_1_PushToMain/microservices/folder/delivery/http (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -destination=../../../../mocks/app/folder/mock_handler_service.go -package=mocks github.com/go-park-mail-ru/2026_1_PushToMain/microservices/folder/delivery/http Service
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	service "github.com/go-park-mail-ru/2026_1_PushToMain/microservices/folder/service"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// AddEmailsInFolder mocks base method.
func (m *MockService) AddEmailsInFolder(ctx context.Context, input service.AddEmailsInFolderInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddEmailsInFolder", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddEmailsInFolder indicates an expected call of AddEmailsInFolder.
func (mr *MockServiceMockRecorder) AddEmailsInFolder(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddEmailsInFolder", reflect.TypeOf((*MockService)(nil).AddEmailsInFolder), ctx, input)
}

// ChangeFolderName mocks base method.
func (m *MockService) ChangeFolderName(ctx context.Context, input service.ChangeFolderNameInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeFolderName", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangeFolderName indicates an expected call of ChangeFolderName.
func (mr *MockServiceMockRecorder) ChangeFolderName(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeFolderName", reflect.TypeOf((*MockService)(nil).ChangeFolderName), ctx, input)
}

// CreateNewFolder mocks base method.
func (m *MockService) CreateNewFolder(ctx context.Context, input service.CreateNewFolderInput) (*service.CreateNewFolderResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNewFolder", ctx, input)
	ret0, _ := ret[0].(*service.CreateNewFolderResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNewFolder indicates an expected call of CreateNewFolder.
func (mr *MockServiceMockRecorder) CreateNewFolder(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNewFolder", reflect.TypeOf((*MockService)(nil).CreateNewFolder), ctx, input)
}

// DeleteEmailsFromFolder mocks base method.
func (m *MockService) DeleteEmailsFromFolder(ctx context.Context, input service.DeleteEmailsFromFolderInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEmailsFromFolder", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEmailsFromFolder indicates an expected call of DeleteEmailsFromFolder.
func (mr *MockServiceMockRecorder) DeleteEmailsFromFolder(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEmailsFromFolder", reflect.TypeOf((*MockService)(nil).DeleteEmailsFromFolder), ctx, input)
}

// DeleteFolder mocks base method.
func (m *MockService) DeleteFolder(ctx context.Context, input service.DeleteFolderInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFolder", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFolder indicates an expected call of DeleteFolder.
func (mr *MockServiceMockRecorder) DeleteFolder(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFolder", reflect.TypeOf((*MockService)(nil).DeleteFolder), ctx, input)
}

// GetEmailsFromFolder mocks base method.
func (m *MockService) GetEmailsFromFolder(ctx context.Context, input service.GetEmailsFromFolderInput) (*service.GetEmailsFromFolderResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmailsFromFolder", ctx, input)
	ret0, _ := ret[0].(*service.GetEmailsFromFolderResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmailsFromFolder indicates an expected call of GetEmailsFromFolder.
func (mr *MockServiceMockRecorder) GetEmailsFromFolder(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmailsFromFolder", reflect.TypeOf((*MockService)(nil).GetEmailsFromFolder), ctx, input)
}
