// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2026_1_PushToMain/internal/app/user/service (interfaces: DbRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../../../mocks/app/user/mock_db_repository.go -package=mocks github.com/go-park-mail-ru/2026_1_PushToMain/internal/app/user/service DbRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/go-park-mail-ru/2026_1_PushToMain/internal/app/user/models"
	gomock "go.uber.org/mock/gomock"
)

// MockDbRepository is a mock of DbRepository interface.
type MockDbRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDbRepositoryMockRecorder
	isgomock struct{}
}

// MockDbRepositoryMockRecorder is the mock recorder for MockDbRepository.
type MockDbRepositoryMockRecorder struct {
	mock *MockDbRepository
}

// NewMockDbRepository creates a new mock instance.
func NewMockDbRepository(ctrl *gomock.Controller) *MockDbRepository {
	mock := &MockDbRepository{ctrl: ctrl}
	mock.recorder = &MockDbRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDbRepository) EXPECT() *MockDbRepositoryMockRecorder {
	return m.recorder
}

// FindByEmail mocks base method.
func (m *MockDbRepository) FindByEmail(ctx context.Context, email string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByEmail", ctx, email)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByEmail indicates an expected call of FindByEmail.
func (mr *MockDbRepositoryMockRecorder) FindByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByEmail", reflect.TypeOf((*MockDbRepository)(nil).FindByEmail), ctx, email)
}

// FindByID mocks base method.
func (m *MockDbRepository) FindByID(ctx context.Context, userID int64) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, userID)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockDbRepositoryMockRecorder) FindByID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockDbRepository)(nil).FindByID), ctx, userID)
}

// Save mocks base method.
func (m *MockDbRepository) Save(ctx context.Context, user models.User) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, user)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockDbRepositoryMockRecorder) Save(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockDbRepository)(nil).Save), ctx, user)
}

// UpdateAvatar mocks base method.
func (m *MockDbRepository) UpdateAvatar(ctx context.Context, userID int64, imagePath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAvatar", ctx, userID, imagePath)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAvatar indicates an expected call of UpdateAvatar.
func (mr *MockDbRepositoryMockRecorder) UpdateAvatar(ctx, userID, imagePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAvatar", reflect.TypeOf((*MockDbRepository)(nil).UpdateAvatar), ctx, userID, imagePath)
}

// UpdatePassword mocks base method.
func (m *MockDbRepository) UpdatePassword(ctx context.Context, userID int64, passwordHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePassword", ctx, userID, passwordHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePassword indicates an expected call of UpdatePassword.
func (mr *MockDbRepositoryMockRecorder) UpdatePassword(ctx, userID, passwordHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePassword", reflect.TypeOf((*MockDbRepository)(nil).UpdatePassword), ctx, userID, passwordHash)
}

// UpdateProfile mocks base method.
func (m *MockDbRepository) UpdateProfile(ctx context.Context, userID int64, name, surname string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProfile", ctx, userID, name, surname)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProfile indicates an expected call of UpdateProfile.
func (mr *MockDbRepositoryMockRecorder) UpdateProfile(ctx, userID, name, surname any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfile", reflect.TypeOf((*MockDbRepository)(nil).UpdateProfile), ctx, userID, name, surname)
}
