definitions:
  handlers.AuthResponse:
    properties:
      token:
        type: string
    type: object
  handlers.SignInRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  handlers.SignUpRequest:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
      surname:
        type: string
    type: object
info:
  contact: {}
paths:
  /signin:
    post:
      consumes:
      - application/json
      description: Вход пользователя с выдачей JWT токена
      parameters:
      - description: Данные для входа
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.SignInRequest'
      produces:
      - application/json
      responses:
        "200":
          description: JWT токен
          schema:
            $ref: '#/definitions/handlers.AuthResponse'
        "400":
          description: BAD_REQUEST
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Авторизация пользователя
      tags:
      - auth
  /signup:
    post:
      consumes:
      - application/json
      description: Создает нового пользователя и возвращает JWT токен
      parameters:
      - description: Данные нового пользователя
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.SignUpRequest'
      produces:
      - application/json
      responses:
        "200":
          description: JWT токен
          schema:
            $ref: '#/definitions/handlers.AuthResponse'
        "400":
          description: BAD_REQUEST
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "409":
          description: User already exists
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Регистрация пользователя
      tags:
      - auth
swagger: "2.0"
