ALTER TABLE user_emails
    ADD COLUMN IF NOT EXISTS is_spam BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE user_emails
    ADD COLUMN IF NOT EXISTS is_draft BOOLEAN NOT NULL DEFAULT false;

CREATE TABLE spam_senders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id BIGINT NOT NULL,
    sender_id BIGINT NOT NULL,

    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    UNIQUE(user_id, sender_id)
);

CREATE TABLE draft_receivers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    email_id BIGINT NOT NULL REFERENCES emails(id) ON DELETE CASCADE,

    receiver_email TEXT NOT NULL,

    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT receiver_email_length_check
        CHECK (char_length(receiver_email) < 256)
);

CREATE INDEX idx_spam_senders_user_id
    ON spam_senders(user_id);

CREATE INDEX idx_draft_receivers_email_id
    ON draft_receivers(email_id);

CREATE INDEX idx_user_emails_spam_by_user
    ON user_emails(user_id, created_at DESC)
    WHERE is_spam = true;

CREATE INDEX idx_user_emails_trash_by_user
    ON user_emails(user_id, updated_at DESC)
    WHERE is_deleted = true;

CREATE INDEX idx_user_emails_drafts_by_user
    ON user_emails(user_id, updated_at DESC)
    WHERE is_draft = true AND is_sender = true;